# Place holder



```{r load_libraries}
library(dplyr)
library(readr)
```

```{r import_data}
source("R/import_data.R")
PM_MB_means <- import_data()
```


Data from `r length(PM_MB_means$trial_ref)` trials were collected and the means of each treatment calculated (`R/Cleaning historical data.R`). These data were combined into one file `1902 powdery mildew-Mungbean - Collated means.csv`.

```{r Calculate_yield-gains}
PM_MB_means$grain_yield.t.ha. <-
   as.numeric(PM_MB_means$grain_yield.t.ha.) # NAs produced due to some cells having text description to why there is no specific data

for (i in unique(PM_MB_means$trial_ref)) {
   dat1 <- PM_MB_means[PM_MB_means$trial_ref == i, ]
   
   if (any(is.na(unique(dat1$row_spacing)))) {
      warning(
         paste(
            unique(dat1$trial_ref),
            "at",
            unique(dat1$location),
            "in year",
            unique(dat1$year),
            "has unknown row.spacing (NA)\n 'yield_gain' and 'proportional yield gain' not calculated\n"
         )
      )
      next()
   }
   
   for (j in unique(dat1$row_spacing)) {
      dat2 <- dat1[dat1$row_spacing == j, ]
      controlY <-
         mean(dat2[dat2$fungicide == "control", "grain_yield.t.ha."])
      
      dat2$yield_gain <- dat2$grain_yield.t.ha. - controlY
      dat2$prop_YG <- dat2$yield_gain  /  controlY
      
      dat2[dat2$fungicide == "control", c("yield_gain", "prop_YG")] <-
         NA
      
      dat1[dat1$row_spacing == j, ] <- dat2
   }
   PM_MB_means[PM_MB_means$trial_ref == i, ] <- dat1
}



# ____________________________________________
# calculate yield gain and prop_yield gain for experiments with no row spacing data

# dat1 <- PM_MB_means[PM_MB_means$trial_ref == "AM1303", ]
# 
# controlY <-
#    mean(dat1[dat1$fungicide == "control", "grain_yield.t.ha."])
# 
# dat1$yield_gain <- dat1$grain_yield.t.ha. - controlY
# dat1$prop_YG <- dat1$yield_gain / controlY
# dat1[dat1$fungicide == "control", c("yield_gain", "prop_YG")] <- NA
# PM_MB_means[PM_MB_means$trial_ref == "AM1303", ] <- dat1

write.csv(PM_MB_means,
          "data/1902 PM_MB_means&Ygains.csv")
```




```{r clustered_fungicide_applications}
source("R/slimming_PM_dat.R")
head(slim_PM_dat)


slim_PM_dat %<>%
  mutate(fungicide_timing_1 = fungicide_application_1 - first_sign_disease) %>%
  mutate(fungicide_timing_2 = fungicide_application_2 - fungicide_application_1) %>%
  mutate(fungicide_timing_3 = fungicide_application_3 - fungicide_application_2) %>%
  filter(!is.na(grain_yield.t.ha)) %>% 
  filter(!is.na(PM_final_severity))


```


```{r cluster}

slim_PM_dat %<>%
  mutate(
    cluster_1 = case_when(
      fungicide_timing_1 < 0 ~ "Early",
      fungicide_timing_1 >= 0 &
        fungicide_timing_1 < 4 ~ "Recommended",
      TRUE ~ "Late"
    )
  ) %>%
  mutate(
    cluster_2 = case_when(
      fungicide_timing_2 < 13 ~ "Early",
      fungicide_timing_2 >= 13 &
        fungicide_timing_2 < 17 ~ "Recommended",
      TRUE ~ "Late"
    )
  ) %>% 
  mutate(
    cluster_3 = case_when(
      fungicide_timing_3 < 14 ~ "Early",
      TRUE ~ "Recommended"
    )
  )

slim_PM_dat[slim_PM_dat$fungicide_ai == "control", c("fungicide_timing_1", "fungicide_timing_2", "fungicide_timing_3",
                                                     "cluster_1", "cluster_2","cluster_3")] <- "control"


```
