---
title: Meta-analysis of fungicide application timing for powdery mildew management
  in mungbean.
author: "P. Melloy"
date: "31/01/2020"
output:
  html_document: default
bibliography: Mungbean.bib
---

# Manuscript wireframe

## Who are the intended readers? - list 3 to 5 of them by name
   * Adam Sparks – Plant disease modeller
   * Levente Kiss – Powdery mildew taxonomist
   * Lisa Kelly – Plant pathologist
   * Paul MacIntosh – Mungbean/ pulse agronomist
   * Ross Pomroy – Agronomist
   * Jean Galloway – Plant disease modeller
   * Art Diggle – Plant disease modeller

## what did you do? (limit - 50 words)
Undertook a meta-analysis of twenty four field trials aimed at improving the efficiency and timing of fungicides for control of powdery mildew on mungbean.


## Why did you do it? (limit - 50 words)  
Data from unpublished field trials independently did not provide a clear indication for when to apply fungicide to best mitigate yield losses from powdery mildew. 
By analysing the collective data we aim to provide a better estimate for fungicide application timing to mitigate the yield loss from powdery mildew.  

## what happened? (limit - 50 words)  
We found that fungicide sprays prior to when the powdery mildew was first spotted in the mungbean crop on average provided no yield protection. 
A fungicide spray schedule of one or more fungicide applications commencing within three days of first sign of the disease significantly mitigated yield loss to the disease. 
However a fungicide spray schedule of 2 or more applications commencing four days or later than first sign of disease saved the most yield.

## What do the results mean in theory? (limit - 50 words)
Fungicide spray schedules for control of powdery mildew in mungbean should commence around seven to nine days following the first signs of the disease.


## What do the results mean in practice? (limit - 50 words)  
Primarily that fungicide spray schedules that commence prior to signs of the disease establishing in the mungbean canopy are likely to be ineffective at mitigating the diseases impact on yield. 
We also don’t have data on at what point starting a fungicide spray schedule is too late. 
Growers can’t scout their crop three times a week in the fashion of researchers and are unlikely to identify the true date when signs of powdery mildew become apparent. 
Therefore these results reinforce the message to growers to spray for powdery mildew as soon as it is observed in their crop to protect yields.

## what is the key benefit for your readers? (limit - 25 words).  
This study is the most robust analysis of management of powdery mildew in mungbean using fungicides. 
It provides a more certain time frame for growers to plan when to commence a fungicide spray schedule.  

Fewer fungicide applications will reduce costs for growers and prolong the efficacy of fungicides before the disease develops resistance.


## What remains unresolved? (no word limit).  
Within the meta-analysis, some comparisons between spray management factors contained fewer replicates in comparison to other spray management factor combinations.
Only a few studies incorporated in the meta-analysis contained comparisons between the “Late plus” factor and the treatments: negative spray control, a single spray at first sign, and spray at first sign with one or more follow-up applications.



# Manuscript

## Introduction
Mungbean is a short season summer pulse crop which can provide a high returns for growers in eastern Australia. 
Mungbean can potentially yield up to 2.3 tonnes per hectare, with a value of up to \$ 1300 a tonne [AgMargins; 2019](https://agmargins.net.au/Reports/Details/fced3a80-a762-481c-b812-9953e33410e6). 
Powdery mildew _Podosphaera xanthii_ can potentially cause yield losses on mungbean of up to 43% [Kelly et. al 2017](https://grdc.com.au/resources-and-publications/grdc-update-papers/tab-content/grdc-update-papers/2017/07/mungbean-and-sorghum-disease-update). 
Fortunatley a number of strategies are employed to reduce the damage powdery mildew inflicts on yields.
### Managements strategies
#### and conditions for infection
Powdery mildew infection requires cool temperatures (22$^\circ$ - 26$^\circ$C) and a leaf surface that is not overly wet for infection [Kelly et. al 2017](https://grdc.com.au/resources-and-publications/grdc-update-papers/tab-content/grdc-update-papers/2017/07/mungbean-and-sorghum-disease-update). In southern Queensland and northern New South Wales, planting dates between late spring (November) and mid-summer (January) are advised to avoid the conducsive cooler autumn temperatures which normally commence in March in the southern hemisphere conducive for powdery mildew establishment.
Signs of powdery mildew are almost always first observed when temperatures start to cool.

### Fungicide resistance
Lucritive returns of \$ 2260 over a short three month season may tempt growers into applying fungicide to control diseases such as powdery mildew more than they are needed.

### Previous studies

### Meta-analyes

### Aims

## Materials and methods
