<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 AUPDC meta-analysis | Powdery mildew yield loss mitigation strategies in mungbean, a meta-analysis.</title>
  <meta name="description" content="A meta-analysis of fungicide use in mungbean to control for yield loss due to powdery mildew." />
  <meta name="generator" content="bookdown 0.19 and GitBook 2.6.7" />

  <meta property="og:title" content="6 AUPDC meta-analysis | Powdery mildew yield loss mitigation strategies in mungbean, a meta-analysis." />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A meta-analysis of fungicide use in mungbean to control for yield loss due to powdery mildew." />
  <meta name="github-repo" content="OpenPlantPathology/Mungbean_PM" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 AUPDC meta-analysis | Powdery mildew yield loss mitigation strategies in mungbean, a meta-analysis." />
  
  <meta name="twitter:description" content="A meta-analysis of fungicide use in mungbean to control for yield loss due to powdery mildew." />
  

<meta name="author" content="Paul Melloy, Emerson Del Ponte and Adam H. Sparks" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="meta-analysis.html"/>
<link rel="next" href="manuscript-wire-frame.html"/>
<script src="libs/header-attrs-2.1/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Research questions</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#parts-of-analysis-that-need-checking"><i class="fa fa-check"></i><b>1.1</b> Parts of analysis that need checking</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="studies-considered-in-meta-analysis.html"><a href="studies-considered-in-meta-analysis.html"><i class="fa fa-check"></i><b>2</b> Studies considered in meta-analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="studies-considered-in-meta-analysis.html"><a href="studies-considered-in-meta-analysis.html#summary-of-data"><i class="fa fa-check"></i><b>2.1</b> Summary of data</a></li>
<li class="chapter" data-level="2.2" data-path="studies-considered-in-meta-analysis.html"><a href="studies-considered-in-meta-analysis.html#powdery-mildew-ratings"><i class="fa fa-check"></i><b>2.2</b> Powdery mildew ratings</a></li>
<li class="chapter" data-level="2.3" data-path="studies-considered-in-meta-analysis.html"><a href="studies-considered-in-meta-analysis.html#experimental-locations"><i class="fa fa-check"></i><b>2.3</b> Experimental locations</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html"><i class="fa fa-check"></i><b>3</b> Preliminary Analysis</a>
<ul>
<li class="chapter" data-level="3.1" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#explore-and-visualise-data"><i class="fa fa-check"></i><b>3.1</b> Explore and Visualise Data</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#fungicides"><i class="fa fa-check"></i><b>3.1.1</b> Fungicides</a></li>
<li class="chapter" data-level="3.1.2" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#mungbean-cultivars"><i class="fa fa-check"></i><b>3.1.2</b> Mungbean cultivars</a></li>
<li class="chapter" data-level="3.1.3" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#row-spacing"><i class="fa fa-check"></i><b>3.1.3</b> Row spacing</a></li>
<li class="chapter" data-level="3.1.4" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#yield-vs-in-season-rain"><i class="fa fa-check"></i><b>3.1.4</b> Yield vs in-season rain</a></li>
<li class="chapter" data-level="3.1.5" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#season-range-and-first-incidence"><i class="fa fa-check"></i><b>3.1.5</b> Season range and first incidence</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html"><i class="fa fa-check"></i><b>4</b> Prepare data for meta-analysis</a>
<ul>
<li class="chapter" data-level="4.1" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#set-environment-and-import-data"><i class="fa fa-check"></i><b>4.1</b> Set environment and import data</a></li>
<li class="chapter" data-level="4.2" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#standardising-sample-variance"><i class="fa fa-check"></i><b>4.2</b> Standardising sample variance</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#converting-least-squares-to-sample-variance"><i class="fa fa-check"></i><b>4.2.1</b> Converting least-squares to sample variance</a></li>
<li class="chapter" data-level="4.2.2" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#converting-standard-deviation-to-sample-variance"><i class="fa fa-check"></i><b>4.2.2</b> Converting standard deviation to sample variance</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#yield-saving"><i class="fa fa-check"></i><b>4.3</b> Yield saving</a></li>
<li class="chapter" data-level="4.4" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#reduce-data-set-to-required-variables"><i class="fa fa-check"></i><b>4.4</b> Reduce data set to required variables</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#cluster-fungicide-applications"><i class="fa fa-check"></i><b>4.4.1</b> Cluster fungicide applications</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#audpc-visualise-raw-data"><i class="fa fa-check"></i><b>4.5</b> AUDPC visualise raw data</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="meta-analysis.html"><a href="meta-analysis.html"><i class="fa fa-check"></i><b>5</b> Meta-analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="meta-analysis.html"><a href="meta-analysis.html#grain-yield-meta-analysis"><i class="fa fa-check"></i><b>5.1</b> Grain yield meta-analysis</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="meta-analysis.html"><a href="meta-analysis.html#imputing-sample-variances"><i class="fa fa-check"></i><b>5.1.1</b> Imputing sample variances</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="meta-analysis.html"><a href="meta-analysis.html#meta-analysis-1"><i class="fa fa-check"></i><b>5.2</b> Meta-analysis</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="meta-analysis.html"><a href="meta-analysis.html#metafor-package"><i class="fa fa-check"></i><b>5.2.1</b> metafor package</a></li>
<li class="chapter" data-level="5.2.2" data-path="meta-analysis.html"><a href="meta-analysis.html#netmeta-package"><i class="fa fa-check"></i><b>5.2.2</b> netmeta package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="aupdc-meta-analysis.html"><a href="aupdc-meta-analysis.html"><i class="fa fa-check"></i><b>6</b> AUPDC meta-analysis</a>
<ul>
<li class="chapter" data-level="6.0.1" data-path="aupdc-meta-analysis.html"><a href="aupdc-meta-analysis.html#spray-management-and-audpc"><i class="fa fa-check"></i><b>6.0.1</b> Spray management and AUDPC</a></li>
<li class="chapter" data-level="6.1" data-path="aupdc-meta-analysis.html"><a href="aupdc-meta-analysis.html#aupdc-impact-on-grain-yield-meta-analysis"><i class="fa fa-check"></i><b>6.1</b> AUPDC impact on grain yield meta-analysis</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html"><i class="fa fa-check"></i><b>7</b> Manuscript wire frame</a>
<ul>
<li class="chapter" data-level="7.1" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#who-are-the-intended-readers---list-3-to-5-of-them-by-name"><i class="fa fa-check"></i><b>7.1</b> Who are the intended readers? - list 3 to 5 of them by name</a></li>
<li class="chapter" data-level="7.2" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-did-you-do-limit---50-words"><i class="fa fa-check"></i><b>7.2</b> what did you do? (limit - 50 words)</a></li>
<li class="chapter" data-level="7.3" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#why-did-you-do-it-limit---50-words"><i class="fa fa-check"></i><b>7.3</b> Why did you do it? (limit - 50 words)</a></li>
<li class="chapter" data-level="7.4" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-happened-limit---50-words"><i class="fa fa-check"></i><b>7.4</b> what happened? (limit - 50 words)</a></li>
<li class="chapter" data-level="7.5" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-do-the-results-mean-in-theory-limit---50-words"><i class="fa fa-check"></i><b>7.5</b> What do the results mean in theory? (limit - 50 words)</a></li>
<li class="chapter" data-level="7.6" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-do-the-results-mean-in-practice-limit---50-words"><i class="fa fa-check"></i><b>7.6</b> What do the results mean in practice? (limit - 50 words)</a></li>
<li class="chapter" data-level="7.7" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-is-the-key-benefit-for-your-readers-limit---25-words."><i class="fa fa-check"></i><b>7.7</b> what is the key benefit for your readers? (limit - 25 words).</a></li>
<li class="chapter" data-level="7.8" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-remains-unresolved-no-word-limit."><i class="fa fa-check"></i><b>7.8</b> What remains unresolved? (no word limit).</a></li>
<li class="chapter" data-level="7.9" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#introduction"><i class="fa fa-check"></i><b>7.9</b> Introduction</a>
<ul>
<li class="chapter" data-level="7.9.1" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#managements-strategies"><i class="fa fa-check"></i><b>7.9.1</b> Managements strategies</a></li>
<li class="chapter" data-level="7.9.2" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#fungicide-resistance"><i class="fa fa-check"></i><b>7.9.2</b> Fungicide resistance</a></li>
<li class="chapter" data-level="7.9.3" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#previous-studies---fungicide-work"><i class="fa fa-check"></i><b>7.9.3</b> Previous studies - fungicide work</a></li>
<li class="chapter" data-level="7.9.4" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#meta-analysis-2"><i class="fa fa-check"></i><b>7.9.4</b> Meta-analysis</a></li>
<li class="chapter" data-level="7.9.5" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#aims"><i class="fa fa-check"></i><b>7.9.5</b> Aims</a></li>
</ul></li>
<li class="chapter" data-level="7.10" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#materials-and-methods"><i class="fa fa-check"></i><b>7.10</b> Materials and methods</a></li>
<li class="chapter" data-level="7.11" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#discussion"><i class="fa fa-check"></i><b>7.11</b> Discussion</a>
<ul>
<li class="chapter" data-level="7.11.1" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#fungicide-resistance-1"><i class="fa fa-check"></i><b>7.11.1</b> Fungicide resistance</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Powdery mildew yield loss mitigation strategies in mungbean, a meta-analysis.</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="aupdc-meta-analysis" class="section level1" number="6">
<h1><span class="header-section-number">6</span> AUPDC meta-analysis</h1>
<p>Now it’s time to look at how the spray management scenarios might impact disease pressure on the mungbean yields. First let’s evaluate which measure of disease is the most robust predictor for yield loss, AUDPC, AUDPS or disease incidence at the end of the season.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="aupdc-meta-analysis.html#cb1-1"></a>PM_Mdat<span class="op">$</span>slope &lt;-<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb1-2"><a href="aupdc-meta-analysis.html#cb1-2"></a>PM_Mdat<span class="op">$</span>SE &lt;-<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb1-3"><a href="aupdc-meta-analysis.html#cb1-3"></a><span class="cf">for</span> (i <span class="cf">in</span> PM_Mdat<span class="op">$</span>trial) {</span>
<span id="cb1-4"><a href="aupdc-meta-analysis.html#cb1-4"></a>   PM_Mdat[PM_Mdat<span class="op">$</span>trial <span class="op">==</span><span class="st"> </span>i, <span class="kw">c</span>(<span class="st">&quot;slope&quot;</span>, <span class="st">&quot;SE&quot;</span>)] &lt;-</span>
<span id="cb1-5"><a href="aupdc-meta-analysis.html#cb1-5"></a><span class="st">      </span><span class="kw">coef</span>(<span class="kw">summary</span>(<span class="kw">lm</span>(grain_yield.t.ha <span class="op">~</span><span class="st"> </span>AUDPC_m, <span class="dt">data =</span> PM_Mdat[PM_Mdat<span class="op">$</span>trial <span class="op">==</span><span class="st"> </span>i, ])))[<span class="dv">2</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>]</span>
<span id="cb1-6"><a href="aupdc-meta-analysis.html#cb1-6"></a>}</span>
<span id="cb1-7"><a href="aupdc-meta-analysis.html#cb1-7"></a></span>
<span id="cb1-8"><a href="aupdc-meta-analysis.html#cb1-8"></a><span class="kw">plot</span>(<span class="dv">1</span> <span class="op">/</span><span class="st"> </span>SE <span class="op">~</span><span class="st"> </span>slope,</span>
<span id="cb1-9"><a href="aupdc-meta-analysis.html#cb1-9"></a>     <span class="dt">data =</span> PM_Mdat,</span>
<span id="cb1-10"><a href="aupdc-meta-analysis.html#cb1-10"></a>     <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">3000</span>, <span class="dv">6000</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/AUDPC_funnel-1.png" width="672" /></p>
<p>Now it’s time to look at how the spray management scenarios might impact disease pressure on the mungbean yields. First lets evaluate which measure of disease is the most robust predictor for yield loss, AUDPC, AUDPS or disease incidence at the end of the season.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="aupdc-meta-analysis.html#cb2-1"></a><span class="kw">library</span>(MuMIn)</span>
<span id="cb2-2"><a href="aupdc-meta-analysis.html#cb2-2"></a><span class="kw">summary</span>(<span class="kw">lm</span>(grain_yield.t.ha <span class="op">~</span><span class="st"> </span>AUDPC_m, <span class="dt">data =</span> PM_Mdat))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = grain_yield.t.ha ~ AUDPC_m, data = PM_Mdat)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -0.929 -0.481 -0.120  0.404  1.352 
## 
## Coefficients:
##             Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept) 1.022121   0.099531   10.27 &lt;0.0000000000000002 ***
## AUDPC_m     0.000961   0.000656    1.46                0.15    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.581 on 149 degrees of freedom
## Multiple R-squared:  0.0142, Adjusted R-squared:  0.00757 
## F-statistic: 2.14 on 1 and 149 DF,  p-value: 0.145</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="aupdc-meta-analysis.html#cb4-1"></a><span class="kw">summary</span>(<span class="kw">lm</span>(grain_yield.t.ha <span class="op">~</span><span class="st"> </span>AUDPS_m, <span class="dt">data =</span> PM_Mdat))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = grain_yield.t.ha ~ AUDPS_m, data = PM_Mdat)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -0.873 -0.496 -0.128  0.429  1.367 
## 
## Coefficients:
##             Estimate Std. Error t value            Pr(&gt;|t|)    
## (Intercept) 1.078433   0.107351   10.05 &lt;0.0000000000000002 ***
## AUDPS_m     0.000430   0.000576    0.75                0.46    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.584 on 149 degrees of freedom
## Multiple R-squared:  0.00374,    Adjusted R-squared:  -0.00295 
## F-statistic: 0.559 on 1 and 149 DF,  p-value: 0.456</code></pre>
<p>Area under the disease progress stairs (AUDPS) shows almost the same fit as the AUDPC linear model. AUDPC and AUDPS are not good predictors of loss in yield overall, without the inclusion of a <code>trial</code> parameter. Let’s test the model with the inclusion of <code>trial</code> as a random effect.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="aupdc-meta-analysis.html#cb6-1"></a>Me_mod1 &lt;-<span class="st"> </span><span class="kw">lmer</span>(grain_yield.t.ha <span class="op">~</span><span class="st"> </span>AUDPC_m <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>trial),</span>
<span id="cb6-2"><a href="aupdc-meta-analysis.html#cb6-2"></a>                <span class="dt">data =</span> PM_Mdat)</span>
<span id="cb6-3"><a href="aupdc-meta-analysis.html#cb6-3"></a><span class="kw">summary</span>(Me_mod1)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: grain_yield.t.ha ~ AUDPC_m + (1 | trial)
##    Data: PM_Mdat
## 
## REML criterion at convergence: -3.7
## 
## Scaled residuals: 
##    Min     1Q Median     3Q    Max 
## -3.441 -0.412  0.023  0.490  2.710 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  trial    (Intercept) 0.3110   0.558   
##  Residual             0.0261   0.162   
## Number of obs: 151, groups:  trial, 25
## 
## Fixed effects:
##              Estimate Std. Error t value
## (Intercept)  1.303569   0.118253   11.02
## AUDPC_m     -0.001460   0.000337   -4.34
## 
## Correlation of Fixed Effects:
##         (Intr)
## AUDPC_m -0.306</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="aupdc-meta-analysis.html#cb8-1"></a><span class="kw">r.squaredGLMM</span>(Me_mod1)</span></code></pre></div>
<pre><code>## Warning: &#39;r.squaredGLMM&#39; now calculates a revised statistic. See the help page.</code></pre>
<pre><code>##          R2m    R2c
## [1,] 0.03201 0.9251</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="aupdc-meta-analysis.html#cb11-1"></a>Me_mod1.s &lt;-<span class="st"> </span><span class="kw">lmer</span>(grain_yield.t.ha <span class="op">~</span><span class="st"> </span>AUDPS_m <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>trial),</span>
<span id="cb11-2"><a href="aupdc-meta-analysis.html#cb11-2"></a>                  <span class="dt">data =</span> PM_Mdat)</span>
<span id="cb11-3"><a href="aupdc-meta-analysis.html#cb11-3"></a><span class="kw">summary</span>(Me_mod1.s)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: grain_yield.t.ha ~ AUDPS_m + (1 | trial)
##    Data: PM_Mdat
## 
## REML criterion at convergence: -2
## 
## Scaled residuals: 
##    Min     1Q Median     3Q    Max 
## -3.417 -0.406  0.000  0.479  2.821 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  trial    (Intercept) 0.3007   0.548   
##  Residual             0.0265   0.163   
## Number of obs: 151, groups:  trial, 25
## 
## Fixed effects:
##             Estimate Std. Error t value
## (Intercept)  1.29267    0.11617   11.13
## AUDPS_m     -0.00104    0.00025   -4.16
## 
## Correlation of Fixed Effects:
##         (Intr)
## AUDPS_m -0.302</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="aupdc-meta-analysis.html#cb13-1"></a><span class="kw">r.squaredGLMM</span>(Me_mod1)</span></code></pre></div>
<pre><code>##          R2m    R2c
## [1,] 0.03201 0.9251</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="aupdc-meta-analysis.html#cb15-1"></a><span class="kw">r.squaredGLMM</span>(Me_mod1.s)</span></code></pre></div>
<pre><code>##          R2m    R2c
## [1,] 0.02215 0.9208</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="aupdc-meta-analysis.html#cb17-1"></a><span class="kw">anova</span>(Me_mod1, Me_mod1.s)</span></code></pre></div>
<pre><code>## refitting model(s) with ML (instead of REML)</code></pre>
<pre><code>## Data: PM_Mdat
## Models:
## Me_mod1: grain_yield.t.ha ~ AUDPC_m + (1 | trial)
## Me_mod1.s: grain_yield.t.ha ~ AUDPS_m + (1 | trial)
##           npar   AIC    BIC logLik deviance Chisq Df Pr(&gt;Chisq)
## Me_mod1      4 -12.4 -0.350  10.21    -20.4                    
## Me_mod1.s    4 -11.3  0.776   9.65    -19.3     0  0          1</code></pre>
<p>AUDPC becomes a significant predictor of grain yield when the random effect when accounting for <code>trial</code>. However we noticed in the plots earlier that not only the intercept but the slope varies depending on the trial. Let’s see if the model improves when AUDPC is used as a random slope for trial.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="aupdc-meta-analysis.html#cb20-1"></a>Me_mod2 &lt;-<span class="st"> </span><span class="kw">lmer</span>(grain_yield.t.ha <span class="op">~</span><span class="st"> </span>AUDPC_m <span class="op">+</span><span class="st"> </span>(AUDPC_m <span class="op">|</span><span class="st"> </span>trial),</span>
<span id="cb20-2"><a href="aupdc-meta-analysis.html#cb20-2"></a>                <span class="dt">data =</span> PM_Mdat)</span></code></pre></div>
<pre><code>## boundary (singular) fit: see ?isSingular</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="aupdc-meta-analysis.html#cb22-1"></a><span class="kw">anova</span>(Me_mod1, Me_mod2)</span></code></pre></div>
<pre><code>## refitting model(s) with ML (instead of REML)</code></pre>
<pre><code>## Data: PM_Mdat
## Models:
## Me_mod1: grain_yield.t.ha ~ AUDPC_m + (1 | trial)
## Me_mod2: grain_yield.t.ha ~ AUDPC_m + (AUDPC_m | trial)
##         npar   AIC    BIC logLik deviance Chisq Df  Pr(&gt;Chisq)    
## Me_mod1    4 -12.4  -0.35   10.2    -20.4                         
## Me_mod2    6 -44.6 -26.53   28.3    -56.6  36.2  2 0.000000014 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The model is significantly improved, lower AIC and a higher log likelihood. Let’s see if AUDPS improves in the same way.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="aupdc-meta-analysis.html#cb25-1"></a>Me_mod2.s &lt;-<span class="st"> </span><span class="kw">lmer</span>(grain_yield.t.ha <span class="op">~</span><span class="st"> </span>AUDPS_m <span class="op">+</span><span class="st"> </span>(AUDPS_m <span class="op">|</span><span class="st"> </span>trial),</span>
<span id="cb25-2"><a href="aupdc-meta-analysis.html#cb25-2"></a>                  <span class="dt">data =</span> PM_Mdat)</span></code></pre></div>
<pre><code>## Warning in checkConv(attr(opt, &quot;derivs&quot;), opt$par, ctrl = control$checkConv, :
## Model failed to converge with max|grad| = 6.55841 (tol = 0.002, component 1)</code></pre>
<pre><code>## Warning in checkConv(attr(opt, &quot;derivs&quot;), opt$par, ctrl = control$checkConv, : Model is nearly unidentifiable: very large eigenvalue
##  - Rescale variables?</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="aupdc-meta-analysis.html#cb28-1"></a><span class="kw">anova</span>(Me_mod1.s, Me_mod2.s)</span></code></pre></div>
<pre><code>## refitting model(s) with ML (instead of REML)</code></pre>
<pre><code>## Data: PM_Mdat
## Models:
## Me_mod1.s: grain_yield.t.ha ~ AUDPS_m + (1 | trial)
## Me_mod2.s: grain_yield.t.ha ~ AUDPS_m + (AUDPS_m | trial)
##           npar   AIC    BIC logLik deviance Chisq Df  Pr(&gt;Chisq)    
## Me_mod1.s    4 -11.3   0.78   9.65    -19.3                         
## Me_mod2.s    6 -42.4 -24.31  27.21    -54.4  35.1  2 0.000000024 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The model did improve, however AUDPC still shows a better fit as shown by a lower AIC and a model which converged.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="aupdc-meta-analysis.html#cb31-1"></a><span class="kw">r.squaredGLMM</span>(Me_mod2.s) <span class="co"># Rsquared for AUDPStairs</span></span></code></pre></div>
<pre><code>##          R2m    R2c
## [1,] 0.06548 0.8894</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="aupdc-meta-analysis.html#cb33-1"></a><span class="kw">r.squaredGLMM</span>(Me_mod2)<span class="co"># Rsquared for AUDPCurve</span></span></code></pre></div>
<pre><code>##          R2m   R2c
## [1,] 0.07195 0.939</code></pre>
<p>The R-squared of the AUDPC model is a better fit compared to the AUDPS model, and has a conditional <span class="math inline">\(R^2\)</span> value of 0.939.
&gt; From here on we will use AUDPC.</p>
<p>Let’s compare the area under the disease progress curve (AUDPC) to final severity.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="aupdc-meta-analysis.html#cb35-1"></a>Me_mod3 &lt;-<span class="st"> </span><span class="kw">lmer</span>(grain_yield.t.ha <span class="op">~</span><span class="st"> </span>PM_final_severity <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>trial),</span>
<span id="cb35-2"><a href="aupdc-meta-analysis.html#cb35-2"></a>                <span class="dt">data =</span> PM_Mdat)</span>
<span id="cb35-3"><a href="aupdc-meta-analysis.html#cb35-3"></a>Me_mod4 &lt;-</span>
<span id="cb35-4"><a href="aupdc-meta-analysis.html#cb35-4"></a><span class="st">   </span><span class="kw">lmer</span>(grain_yield.t.ha <span class="op">~</span><span class="st"> </span>PM_final_severity <span class="op">+</span><span class="st"> </span>(PM_final_severity <span class="op">|</span></span>
<span id="cb35-5"><a href="aupdc-meta-analysis.html#cb35-5"></a><span class="st">                                                   </span>trial),</span>
<span id="cb35-6"><a href="aupdc-meta-analysis.html#cb35-6"></a>        <span class="dt">data =</span> PM_Mdat)</span>
<span id="cb35-7"><a href="aupdc-meta-analysis.html#cb35-7"></a><span class="kw">anova</span>(Me_mod3, Me_mod4)</span></code></pre></div>
<pre><code>## refitting model(s) with ML (instead of REML)</code></pre>
<pre><code>## Data: PM_Mdat
## Models:
## Me_mod3: grain_yield.t.ha ~ PM_final_severity + (1 | trial)
## Me_mod4: grain_yield.t.ha ~ PM_final_severity + (PM_final_severity | trial)
##         npar   AIC  BIC logLik deviance Chisq Df Pr(&gt;Chisq)   
## Me_mod3    4 -3.55 8.52   5.78    -11.6                       
## Me_mod4    6 -9.81 8.30  10.90    -21.8  10.3  2     0.0059 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="aupdc-meta-analysis.html#cb38-1"></a><span class="kw">summary</span>(Me_mod4)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: grain_yield.t.ha ~ PM_final_severity + (PM_final_severity | trial)
##    Data: PM_Mdat
## 
## REML criterion at convergence: -12.6
## 
## Scaled residuals: 
##    Min     1Q Median     3Q    Max 
## -3.226 -0.369 -0.011  0.445  2.671 
## 
## Random effects:
##  Groups   Name              Variance Std.Dev. Corr 
##  trial    (Intercept)       1.07423  1.0365        
##           PM_final_severity 0.00543  0.0737   -0.95
##  Residual                   0.02262  0.1504        
## Number of obs: 151, groups:  trial, 25
## 
## Fixed effects:
##                   Estimate Std. Error t value
## (Intercept)         1.4942     0.2196    6.80
## PM_final_severity  -0.0507     0.0185   -2.75
## 
## Correlation of Fixed Effects:
##             (Intr)
## PM_fnl_svrt -0.911</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="aupdc-meta-analysis.html#cb40-1"></a><span class="kw">r.squaredGLMM</span>(Me_mod4)</span></code></pre></div>
<pre><code>##         R2m   R2c
## [1,] 0.0281 0.945</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="aupdc-meta-analysis.html#cb42-1"></a><span class="co"># PM_final_incidence vs AUDPC</span></span>
<span id="cb42-2"><a href="aupdc-meta-analysis.html#cb42-2"></a><span class="kw">anova</span>(Me_mod4, Me_mod2)</span></code></pre></div>
<pre><code>## refitting model(s) with ML (instead of REML)</code></pre>
<pre><code>## Data: PM_Mdat
## Models:
## Me_mod4: grain_yield.t.ha ~ PM_final_severity + (PM_final_severity | trial)
## Me_mod2: grain_yield.t.ha ~ AUDPC_m + (AUDPC_m | trial)
##         npar   AIC   BIC logLik deviance Chisq Df          Pr(&gt;Chisq)    
## Me_mod4    6  -9.8   8.3   10.9    -21.8                                 
## Me_mod2    6 -44.6 -26.5   28.3    -56.6  34.8  0 &lt;0.0000000000000002 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Powdery mildew incidence at the end of the season was a significant covariate for grain yield, however was a weaker predictor compared to AUDPC. In addition model comparison shows AUDPC is significantly better at predicting grain yield.</p>
<div id="spray-management-and-audpc" class="section level3" number="6.0.1">
<h3><span class="header-section-number">6.0.1</span> Spray management and AUDPC</h3>
<p>We shall proceed by including the spray management predictor into the analysis.
First let’s assess the <code>spray_management</code> variable as an additive fixed effect.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="aupdc-meta-analysis.html#cb45-1"></a>Me_mod5 &lt;-</span>
<span id="cb45-2"><a href="aupdc-meta-analysis.html#cb45-2"></a><span class="st">   </span><span class="kw">lmer</span>(grain_yield.t.ha <span class="op">~</span><span class="st"> </span>AUDPC_m <span class="op">+</span><span class="st"> </span>spray_management <span class="op">+</span><span class="st"> </span>(AUDPC_m <span class="op">|</span></span>
<span id="cb45-3"><a href="aupdc-meta-analysis.html#cb45-3"></a><span class="st">                                                            </span>trial),</span>
<span id="cb45-4"><a href="aupdc-meta-analysis.html#cb45-4"></a>        <span class="dt">data =</span> PM_Mdat)</span></code></pre></div>
<pre><code>## boundary (singular) fit: see ?isSingular</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="aupdc-meta-analysis.html#cb47-1"></a><span class="kw">anova</span>(Me_mod2, Me_mod5)</span></code></pre></div>
<pre><code>## refitting model(s) with ML (instead of REML)</code></pre>
<pre><code>## Data: PM_Mdat
## Models:
## Me_mod2: grain_yield.t.ha ~ AUDPC_m + (AUDPC_m | trial)
## Me_mod5: grain_yield.t.ha ~ AUDPC_m + spray_management + (AUDPC_m | trial)
##         npar   AIC   BIC logLik deviance Chisq Df Pr(&gt;Chisq)   
## Me_mod2    6 -44.6 -26.5   28.3    -56.6                       
## Me_mod5   10 -50.1 -19.9   35.0    -70.1  13.4  4     0.0094 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>This model is significantly better and shows a lower AIC. However makes more sense to use <code>spray_management</code> as a interactive term with AUDPC_m. As you would assume AUDPC would be dependant on the <code>spray_management</code>.</p>
<p>It is also worth noting there is no reason to include these parameters individually in the model to assess their independent effect on grain yield as we know the application of fungicide to mitigate yield loss is aimed at reducing the disease in the crop.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="aupdc-meta-analysis.html#cb50-1"></a>Me_mod6 &lt;-</span>
<span id="cb50-2"><a href="aupdc-meta-analysis.html#cb50-2"></a><span class="st">   </span><span class="kw">lmer</span>(grain_yield.t.ha <span class="op">~</span><span class="st"> </span>AUDPC_m<span class="op">:</span>spray_management <span class="op">+</span><span class="st"> </span>(AUDPC_m <span class="op">|</span><span class="st"> </span>trial),</span>
<span id="cb50-3"><a href="aupdc-meta-analysis.html#cb50-3"></a>        <span class="dt">data =</span> PM_Mdat)</span></code></pre></div>
<pre><code>## boundary (singular) fit: see ?isSingular</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="aupdc-meta-analysis.html#cb52-1"></a><span class="kw">anova</span>(Me_mod5, Me_mod6)</span></code></pre></div>
<pre><code>## refitting model(s) with ML (instead of REML)</code></pre>
<pre><code>## Data: PM_Mdat
## Models:
## Me_mod5: grain_yield.t.ha ~ AUDPC_m + spray_management + (AUDPC_m | trial)
## Me_mod6: grain_yield.t.ha ~ AUDPC_m:spray_management + (AUDPC_m | trial)
##         npar   AIC   BIC logLik deviance Chisq Df          Pr(&gt;Chisq)    
## Me_mod5   10 -50.1 -19.9   35.0    -70.1                                 
## Me_mod6   10 -58.7 -28.5   39.3    -78.7  8.64  0 &lt;0.0000000000000002 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>I will try to use the AUDPC:spray_management iterative term as a random effect slope to trial, however I think this may over fit the model preventing convergence.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="aupdc-meta-analysis.html#cb55-1"></a>Me_mod8 &lt;-</span>
<span id="cb55-2"><a href="aupdc-meta-analysis.html#cb55-2"></a><span class="st">   </span><span class="kw">lmer</span>(</span>
<span id="cb55-3"><a href="aupdc-meta-analysis.html#cb55-3"></a>      grain_yield.t.ha <span class="op">~</span><span class="st"> </span>AUDPC_m<span class="op">:</span>spray_management <span class="op">+</span><span class="st"> </span>(AUDPC_m<span class="op">:</span>spray_management <span class="op">|</span></span>
<span id="cb55-4"><a href="aupdc-meta-analysis.html#cb55-4"></a><span class="st">                                                        </span>trial),</span>
<span id="cb55-5"><a href="aupdc-meta-analysis.html#cb55-5"></a>      <span class="dt">data =</span> PM_Mdat</span>
<span id="cb55-6"><a href="aupdc-meta-analysis.html#cb55-6"></a>   )</span></code></pre></div>
<pre><code>## boundary (singular) fit: see ?isSingular</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="aupdc-meta-analysis.html#cb57-1"></a><span class="kw">anova</span>(Me_mod6, Me_mod8)</span></code></pre></div>
<pre><code>## refitting model(s) with ML (instead of REML)</code></pre>
<pre><code>## Warning in optwrap(optimizer, devfun, x@theta, lower = x@lower, calc.derivs =
## TRUE, : convergence code 1 from bobyqa: bobyqa -- maximum number of function
## evaluations exceeded</code></pre>
<pre><code>## Data: PM_Mdat
## Models:
## Me_mod6: grain_yield.t.ha ~ AUDPC_m:spray_management + (AUDPC_m | trial)
## Me_mod8: grain_yield.t.ha ~ AUDPC_m:spray_management + (AUDPC_m:spray_management | 
## Me_mod8:     trial)
##         npar   AIC   BIC logLik deviance Chisq Df Pr(&gt;Chisq)
## Me_mod6   10 -58.7 -28.5   39.3    -78.7                    
## Me_mod8   28 206.9 291.4  -75.5    150.9     0 18          1</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="aupdc-meta-analysis.html#cb61-1"></a>Me_mod9 &lt;-</span>
<span id="cb61-2"><a href="aupdc-meta-analysis.html#cb61-2"></a><span class="st">   </span><span class="kw">lmer</span>(grain_yield.t.ha <span class="op">~</span><span class="st"> </span>AUDPC_m<span class="op">:</span>spray_management <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>trial),</span>
<span id="cb61-3"><a href="aupdc-meta-analysis.html#cb61-3"></a>        <span class="dt">data =</span> PM_Mdat)</span>
<span id="cb61-4"><a href="aupdc-meta-analysis.html#cb61-4"></a></span>
<span id="cb61-5"><a href="aupdc-meta-analysis.html#cb61-5"></a><span class="kw">anova</span>(Me_mod6, Me_mod8)</span></code></pre></div>
<pre><code>## refitting model(s) with ML (instead of REML)</code></pre>
<pre><code>## Warning in optwrap(optimizer, devfun, x@theta, lower = x@lower, calc.derivs =
## TRUE, : convergence code 1 from bobyqa: bobyqa -- maximum number of function
## evaluations exceeded</code></pre>
<pre><code>## Data: PM_Mdat
## Models:
## Me_mod6: grain_yield.t.ha ~ AUDPC_m:spray_management + (AUDPC_m | trial)
## Me_mod8: grain_yield.t.ha ~ AUDPC_m:spray_management + (AUDPC_m:spray_management | 
## Me_mod8:     trial)
##         npar   AIC   BIC logLik deviance Chisq Df Pr(&gt;Chisq)
## Me_mod6   10 -58.7 -28.5   39.3    -78.7                    
## Me_mod8   28 206.9 291.4  -75.5    150.9     0 18          1</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="aupdc-meta-analysis.html#cb65-1"></a><span class="kw">anova</span>(Me_mod6, Me_mod9)</span></code></pre></div>
<pre><code>## refitting model(s) with ML (instead of REML)</code></pre>
<pre><code>## Data: PM_Mdat
## Models:
## Me_mod9: grain_yield.t.ha ~ AUDPC_m:spray_management + (1 | trial)
## Me_mod6: grain_yield.t.ha ~ AUDPC_m:spray_management + (AUDPC_m | trial)
##         npar   AIC   BIC logLik deviance Chisq Df Pr(&gt;Chisq)    
## Me_mod9    8 -35.1 -11.0   25.6    -51.1                        
## Me_mod6   10 -58.7 -28.5   39.3    -78.7  27.6  2   0.000001 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>As expected the model produced an error warning stating the maximum number of evaluations were exceeded. Also the model comparisons show that the newer Me_mod7 was not a better model. We we proceed with Me_mod6 as the model with the best fit.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="aupdc-meta-analysis.html#cb68-1"></a><span class="kw">summary</span>(Me_mod6)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML [&#39;lmerMod&#39;]
## Formula: grain_yield.t.ha ~ AUDPC_m:spray_management + (AUDPC_m | trial)
##    Data: PM_Mdat
## 
## REML criterion at convergence: -2.7
## 
## Scaled residuals: 
##    Min     1Q Median     3Q    Max 
## -4.046 -0.516  0.041  0.580  2.530 
## 
## Random effects:
##  Groups   Name        Variance   Std.Dev. Corr 
##  trial    (Intercept) 0.57493890 0.75825       
##           AUDPC_m     0.00000263 0.00162  -1.00
##  Residual             0.01675633 0.12945       
## Number of obs: 151, groups:  trial, 25
## 
## Fixed effects:
##                                           Estimate Std. Error t value
## (Intercept)                               1.289860   0.157852    8.17
## AUDPC_m:spray_managementcontrol          -0.001480   0.000433   -3.42
## AUDPC_m:spray_managementEarly            -0.001397   0.000525   -2.66
## AUDPC_m:spray_managementLate_plus        -0.000527   0.000628   -0.84
## AUDPC_m:spray_managementRecommended      -0.001193   0.000518   -2.30
## AUDPC_m:spray_managementRecommended_plus -0.000408   0.000569   -0.72
## 
## Correlation of Fixed Effects:
##             (Intr) AUDPC_m:_ AUDPC_:_E AUDPC_:_L AUDPC_m:_R
## AUDPC_m:sp_ -0.888                                         
## AUDPC_m:s_E -0.773  0.874                                  
## AUDPC_m:_L_ -0.680  0.792     0.703                        
## AUDPC_m:s_R -0.789  0.892     0.862     0.723              
## AUDPC_m:_R_ -0.752  0.892     0.882     0.727     0.897    
## convergence code: 0
## boundary (singular) fit: see ?isSingular</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="aupdc-meta-analysis.html#cb70-1"></a><span class="kw">coef</span>(Me_mod6)[[<span class="st">&quot;trial&quot;</span>]][<span class="kw">order</span>(<span class="kw">coef</span>(Me_mod6)[[<span class="st">&quot;trial&quot;</span>]]<span class="op">$</span>AUDPC_m),]</span></code></pre></div>
<pre><code>##                                                AUDPC_m (Intercept)
## mung1617/02_2017_Missen Flats_Jade_0.25    -0.00359691      2.9724
## mung1617/02_2017_Missen Flats_Jade_0.5     -0.00269276      2.5495
## mung1516/01_2016_Hermitage_Jade_0.75       -0.00245884      2.4400
## mung1415/01_2015_Hermitage_Jade_0.75       -0.00215994      2.3002
## mung1617/02_2017_Missen Flats_Jade_1       -0.00172370      2.0962
## mung1718/01_2018_Wellcamp_Jade_0.25        -0.00110878      1.8085
## mung1011/01_2011_Hermitage_Berken_0.75     -0.00102342      1.7686
## mung1718/01_2018_Wellcamp_Jade_0.5         -0.00098769      1.7519
## mung1011/01_2011_Hermitage_Crystal_0.75    -0.00048512      1.5168
## AM1303_2013_Premer_Crystal_NA              -0.00024743      1.4056
## mung1718/01_2018_Wellcamp_Jade_1            0.00001529      1.2827
## AM1304_2013_Marys Mount_Crystal_1           0.00012058      1.2335
## mung1112/02_2012_Kingaroy_Crystal_0.75      0.00016388      1.2132
## mung1011/02_2011_Kingaroy_Berken_0.75       0.00054003      1.0372
## mung1516/02_2016_Kingaroy_Jade_0.75         0.00074864      0.9397
## mung1112/01_2012_Gatton_Crystal_0.75        0.00082326      0.9048
## mung1516/03_2016_Emerald_Jade_0.75          0.00096984      0.8362
## mung1011/02_2011_Kingaroy_Crystal_0.75      0.00100242      0.8210
## BB1305_2013_Millmerran_Crystal_0.333333333  0.00107917      0.7851
## AM1305_2013_Goolhi_Crystal_0.33             0.00132410      0.6705
## mung1819/01_2019_Hermitage_Jade_0.25        0.00156796      0.5564
## mung1617/01_2017_Hermitage_Jade_0.5         0.00186749      0.4163
## mung1617/01_2017_Hermitage_Jade_1           0.00200146      0.3536
## mung1617/01_2017_Hermitage_Jade_0.25        0.00202611      0.3421
## mung1819/02_2019_Hermitage_Jade_0.25        0.00223437      0.2447
##                                            AUDPC_m:spray_managementcontrol
## mung1617/02_2017_Missen Flats_Jade_0.25                           -0.00148
## mung1617/02_2017_Missen Flats_Jade_0.5                            -0.00148
## mung1516/01_2016_Hermitage_Jade_0.75                              -0.00148
## mung1415/01_2015_Hermitage_Jade_0.75                              -0.00148
## mung1617/02_2017_Missen Flats_Jade_1                              -0.00148
## mung1718/01_2018_Wellcamp_Jade_0.25                               -0.00148
## mung1011/01_2011_Hermitage_Berken_0.75                            -0.00148
## mung1718/01_2018_Wellcamp_Jade_0.5                                -0.00148
## mung1011/01_2011_Hermitage_Crystal_0.75                           -0.00148
## AM1303_2013_Premer_Crystal_NA                                     -0.00148
## mung1718/01_2018_Wellcamp_Jade_1                                  -0.00148
## AM1304_2013_Marys Mount_Crystal_1                                 -0.00148
## mung1112/02_2012_Kingaroy_Crystal_0.75                            -0.00148
## mung1011/02_2011_Kingaroy_Berken_0.75                             -0.00148
## mung1516/02_2016_Kingaroy_Jade_0.75                               -0.00148
## mung1112/01_2012_Gatton_Crystal_0.75                              -0.00148
## mung1516/03_2016_Emerald_Jade_0.75                                -0.00148
## mung1011/02_2011_Kingaroy_Crystal_0.75                            -0.00148
## BB1305_2013_Millmerran_Crystal_0.333333333                        -0.00148
## AM1305_2013_Goolhi_Crystal_0.33                                   -0.00148
## mung1819/01_2019_Hermitage_Jade_0.25                              -0.00148
## mung1617/01_2017_Hermitage_Jade_0.5                               -0.00148
## mung1617/01_2017_Hermitage_Jade_1                                 -0.00148
## mung1617/01_2017_Hermitage_Jade_0.25                              -0.00148
## mung1819/02_2019_Hermitage_Jade_0.25                              -0.00148
##                                            AUDPC_m:spray_managementEarly
## mung1617/02_2017_Missen Flats_Jade_0.25                        -0.001397
## mung1617/02_2017_Missen Flats_Jade_0.5                         -0.001397
## mung1516/01_2016_Hermitage_Jade_0.75                           -0.001397
## mung1415/01_2015_Hermitage_Jade_0.75                           -0.001397
## mung1617/02_2017_Missen Flats_Jade_1                           -0.001397
## mung1718/01_2018_Wellcamp_Jade_0.25                            -0.001397
## mung1011/01_2011_Hermitage_Berken_0.75                         -0.001397
## mung1718/01_2018_Wellcamp_Jade_0.5                             -0.001397
## mung1011/01_2011_Hermitage_Crystal_0.75                        -0.001397
## AM1303_2013_Premer_Crystal_NA                                  -0.001397
## mung1718/01_2018_Wellcamp_Jade_1                               -0.001397
## AM1304_2013_Marys Mount_Crystal_1                              -0.001397
## mung1112/02_2012_Kingaroy_Crystal_0.75                         -0.001397
## mung1011/02_2011_Kingaroy_Berken_0.75                          -0.001397
## mung1516/02_2016_Kingaroy_Jade_0.75                            -0.001397
## mung1112/01_2012_Gatton_Crystal_0.75                           -0.001397
## mung1516/03_2016_Emerald_Jade_0.75                             -0.001397
## mung1011/02_2011_Kingaroy_Crystal_0.75                         -0.001397
## BB1305_2013_Millmerran_Crystal_0.333333333                     -0.001397
## AM1305_2013_Goolhi_Crystal_0.33                                -0.001397
## mung1819/01_2019_Hermitage_Jade_0.25                           -0.001397
## mung1617/01_2017_Hermitage_Jade_0.5                            -0.001397
## mung1617/01_2017_Hermitage_Jade_1                              -0.001397
## mung1617/01_2017_Hermitage_Jade_0.25                           -0.001397
## mung1819/02_2019_Hermitage_Jade_0.25                           -0.001397
##                                            AUDPC_m:spray_managementLate_plus
## mung1617/02_2017_Missen Flats_Jade_0.25                            -0.000527
## mung1617/02_2017_Missen Flats_Jade_0.5                             -0.000527
## mung1516/01_2016_Hermitage_Jade_0.75                               -0.000527
## mung1415/01_2015_Hermitage_Jade_0.75                               -0.000527
## mung1617/02_2017_Missen Flats_Jade_1                               -0.000527
## mung1718/01_2018_Wellcamp_Jade_0.25                                -0.000527
## mung1011/01_2011_Hermitage_Berken_0.75                             -0.000527
## mung1718/01_2018_Wellcamp_Jade_0.5                                 -0.000527
## mung1011/01_2011_Hermitage_Crystal_0.75                            -0.000527
## AM1303_2013_Premer_Crystal_NA                                      -0.000527
## mung1718/01_2018_Wellcamp_Jade_1                                   -0.000527
## AM1304_2013_Marys Mount_Crystal_1                                  -0.000527
## mung1112/02_2012_Kingaroy_Crystal_0.75                             -0.000527
## mung1011/02_2011_Kingaroy_Berken_0.75                              -0.000527
## mung1516/02_2016_Kingaroy_Jade_0.75                                -0.000527
## mung1112/01_2012_Gatton_Crystal_0.75                               -0.000527
## mung1516/03_2016_Emerald_Jade_0.75                                 -0.000527
## mung1011/02_2011_Kingaroy_Crystal_0.75                             -0.000527
## BB1305_2013_Millmerran_Crystal_0.333333333                         -0.000527
## AM1305_2013_Goolhi_Crystal_0.33                                    -0.000527
## mung1819/01_2019_Hermitage_Jade_0.25                               -0.000527
## mung1617/01_2017_Hermitage_Jade_0.5                                -0.000527
## mung1617/01_2017_Hermitage_Jade_1                                  -0.000527
## mung1617/01_2017_Hermitage_Jade_0.25                               -0.000527
## mung1819/02_2019_Hermitage_Jade_0.25                               -0.000527
##                                            AUDPC_m:spray_managementRecommended
## mung1617/02_2017_Missen Flats_Jade_0.25                              -0.001193
## mung1617/02_2017_Missen Flats_Jade_0.5                               -0.001193
## mung1516/01_2016_Hermitage_Jade_0.75                                 -0.001193
## mung1415/01_2015_Hermitage_Jade_0.75                                 -0.001193
## mung1617/02_2017_Missen Flats_Jade_1                                 -0.001193
## mung1718/01_2018_Wellcamp_Jade_0.25                                  -0.001193
## mung1011/01_2011_Hermitage_Berken_0.75                               -0.001193
## mung1718/01_2018_Wellcamp_Jade_0.5                                   -0.001193
## mung1011/01_2011_Hermitage_Crystal_0.75                              -0.001193
## AM1303_2013_Premer_Crystal_NA                                        -0.001193
## mung1718/01_2018_Wellcamp_Jade_1                                     -0.001193
## AM1304_2013_Marys Mount_Crystal_1                                    -0.001193
## mung1112/02_2012_Kingaroy_Crystal_0.75                               -0.001193
## mung1011/02_2011_Kingaroy_Berken_0.75                                -0.001193
## mung1516/02_2016_Kingaroy_Jade_0.75                                  -0.001193
## mung1112/01_2012_Gatton_Crystal_0.75                                 -0.001193
## mung1516/03_2016_Emerald_Jade_0.75                                   -0.001193
## mung1011/02_2011_Kingaroy_Crystal_0.75                               -0.001193
## BB1305_2013_Millmerran_Crystal_0.333333333                           -0.001193
## AM1305_2013_Goolhi_Crystal_0.33                                      -0.001193
## mung1819/01_2019_Hermitage_Jade_0.25                                 -0.001193
## mung1617/01_2017_Hermitage_Jade_0.5                                  -0.001193
## mung1617/01_2017_Hermitage_Jade_1                                    -0.001193
## mung1617/01_2017_Hermitage_Jade_0.25                                 -0.001193
## mung1819/02_2019_Hermitage_Jade_0.25                                 -0.001193
##                                            AUDPC_m:spray_managementRecommended_plus
## mung1617/02_2017_Missen Flats_Jade_0.25                                  -0.0004081
## mung1617/02_2017_Missen Flats_Jade_0.5                                   -0.0004081
## mung1516/01_2016_Hermitage_Jade_0.75                                     -0.0004081
## mung1415/01_2015_Hermitage_Jade_0.75                                     -0.0004081
## mung1617/02_2017_Missen Flats_Jade_1                                     -0.0004081
## mung1718/01_2018_Wellcamp_Jade_0.25                                      -0.0004081
## mung1011/01_2011_Hermitage_Berken_0.75                                   -0.0004081
## mung1718/01_2018_Wellcamp_Jade_0.5                                       -0.0004081
## mung1011/01_2011_Hermitage_Crystal_0.75                                  -0.0004081
## AM1303_2013_Premer_Crystal_NA                                            -0.0004081
## mung1718/01_2018_Wellcamp_Jade_1                                         -0.0004081
## AM1304_2013_Marys Mount_Crystal_1                                        -0.0004081
## mung1112/02_2012_Kingaroy_Crystal_0.75                                   -0.0004081
## mung1011/02_2011_Kingaroy_Berken_0.75                                    -0.0004081
## mung1516/02_2016_Kingaroy_Jade_0.75                                      -0.0004081
## mung1112/01_2012_Gatton_Crystal_0.75                                     -0.0004081
## mung1516/03_2016_Emerald_Jade_0.75                                       -0.0004081
## mung1011/02_2011_Kingaroy_Crystal_0.75                                   -0.0004081
## BB1305_2013_Millmerran_Crystal_0.333333333                               -0.0004081
## AM1305_2013_Goolhi_Crystal_0.33                                          -0.0004081
## mung1819/01_2019_Hermitage_Jade_0.25                                     -0.0004081
## mung1617/01_2017_Hermitage_Jade_0.5                                      -0.0004081
## mung1617/01_2017_Hermitage_Jade_1                                        -0.0004081
## mung1617/01_2017_Hermitage_Jade_0.25                                     -0.0004081
## mung1819/02_2019_Hermitage_Jade_0.25                                     -0.0004081</code></pre>
<p>The first output shows our random effects do a good job of explaining the variation leaving less residual variation than what is explained by the random intercept, trial.
In the fixed effects the intercept gives an estimate of the average yield across all treatments (1.29 t/Ha). The other fixed effects show the change in predicted yield as AUDPC increases under each of the spray_management factors. Spray_management treatments, control, early, and recommended show significant declines in grain_yields as AUDPC increases. Recommended_plus and Late_plus show no significant decline in grain yield as AUDPC increases.</p>
<p>The second output is the random effect coefficients. Here the intercept represents a yield estimate for each trial without the limitation of the disease. AUDPC_m shows the slope of the regression for grain yield as AUDPC increases. The coefficients of the model (ordered by AUDPC) show that higher yielding trials had a steeper negative slope. In other words higher yielding mungbean crops were likely to see greater losses from disease.</p>
</div>
<div id="aupdc-impact-on-grain-yield-meta-analysis" class="section level2" number="6.1">
<h2><span class="header-section-number">6.1</span> AUPDC impact on grain yield meta-analysis</h2>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="aupdc-meta-analysis.html#cb72-1"></a>PM_Mdat<span class="op">$</span>AUDPC_log &lt;-<span class="st"> </span><span class="kw">log</span>(PM_Mdat<span class="op">$</span>AUDPC_m)</span>
<span id="cb72-2"><a href="aupdc-meta-analysis.html#cb72-2"></a></span>
<span id="cb72-3"><a href="aupdc-meta-analysis.html#cb72-3"></a>PM_mv_AI &lt;-<span class="st"> </span><span class="kw">rma.mv</span>(</span>
<span id="cb72-4"><a href="aupdc-meta-analysis.html#cb72-4"></a>   yi,</span>
<span id="cb72-5"><a href="aupdc-meta-analysis.html#cb72-5"></a>   vi,</span>
<span id="cb72-6"><a href="aupdc-meta-analysis.html#cb72-6"></a>   <span class="dt">mods =</span> <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(AUDPC_m <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)<span class="op">:</span>spray_management,</span>
<span id="cb72-7"><a href="aupdc-meta-analysis.html#cb72-7"></a>   <span class="dt">method =</span> <span class="st">&quot;ML&quot;</span>,</span>
<span id="cb72-8"><a href="aupdc-meta-analysis.html#cb72-8"></a>   <span class="dt">random =</span> <span class="kw">list</span>( <span class="op">~</span><span class="st"> </span>spray_management <span class="op">|</span><span class="st"> </span>trial),</span>
<span id="cb72-9"><a href="aupdc-meta-analysis.html#cb72-9"></a>   <span class="dt">struct =</span> <span class="st">&quot;UN&quot;</span>,</span>
<span id="cb72-10"><a href="aupdc-meta-analysis.html#cb72-10"></a>   <span class="dt">data =</span> PM_Mdat</span>
<span id="cb72-11"><a href="aupdc-meta-analysis.html#cb72-11"></a>)</span></code></pre></div>
<pre><code>## Warning: Some combinations of the levels of the inner factor never occurred.
## Corresponding rho value(s) fixed to 0.</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="aupdc-meta-analysis.html#cb74-1"></a><span class="kw">summary</span>(PM_mv_AI)</span></code></pre></div>
<pre><code>## 
## Multivariate Meta-Analysis Model (k = 151; method: ML)
## 
##   logLik  Deviance       AIC       BIC      AICc 
##  45.8387  256.1988  -51.6773    8.6683  -45.2158   
## 
## Variance Components:
## 
## outer factor: trial            (nlvls = 25)
## inner factor: spray_management (nlvls = 5)
## 
##             estim    sqrt  k.lvl  fixed             level 
## tau^2.1    0.2378  0.4877     40     no           control 
## tau^2.2    0.2266  0.4761     13     no             Early 
## tau^2.3    0.2960  0.5440     20     no         Late_plus 
## tau^2.4    0.2567  0.5066     32     no       Recommended 
## tau^2.5    0.2754  0.5248     46     no  Recommended_plus 
## 
##                   rho.cntr  rho.Erly  rho.Lt_p  rho.Rcmm  rho.Rcm_    cntr 
## control                  1    0.9943    0.9909    0.9954    0.9919       - 
## Early               0.9943         1    0.0000    0.9971    0.9997       7 
## Late_plus           0.9909    0.0000         1    0.9912    0.9992       7 
## Recommended         0.9954    0.9971    0.9912         1    0.9950      21 
## Recommended_plus    0.9919    0.9997    0.9992    0.9950         1      19 
##                   Erly  Lt_p  Rcmm  Rcm_ 
## control             no    no    no    no 
## Early                -   yes    no    no 
## Late_plus            0     -    no    no 
## Recommended          6     4     -    no 
## Recommended_plus     6     4    19     - 
## 
## Test for Residual Heterogeneity:
## QE(df = 145) = 5624.3637, p-val &lt; .0001
## 
## Test of Moderators (coefficients 2:6):
## QM(df = 5) = 12.0731, p-val = 0.0338
## 
## Model Results:
## 
##                                                    estimate      se     zval 
## intrcpt                                             -0.0296  0.1259  -0.2352 
## log(AUDPC_m + 1):spray_managementcontrol             0.0031  0.0149   0.2077 
## log(AUDPC_m + 1):spray_managementEarly               0.0137  0.0200   0.6839 
## log(AUDPC_m + 1):spray_managementLate_plus           0.0206  0.0169   1.2165 
## log(AUDPC_m + 1):spray_managementRecommended         0.0179  0.0162   1.1068 
## log(AUDPC_m + 1):spray_managementRecommended_plus    0.0261  0.0180   1.4471 
##                                                      pval    ci.lb   ci.ub 
## intrcpt                                            0.8141  -0.2764  0.2172    
## log(AUDPC_m + 1):spray_managementcontrol           0.8354  -0.0262  0.0324    
## log(AUDPC_m + 1):spray_managementEarly             0.4941  -0.0256  0.0529    
## log(AUDPC_m + 1):spray_managementLate_plus         0.2238  -0.0126  0.0537    
## log(AUDPC_m + 1):spray_managementRecommended       0.2684  -0.0138  0.0497    
## log(AUDPC_m + 1):spray_managementRecommended_plus  0.1479  -0.0092  0.0614    
## 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="aupdc-meta-analysis.html#cb76-1"></a><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.1196</span>)</span></code></pre></div>
<pre><code>## [1] 0.8873</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="meta-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="manuscript-wire-frame.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
