<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Grain yield meta-analysis | A meta-analysis of powdery mildew yield loss mitigation strategies in Australian mungbean</title>
  <meta name="description" content="A meta-analysis of fungicide use in mungbean to control for yield loss due to powdery mildew." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Grain yield meta-analysis | A meta-analysis of powdery mildew yield loss mitigation strategies in Australian mungbean" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A meta-analysis of fungicide use in mungbean to control for yield loss due to powdery mildew." />
  <meta name="github-repo" content="OpenPlantPathology/Mungbean_PM" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Grain yield meta-analysis | A meta-analysis of powdery mildew yield loss mitigation strategies in Australian mungbean" />
  
  <meta name="twitter:description" content="A meta-analysis of fungicide use in mungbean to control for yield loss due to powdery mildew." />
  

<meta name="author" content="Paul Melloy, Emerson Del Ponte and Adam H. Sparks" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="prepare-data-for-meta-analysis.html"/>

<script src="libs/header-attrs-2.6/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Home</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#contents"><i class="fa fa-check"></i><b>1.1</b> Contents</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#other-research-questions-which-are-not-the-focus-of-this-study"><i class="fa fa-check"></i><b>1.2</b> Other research questions, which are not the focus of this study</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#possible-sources-of-variation-in-this-analysis."><i class="fa fa-check"></i><b>1.3</b> Possible sources of variation in this analysis.</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html"><i class="fa fa-check"></i><b>2</b> Trials considered for inclusion in meta-analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html#criteria-for-inclusion-in-meta-analysis"><i class="fa fa-check"></i><b>2.1</b> Criteria for inclusion in meta-analysis</a></li>
<li class="chapter" data-level="2.2" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html#import-data-and-apply-selection-criteria"><i class="fa fa-check"></i><b>2.2</b> Import data and apply selection criteria</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html#import-data-from-trials-we-have-the-raw-data"><i class="fa fa-check"></i><b>2.2.1</b> Import data from trials we have the raw data</a></li>
<li class="chapter" data-level="2.2.2" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html#import-dataset-of-manual-entries"><i class="fa fa-check"></i><b>2.2.2</b> Import dataset of manual entries</a></li>
<li class="chapter" data-level="2.2.3" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html#summary-of-all-trials"><i class="fa fa-check"></i><b>2.2.3</b> Summary of all trials</a></li>
<li class="chapter" data-level="2.2.4" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html#experiment-locations"><i class="fa fa-check"></i><b>2.2.4</b> Experiment locations</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html#subset-data-to-selection-criteria"><i class="fa fa-check"></i><b>2.3</b> Subset data to selection criteria</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html#classify-dataset-variables"><i class="fa fa-check"></i><b>2.3.1</b> Classify dataset variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html"><i class="fa fa-check"></i><b>3</b> Preliminary Analysis</a>
<ul>
<li class="chapter" data-level="3.1" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#explore-and-visualise-data"><i class="fa fa-check"></i><b>3.1</b> Explore and Visualise Data</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#descriptive-statistics"><i class="fa fa-check"></i><b>3.1.1</b> Descriptive statistics</a></li>
<li class="chapter" data-level="3.1.2" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#fungicides"><i class="fa fa-check"></i><b>3.1.2</b> Fungicides</a></li>
<li class="chapter" data-level="3.1.3" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#mungbean-cultivars"><i class="fa fa-check"></i><b>3.1.3</b> Mungbean cultivars</a></li>
<li class="chapter" data-level="3.1.4" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#row-spacing"><i class="fa fa-check"></i><b>3.1.4</b> Row spacing</a></li>
<li class="chapter" data-level="3.1.5" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#yield-loss-in-cultivar-jade"><i class="fa fa-check"></i><b>3.1.5</b> Yield loss in cultivar Jade</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#summary-of-disease-incidence-effect-on-yields"><i class="fa fa-check"></i><b>3.2</b> Summary of disease incidence effect on yields</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#fao-mungbean-data"><i class="fa fa-check"></i><b>3.2.1</b> FAO mungbean data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html"><i class="fa fa-check"></i><b>4</b> Prepare data for meta-analysis</a>
<ul>
<li class="chapter" data-level="4.1" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#set-environment-and-import-data"><i class="fa fa-check"></i><b>4.1</b> Set environment and import data</a></li>
<li class="chapter" data-level="4.2" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#subset-to-trials-containing-dmi-fungicides"><i class="fa fa-check"></i><b>4.2</b> Subset to trials containing DMI fungicides</a></li>
<li class="chapter" data-level="4.3" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#standardising-sample-variance"><i class="fa fa-check"></i><b>4.3</b> Standardising sample variance</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#converting-least-squares-to-sample-variance"><i class="fa fa-check"></i><b>4.3.1</b> Converting least-squares to sample variance</a></li>
<li class="chapter" data-level="4.3.2" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#converting-standard-deviation-to-sample-variance"><i class="fa fa-check"></i><b>4.3.2</b> Converting standard deviation to sample variance</a></li>
<li class="chapter" data-level="4.3.3" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#check-variance-of-data-set"><i class="fa fa-check"></i><b>4.3.3</b> Check variance of data-set</a></li>
<li class="chapter" data-level="4.3.4" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#inspect-variance-and-response-for-analysis"><i class="fa fa-check"></i><b>4.3.4</b> Inspect variance and response for analysis</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#classifying-fungicide-treatment"><i class="fa fa-check"></i><b>4.4</b> Classifying fungicide treatment</a></li>
<li class="chapter" data-level="4.5" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#trial-factor"><i class="fa fa-check"></i><b>4.5</b> Trial factor</a></li>
<li class="chapter" data-level="4.6" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#test-dose-effect"><i class="fa fa-check"></i><b>4.6</b> Test dose effect</a></li>
<li class="chapter" data-level="4.7" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#row-spacing-1"><i class="fa fa-check"></i><b>4.7</b> Row spacing</a></li>
<li class="chapter" data-level="4.8" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#remove-unnecessary-variables"><i class="fa fa-check"></i><b>4.8</b> Remove unnecessary variables</a></li>
<li class="chapter" data-level="4.9" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#final-data-check"><i class="fa fa-check"></i><b>4.9</b> Final data check</a>
<ul>
<li class="chapter" data-level="4.9.1" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#simplify-and-save-data"><i class="fa fa-check"></i><b>4.9.1</b> Simplify and save data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="grain-yield-meta-analysis.html"><a href="grain-yield-meta-analysis.html"><i class="fa fa-check"></i><b>5</b> Grain yield meta-analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="grain-yield-meta-analysis.html"><a href="grain-yield-meta-analysis.html#metafor-analysis"><i class="fa fa-check"></i><b>5.1</b> metafor analysis</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="grain-yield-meta-analysis.html"><a href="grain-yield-meta-analysis.html#profile-plots"><i class="fa fa-check"></i><b>5.1.1</b> Profile plots</a></li>
<li class="chapter" data-level="5.1.2" data-path="grain-yield-meta-analysis.html"><a href="grain-yield-meta-analysis.html#forest-plot-of-trial-treatment-effect-per-trial"><i class="fa fa-check"></i><b>5.1.2</b> Forest plot of trial treatment effect per trial</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="grain-yield-meta-analysis.html"><a href="grain-yield-meta-analysis.html#netmeta-analysis"><i class="fa fa-check"></i><b>5.2</b> netmeta analysis</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A meta-analysis of powdery mildew yield loss mitigation strategies in Australian mungbean</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="grain-yield-meta-analysis" class="section level1" number="5">
<h1><span class="header-section-number">5</span> Grain yield meta-analysis</h1>
<p>Let’s get started with the analysis by first finding the best model fit that answers our research question.</p>
<blockquote>
<p>When, in relation to PM establishes in the crop, should farmers begin spraying mungbean to mitigate yield loss: before PM establishing, immediately after first sign of PM establishing, or after PM has become established in the crop.</p>
</blockquote>
<p>A secondary question to this aim is: given the time at which the first spray occurred is a second spray provide worthwhile yield protection.</p>
<p>To do this, in our model:</p>
<ul>
<li><p>Grain yield is our response variable (t / ha)</p></li>
<li><p>Trial, which resolves combinations of categorical variables: year, location, row spacing, fungicide dose and cultivar; is set as a random intercept</p></li>
<li><p>We will investigate the effect size of our treatment - spray management,</p></li>
</ul>
<div id="metafor-analysis" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> metafor analysis</h2>
<p>For the first grain yield meta-analysis will be an ARM based model using the <code>metafor</code> package <span class="citation">(<a href="grain-yield-meta-analysis.html#ref-Viechtbauer2010" role="doc-biblioref">Viechtbauer 2010</a>)</span>.</p>
<p>We are using the <code>spray_management</code> variable as a moderator and an interactive term to the <code>trial</code> random variable.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="grain-yield-meta-analysis.html#cb1-1" aria-hidden="true" tabindex="-1"></a>PM_mv <span class="ot">&lt;-</span> <span class="fu">rma.mv</span>(</span>
<span id="cb1-2"><a href="grain-yield-meta-analysis.html#cb1-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">yi =</span> grain_yield.t.ha.,</span>
<span id="cb1-3"><a href="grain-yield-meta-analysis.html#cb1-3" aria-hidden="true" tabindex="-1"></a>   vi,</span>
<span id="cb1-4"><a href="grain-yield-meta-analysis.html#cb1-4" aria-hidden="true" tabindex="-1"></a>   <span class="at">mods =</span> <span class="sc">~</span> spray_management,</span>
<span id="cb1-5"><a href="grain-yield-meta-analysis.html#cb1-5" aria-hidden="true" tabindex="-1"></a>   <span class="at">method =</span> <span class="st">&quot;ML&quot;</span>,</span>
<span id="cb1-6"><a href="grain-yield-meta-analysis.html#cb1-6" aria-hidden="true" tabindex="-1"></a>   <span class="at">random =</span> <span class="fu">list</span>(<span class="sc">~</span> spray_management <span class="sc">|</span> trial, <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> id),</span>
<span id="cb1-7"><a href="grain-yield-meta-analysis.html#cb1-7" aria-hidden="true" tabindex="-1"></a>   <span class="at">struct =</span> <span class="st">&quot;UN&quot;</span>,</span>
<span id="cb1-8"><a href="grain-yield-meta-analysis.html#cb1-8" aria-hidden="true" tabindex="-1"></a>   <span class="at">control =</span> <span class="fu">list</span>(<span class="at">optimizer =</span> <span class="st">&quot;optim&quot;</span>),</span>
<span id="cb1-9"><a href="grain-yield-meta-analysis.html#cb1-9" aria-hidden="true" tabindex="-1"></a>   <span class="at">data =</span> PM_MB_dat</span>
<span id="cb1-10"><a href="grain-yield-meta-analysis.html#cb1-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Warning: Some combinations of the levels of the inner factor never occurred.
## Corresponding rho value(s) fixed to 0.</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="grain-yield-meta-analysis.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(PM_mv)</span></code></pre></div>
<pre><code>## 
## Multivariate Meta-Analysis Model (k = 154; method: ML)
## 
##   logLik  Deviance       AIC       BIC      AICc 
##  49.7175  233.2981  -45.4350   36.5628  -33.4350   
## 
## Variance Components:
## 
##             estim    sqrt  nlvls  fixed  factor 
## sigma^2    0.0000  0.0000    154     no      id 
## 
## outer factor: trial            (nlvls = 23)
## inner factor: spray_management (nlvls = 6)
## 
##             estim    sqrt  k.lvl  fixed             level 
## tau^2.1    0.2096  0.4579     38     no           control 
## tau^2.2    0.2205  0.4696     13     no             Early 
## tau^2.3    0.2887  0.5373     27     no       Recommended 
## tau^2.4    0.4017  0.6338     40     no  Recommended_plus 
## tau^2.5    0.3285  0.5731     17     no              Late 
## tau^2.6    0.4008  0.6331     19     no         Late_plus 
## 
##                   rho.cntr  rho.Erly  rho.Rcmm  rho.Rcm_  rho.Late  rho.Lt_p 
## control                  1    0.9706    0.9872    0.9735    0.9888    0.9843   
## Early               0.9706         1    0.9965    0.9960    0.9932    0.0000   
## Recommended         0.9872    0.9965         1    0.9954    0.9986    0.9986   
## Recommended_plus    0.9735    0.9960    0.9954         1    0.9967    0.9985   
## Late                0.9888    0.9932    0.9986    0.9967         1    0.9996   
## Late_plus           0.9843    0.0000    0.9986    0.9985    0.9996         1   
##                   cntr  Erly  Rcmm  Rcm_  Late  Lt_p 
## control              -    no    no    no    no    no 
## Early                7     -    no    no    no   yes 
## Recommended         19     6     -    no    no    no 
## Recommended_plus    17     6    17     -    no    no 
## Late                11     6    11    11     -    no 
## Late_plus            6     0     3     3     3     - 
## 
## Test for Residual Heterogeneity:
## QE(df = 148) = 10263.2645, p-val &lt; .0001
## 
## Test of Moderators (coefficients 2:6):
## QM(df = 5) = 37.7144, p-val &lt; .0001
## 
## Model Results:
## 
##                                   estimate      se     zval    pval    ci.lb 
## intrcpt                             1.0832  0.0975  11.1138  &lt;.0001   0.8921 
## spray_managementEarly               0.0153  0.0439   0.3479  0.7279  -0.0708 
## spray_managementRecommended         0.1461  0.0338   4.3279  &lt;.0001   0.0799 
## spray_managementRecommended_plus    0.1979  0.0549   3.6045  0.0003   0.0903 
## spray_managementLate                0.1432  0.0447   3.2006  0.0014   0.0555 
## spray_managementLate_plus           0.1387  0.0590   2.3483  0.0189   0.0229 
##                                    ci.ub 
## intrcpt                           1.2742  *** 
## spray_managementEarly             0.1013      
## spray_managementRecommended       0.2123  *** 
## spray_managementRecommended_plus  0.3055  *** 
## spray_managementLate              0.2309   ** 
## spray_managementLate_plus         0.2544    * 
## 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Let’s try the model with an implied simpler variance-covariance matrix “compound symmetry” (“CS”) to examine if unstructured matrix is suitable.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="grain-yield-meta-analysis.html#cb5-1" aria-hidden="true" tabindex="-1"></a>PM_mv_cs <span class="ot">&lt;-</span> <span class="fu">rma.mv</span>(</span>
<span id="cb5-2"><a href="grain-yield-meta-analysis.html#cb5-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">yi =</span> grain_yield.t.ha.,</span>
<span id="cb5-3"><a href="grain-yield-meta-analysis.html#cb5-3" aria-hidden="true" tabindex="-1"></a>   vi,</span>
<span id="cb5-4"><a href="grain-yield-meta-analysis.html#cb5-4" aria-hidden="true" tabindex="-1"></a>   <span class="at">mods =</span> <span class="sc">~</span> spray_management,</span>
<span id="cb5-5"><a href="grain-yield-meta-analysis.html#cb5-5" aria-hidden="true" tabindex="-1"></a>   <span class="at">method =</span> <span class="st">&quot;ML&quot;</span>,</span>
<span id="cb5-6"><a href="grain-yield-meta-analysis.html#cb5-6" aria-hidden="true" tabindex="-1"></a>   <span class="at">random =</span> <span class="fu">list</span>(<span class="sc">~</span> spray_management <span class="sc">|</span> trial, <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> id),</span>
<span id="cb5-7"><a href="grain-yield-meta-analysis.html#cb5-7" aria-hidden="true" tabindex="-1"></a>   <span class="at">struct =</span> <span class="st">&quot;CS&quot;</span>,</span>
<span id="cb5-8"><a href="grain-yield-meta-analysis.html#cb5-8" aria-hidden="true" tabindex="-1"></a>   <span class="at">control =</span> <span class="fu">list</span>(<span class="at">optimizer =</span> <span class="st">&quot;optim&quot;</span>),</span>
<span id="cb5-9"><a href="grain-yield-meta-analysis.html#cb5-9" aria-hidden="true" tabindex="-1"></a>   <span class="at">data =</span> PM_MB_dat</span>
<span id="cb5-10"><a href="grain-yield-meta-analysis.html#cb5-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-11"><a href="grain-yield-meta-analysis.html#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="grain-yield-meta-analysis.html#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(PM_mv, PM_mv_cs)</span></code></pre></div>
<pre><code>## 
##         df      AIC      BIC     AICc  logLik     LRT   pval         QE 
## Full    27 -45.4350  36.5628 -33.4350 49.7175                10263.2645 
## Reduced  9 -40.2381 -12.9055 -38.9881 29.1191 41.1968 0.0014 10263.2645</code></pre>
<p>The test shows that the ‘Full,’ more complicated model <code>PM_mv</code>, is a better fit and therefore we should keep the unstructured variance-covariance matrix.</p>
<p>The first table in the <code>PM_mv</code> output shows tau^2 (between trial variance) of each moderator random effects and the number of occurrences for each treatment in the analysis.
This effectively shows the heterogeneity between experiments for these particular treatments.</p>
<p>The tau^2 also gives us the heterogeneity between trials and indicates <code>Recommended_plus</code> showed the highest heterogeneity between experiments followed by <code>Late_plus</code>, <code>Late</code> then <code>Recommended</code>, with <code>Early</code> and the no-spray <code>control</code> showing the least heterogeneity.</p>
<p>The second table is in two parts (left and right).
The left part, rho, is the correlation of variation between the specified treatments.
All comparisons were acceptable except for a comparison between <code>Early</code> and <code>Late_plus</code>, <code>0.000</code> rho.
<code>Early</code> and <code>Late_plus</code> treatments never occurred within the same trial, which is indicated by the right side of the table (hence the warning).</p>
<p>In this result we can see that the <code>Early</code> treatment is not significantly different to the intercept, which in this case is the mean of the no spray <code>control</code>.
However the other treatments are significantly different from the no-spray control (intercept).
The <span class="math inline">\(Q_M\)</span> <a href="http://www.metafor-project.org/doku.php/tips:models_with_or_without_intercept?s%5B%5D=anova">omnibus test</a> of moderators, shows the moderators significantly influence the model (<span class="math inline">\(Q_M =\)</span> 37.7144 <span class="math inline">\(,df =\)</span> 5, P &lt; 0.0001) and we can reject the null hypothesis (<span class="math inline">\(H_0 : \beta_1 = \beta_2 = \beta_3 =\beta_4 = 0\)</span>) that there is no difference between the moderators <span class="citation">(<a href="grain-yield-meta-analysis.html#ref-Viechtbauer2010" role="doc-biblioref">Viechtbauer 2010</a>)</span>.
The analysis shows there is still a significant amount of residual heterogeneity (<span class="math inline">\(Q_E =\)</span> 10263.2645 <span class="math inline">\(,df=\)</span> 149, P &lt; 0.0001 ) not captured by the spray management moderator indicating other possible moderators which might influence grain yield.</p>
<p>Let’s present the meta-analysis results for the moderator variables in a forest style plot.
First Let’s create a table of the results.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="grain-yield-meta-analysis.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># obtain number of treatments included in each moderator variable</span></span>
<span id="cb7-2"><a href="grain-yield-meta-analysis.html#cb7-2" aria-hidden="true" tabindex="-1"></a>k5 <span class="ot">&lt;-</span></span>
<span id="cb7-3"><a href="grain-yield-meta-analysis.html#cb7-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">as.data.frame</span>(<span class="fu">table</span>(PM_MB_dat<span class="sc">$</span>trial, PM_MB_dat<span class="sc">$</span>spray_management)) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="grain-yield-meta-analysis.html#cb7-4" aria-hidden="true" tabindex="-1"></a>   <span class="fu">filter</span>(Freq <span class="sc">!=</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-5"><a href="grain-yield-meta-analysis.html#cb7-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">group_by</span>(Var2) <span class="sc">%&gt;%</span></span>
<span id="cb7-6"><a href="grain-yield-meta-analysis.html#cb7-6" aria-hidden="true" tabindex="-1"></a>   <span class="fu">summarise</span>(<span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb7-7"><a href="grain-yield-meta-analysis.html#cb7-7" aria-hidden="true" tabindex="-1"></a>   <span class="fu">pull</span>()</span>
<span id="cb7-8"><a href="grain-yield-meta-analysis.html#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="grain-yield-meta-analysis.html#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co"># create data.frame</span></span>
<span id="cb7-10"><a href="grain-yield-meta-analysis.html#cb7-10" aria-hidden="true" tabindex="-1"></a>results_mv <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb7-11"><a href="grain-yield-meta-analysis.html#cb7-11" aria-hidden="true" tabindex="-1"></a>   <span class="at">N =</span> PM_mv<span class="sc">$</span>g.levels.k,</span>
<span id="cb7-12"><a href="grain-yield-meta-analysis.html#cb7-12" aria-hidden="true" tabindex="-1"></a>   <span class="at">k =</span> k5,</span>
<span id="cb7-13"><a href="grain-yield-meta-analysis.html#cb7-13" aria-hidden="true" tabindex="-1"></a>   <span class="at">Effect =</span> <span class="fu">round</span>(PM_mv<span class="sc">$</span>b, <span class="dv">4</span>),</span>
<span id="cb7-14"><a href="grain-yield-meta-analysis.html#cb7-14" aria-hidden="true" tabindex="-1"></a>   <span class="at">se =</span> <span class="fu">round</span>(PM_mv<span class="sc">$</span>se, <span class="dv">4</span>),</span>
<span id="cb7-15"><a href="grain-yield-meta-analysis.html#cb7-15" aria-hidden="true" tabindex="-1"></a>   <span class="at">CI_lower =</span> <span class="fu">round</span>(PM_mv<span class="sc">$</span>ci.lb, <span class="dv">4</span>),</span>
<span id="cb7-16"><a href="grain-yield-meta-analysis.html#cb7-16" aria-hidden="true" tabindex="-1"></a>   <span class="at">CI_upper =</span> <span class="fu">round</span>(PM_mv<span class="sc">$</span>ci.ub, <span class="dv">4</span>),</span>
<span id="cb7-17"><a href="grain-yield-meta-analysis.html#cb7-17" aria-hidden="true" tabindex="-1"></a>   <span class="at">z_val =</span> <span class="fu">round</span>(PM_mv<span class="sc">$</span>zval, <span class="dv">4</span>),</span>
<span id="cb7-18"><a href="grain-yield-meta-analysis.html#cb7-18" aria-hidden="true" tabindex="-1"></a>   <span class="at">p_val =</span> <span class="fu">reportP</span>(PM_mv<span class="sc">$</span>pval, <span class="at">AsNumeric =</span> <span class="cn">TRUE</span>)</span>
<span id="cb7-19"><a href="grain-yield-meta-analysis.html#cb7-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-20"><a href="grain-yield-meta-analysis.html#cb7-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-21"><a href="grain-yield-meta-analysis.html#cb7-21" aria-hidden="true" tabindex="-1"></a><span class="co"># adjust estimates to show absolute means</span></span>
<span id="cb7-22"><a href="grain-yield-meta-analysis.html#cb7-22" aria-hidden="true" tabindex="-1"></a>results_mv <span class="ot">&lt;-</span></span>
<span id="cb7-23"><a href="grain-yield-meta-analysis.html#cb7-23" aria-hidden="true" tabindex="-1"></a>   results_mv[<span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>,] <span class="sc">%&gt;%</span></span>
<span id="cb7-24"><a href="grain-yield-meta-analysis.html#cb7-24" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(<span class="at">Effect =</span> Effect <span class="sc">+</span> results_mv<span class="sc">$</span>Effect[<span class="dv">1</span>]) <span class="sc">%&gt;%</span></span>
<span id="cb7-25"><a href="grain-yield-meta-analysis.html#cb7-25" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(<span class="at">CI_lower =</span> CI_lower <span class="sc">+</span> results_mv<span class="sc">$</span>CI_lower[<span class="dv">1</span>]) <span class="sc">%&gt;%</span></span>
<span id="cb7-26"><a href="grain-yield-meta-analysis.html#cb7-26" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(<span class="at">CI_upper =</span> CI_upper <span class="sc">+</span> results_mv<span class="sc">$</span>CI_upper[<span class="dv">1</span>]) <span class="sc">%&gt;%</span></span>
<span id="cb7-27"><a href="grain-yield-meta-analysis.html#cb7-27" aria-hidden="true" tabindex="-1"></a>   <span class="fu">bind_rows</span>(results_mv[<span class="dv">1</span>,]) <span class="sc">%&gt;%</span></span>
<span id="cb7-28"><a href="grain-yield-meta-analysis.html#cb7-28" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(<span class="at">index =</span> <span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb7-29"><a href="grain-yield-meta-analysis.html#cb7-29" aria-hidden="true" tabindex="-1"></a>   <span class="fu">arrange</span>(index)</span>
<span id="cb7-30"><a href="grain-yield-meta-analysis.html#cb7-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-31"><a href="grain-yield-meta-analysis.html#cb7-31" aria-hidden="true" tabindex="-1"></a><span class="co"># rename colnames to give table headings</span></span>
<span id="cb7-32"><a href="grain-yield-meta-analysis.html#cb7-32" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(results_mv)[<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="dv">6</span><span class="sc">:</span><span class="dv">9</span>)] <span class="ot">&lt;-</span></span>
<span id="cb7-33"><a href="grain-yield-meta-analysis.html#cb7-33" aria-hidden="true" tabindex="-1"></a>   <span class="fu">c</span>(<span class="st">&quot;Treatment&quot;</span>,</span>
<span id="cb7-34"><a href="grain-yield-meta-analysis.html#cb7-34" aria-hidden="true" tabindex="-1"></a>     <span class="st">&quot;$N$&quot;</span>,</span>
<span id="cb7-35"><a href="grain-yield-meta-analysis.html#cb7-35" aria-hidden="true" tabindex="-1"></a>     <span class="st">&quot;$k$&quot;</span>,</span>
<span id="cb7-36"><a href="grain-yield-meta-analysis.html#cb7-36" aria-hidden="true" tabindex="-1"></a>     <span class="st">&quot;$</span><span class="sc">\\</span><span class="st">mu$&quot;</span>,</span>
<span id="cb7-37"><a href="grain-yield-meta-analysis.html#cb7-37" aria-hidden="true" tabindex="-1"></a>     <span class="st">&quot;$CI_{L}$&quot;</span>,</span>
<span id="cb7-38"><a href="grain-yield-meta-analysis.html#cb7-38" aria-hidden="true" tabindex="-1"></a>     <span class="st">&quot;$CI_{U}$&quot;</span>,</span>
<span id="cb7-39"><a href="grain-yield-meta-analysis.html#cb7-39" aria-hidden="true" tabindex="-1"></a>     <span class="st">&quot;$Z$&quot;</span>,</span>
<span id="cb7-40"><a href="grain-yield-meta-analysis.html#cb7-40" aria-hidden="true" tabindex="-1"></a>     <span class="st">&quot;$P$&quot;</span>)</span>
<span id="cb7-41"><a href="grain-yield-meta-analysis.html#cb7-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-42"><a href="grain-yield-meta-analysis.html#cb7-42" aria-hidden="true" tabindex="-1"></a><span class="co"># provide rownames for each moderator variable</span></span>
<span id="cb7-43"><a href="grain-yield-meta-analysis.html#cb7-43" aria-hidden="true" tabindex="-1"></a><span class="fu">row.names</span>(results_mv) <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb7-44"><a href="grain-yield-meta-analysis.html#cb7-44" aria-hidden="true" tabindex="-1"></a>   <span class="st">&quot;Intercept / No Spray control&quot;</span>,</span>
<span id="cb7-45"><a href="grain-yield-meta-analysis.html#cb7-45" aria-hidden="true" tabindex="-1"></a>   <span class="st">&quot;$Early_{single}$&quot;</span>,</span>
<span id="cb7-46"><a href="grain-yield-meta-analysis.html#cb7-46" aria-hidden="true" tabindex="-1"></a>   <span class="st">&quot;$Recommended_{single}$&quot;</span>,</span>
<span id="cb7-47"><a href="grain-yield-meta-analysis.html#cb7-47" aria-hidden="true" tabindex="-1"></a>   <span class="st">&quot;$Recommended_{plus}$&quot;</span>,</span>
<span id="cb7-48"><a href="grain-yield-meta-analysis.html#cb7-48" aria-hidden="true" tabindex="-1"></a>   <span class="st">&quot;$Late_{single}$&quot;</span>,</span>
<span id="cb7-49"><a href="grain-yield-meta-analysis.html#cb7-49" aria-hidden="true" tabindex="-1"></a>   <span class="st">&quot;$Late_{plus}$&quot;</span></span>
<span id="cb7-50"><a href="grain-yield-meta-analysis.html#cb7-50" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-51"><a href="grain-yield-meta-analysis.html#cb7-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-52"><a href="grain-yield-meta-analysis.html#cb7-52" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(results_mv[, <span class="dv">2</span><span class="sc">:</span><span class="dv">9</span>],</span>
<span id="cb7-53"><a href="grain-yield-meta-analysis.html#cb7-53" aria-hidden="true" tabindex="-1"></a>      <span class="at">align =</span> <span class="st">&quot;lcccccccc&quot;</span>,</span>
<span id="cb7-54"><a href="grain-yield-meta-analysis.html#cb7-54" aria-hidden="true" tabindex="-1"></a>      <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb7-55"><a href="grain-yield-meta-analysis.html#cb7-55" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">&quot;Table ##: Estimated mean mungbean yields for each spray schedule treatment used for mitigating yield losses to powdery mildew in mungbean crops grown in eastern Australia. Yield estimates were calculated from the network meta-analysis of data obtained from grey literature reports. Z and P values indicate statistical significance in comparison to the intercept.&quot;</span>)</span></code></pre></div>
<table>
<caption>
(#tab:metafor_results)Table ##: Estimated mean mungbean yields for each spray schedule treatment used for mitigating yield losses to powdery mildew in mungbean crops grown in eastern Australia. Yield estimates were calculated from the network meta-analysis of data obtained from grey literature reports. Z and P values indicate statistical significance in comparison to the intercept.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
<span class="math inline">\(N\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(k\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(\mu\)</span>
</th>
<th style="text-align:center;">
se
</th>
<th style="text-align:center;">
<span class="math inline">\(CI_{L}\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(CI_{U}\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(Z\)</span>
</th>
<th style="text-align:center;">
<span class="math inline">\(P\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Intercept / No Spray control
</td>
<td style="text-align:left;">
38
</td>
<td style="text-align:center;">
23
</td>
<td style="text-align:center;">
1.083
</td>
<td style="text-align:center;">
0.0975
</td>
<td style="text-align:center;">
0.8921
</td>
<td style="text-align:center;">
1.274
</td>
<td style="text-align:center;">
11.1138
</td>
<td style="text-align:center;">
0.0001
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(Early_{single}\)</span>
</td>
<td style="text-align:left;">
13
</td>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
1.099
</td>
<td style="text-align:center;">
0.0439
</td>
<td style="text-align:center;">
0.8213
</td>
<td style="text-align:center;">
1.375
</td>
<td style="text-align:center;">
0.3479
</td>
<td style="text-align:center;">
0.7279
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(Recommended_{single}\)</span>
</td>
<td style="text-align:left;">
27
</td>
<td style="text-align:center;">
19
</td>
<td style="text-align:center;">
1.229
</td>
<td style="text-align:center;">
0.0338
</td>
<td style="text-align:center;">
0.9720
</td>
<td style="text-align:center;">
1.486
</td>
<td style="text-align:center;">
4.3279
</td>
<td style="text-align:center;">
0.0001
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(Recommended_{plus}\)</span>
</td>
<td style="text-align:left;">
40
</td>
<td style="text-align:center;">
17
</td>
<td style="text-align:center;">
1.281
</td>
<td style="text-align:center;">
0.0549
</td>
<td style="text-align:center;">
0.9824
</td>
<td style="text-align:center;">
1.580
</td>
<td style="text-align:center;">
3.6045
</td>
<td style="text-align:center;">
0.0003
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(Late_{single}\)</span>
</td>
<td style="text-align:left;">
17
</td>
<td style="text-align:center;">
11
</td>
<td style="text-align:center;">
1.226
</td>
<td style="text-align:center;">
0.0447
</td>
<td style="text-align:center;">
0.9476
</td>
<td style="text-align:center;">
1.505
</td>
<td style="text-align:center;">
3.2006
</td>
<td style="text-align:center;">
0.0014
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(Late_{plus}\)</span>
</td>
<td style="text-align:left;">
19
</td>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
1.222
</td>
<td style="text-align:center;">
0.0590
</td>
<td style="text-align:center;">
0.9150
</td>
<td style="text-align:center;">
1.529
</td>
<td style="text-align:center;">
2.3483
</td>
<td style="text-align:center;">
0.0189
</td>
</tr>
</tbody>
</table>
<p>Let’s view these comparisons in a plot.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="grain-yield-meta-analysis.html#cb8-1" aria-hidden="true" tabindex="-1"></a>results_mv <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="grain-yield-meta-analysis.html#cb8-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">filter</span>(Treatment <span class="sc">!=</span> <span class="st">&quot;control&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="grain-yield-meta-analysis.html#cb8-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">mutate</span>(<span class="at">Treatment =</span> <span class="fu">factor</span>(Treatment, <span class="at">levels =</span> <span class="fu">rev</span>(</span>
<span id="cb8-4"><a href="grain-yield-meta-analysis.html#cb8-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">c</span>(</span>
<span id="cb8-5"><a href="grain-yield-meta-analysis.html#cb8-5" aria-hidden="true" tabindex="-1"></a>         <span class="st">&quot;Early&quot;</span>,</span>
<span id="cb8-6"><a href="grain-yield-meta-analysis.html#cb8-6" aria-hidden="true" tabindex="-1"></a>         <span class="st">&quot;Recommended&quot;</span>,</span>
<span id="cb8-7"><a href="grain-yield-meta-analysis.html#cb8-7" aria-hidden="true" tabindex="-1"></a>         <span class="st">&quot;Recommended_plus&quot;</span>,</span>
<span id="cb8-8"><a href="grain-yield-meta-analysis.html#cb8-8" aria-hidden="true" tabindex="-1"></a>         <span class="st">&quot;Late&quot;</span>,</span>
<span id="cb8-9"><a href="grain-yield-meta-analysis.html#cb8-9" aria-hidden="true" tabindex="-1"></a>         <span class="st">&quot;Late_plus&quot;</span></span>
<span id="cb8-10"><a href="grain-yield-meta-analysis.html#cb8-10" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb8-11"><a href="grain-yield-meta-analysis.html#cb8-11" aria-hidden="true" tabindex="-1"></a>   ))) <span class="sc">%&gt;%</span></span>
<span id="cb8-12"><a href="grain-yield-meta-analysis.html#cb8-12" aria-hidden="true" tabindex="-1"></a>   <span class="fu">ggplot</span>(<span class="fu">aes</span>(Treatment, <span class="st">`</span><span class="at">$</span><span class="sc">\\</span><span class="at">mu$</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb8-13"><a href="grain-yield-meta-analysis.html#cb8-13" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_hline</span>(</span>
<span id="cb8-14"><a href="grain-yield-meta-analysis.html#cb8-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">yintercept =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.05</span>, <span class="fl">0.3</span>, <span class="at">by =</span> <span class="fl">0.05</span>),</span>
<span id="cb8-15"><a href="grain-yield-meta-analysis.html#cb8-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">color =</span> <span class="fu">usq_cols</span>(<span class="st">&quot;usq charcoal&quot;</span>),</span>
<span id="cb8-16"><a href="grain-yield-meta-analysis.html#cb8-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">linetype =</span> <span class="dv">3</span></span>
<span id="cb8-17"><a href="grain-yield-meta-analysis.html#cb8-17" aria-hidden="true" tabindex="-1"></a>   ) <span class="sc">+</span></span>
<span id="cb8-18"><a href="grain-yield-meta-analysis.html#cb8-18" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb8-19"><a href="grain-yield-meta-analysis.html#cb8-19" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">size =</span> <span class="dv">1</span> <span class="sc">/</span> se), <span class="at">shape =</span> <span class="dv">15</span>) <span class="sc">+</span></span>
<span id="cb8-20"><a href="grain-yield-meta-analysis.html#cb8-20" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_linerange</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> <span class="st">`</span><span class="at">$CI_{L}$</span><span class="st">`</span>, <span class="at">ymax =</span> <span class="st">`</span><span class="at">$CI_{U}$</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb8-21"><a href="grain-yield-meta-analysis.html#cb8-21" aria-hidden="true" tabindex="-1"></a>   <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb8-22"><a href="grain-yield-meta-analysis.html#cb8-22" aria-hidden="true" tabindex="-1"></a>   <span class="co">#ggtitle(&quot;Mean spray schedule effect sizes\nand 95% confidence intervals&quot;)+</span></span>
<span id="cb8-23"><a href="grain-yield-meta-analysis.html#cb8-23" aria-hidden="true" tabindex="-1"></a>   <span class="fu">ylab</span>(<span class="fu">expression</span>(<span class="fu">paste</span>(</span>
<span id="cb8-24"><a href="grain-yield-meta-analysis.html#cb8-24" aria-hidden="true" tabindex="-1"></a>      <span class="st">&quot;Mean yield difference to control (t ha&quot;</span> <span class="sc">^</span> <span class="sc">-</span><span class="dv">1</span>, <span class="st">&quot;)&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb8-25"><a href="grain-yield-meta-analysis.html#cb8-25" aria-hidden="true" tabindex="-1"></a>   ))) <span class="sc">+</span></span>
<span id="cb8-26"><a href="grain-yield-meta-analysis.html#cb8-26" aria-hidden="true" tabindex="-1"></a>   <span class="fu">scale_x_discrete</span>(</span>
<span id="cb8-27"><a href="grain-yield-meta-analysis.html#cb8-27" aria-hidden="true" tabindex="-1"></a>      <span class="st">&quot;Moderator variable&quot;</span>,</span>
<span id="cb8-28"><a href="grain-yield-meta-analysis.html#cb8-28" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(</span>
<span id="cb8-29"><a href="grain-yield-meta-analysis.html#cb8-29" aria-hidden="true" tabindex="-1"></a>         <span class="fu">expression</span>(<span class="st">&quot;Late&quot;</span>[<span class="st">&quot;plus&quot;</span>]),</span>
<span id="cb8-30"><a href="grain-yield-meta-analysis.html#cb8-30" aria-hidden="true" tabindex="-1"></a>         <span class="fu">expression</span>(<span class="st">&quot;Late&quot;</span>[<span class="st">&quot;single&quot;</span>]),</span>
<span id="cb8-31"><a href="grain-yield-meta-analysis.html#cb8-31" aria-hidden="true" tabindex="-1"></a>         <span class="fu">expression</span>(<span class="st">&quot;Recommended&quot;</span>[<span class="st">&quot;plus&quot;</span>]),</span>
<span id="cb8-32"><a href="grain-yield-meta-analysis.html#cb8-32" aria-hidden="true" tabindex="-1"></a>         <span class="fu">expression</span>(<span class="st">&quot;Recommended&quot;</span>[<span class="st">&quot;single&quot;</span>]),</span>
<span id="cb8-33"><a href="grain-yield-meta-analysis.html#cb8-33" aria-hidden="true" tabindex="-1"></a>         <span class="fu">expression</span>(<span class="st">&quot;Early&quot;</span>[<span class="st">&quot;single&quot;</span>])</span>
<span id="cb8-34"><a href="grain-yield-meta-analysis.html#cb8-34" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb8-35"><a href="grain-yield-meta-analysis.html#cb8-35" aria-hidden="true" tabindex="-1"></a>   )</span></code></pre></div>
<p><img src="_main_files/figure-html/metafor_plot-1.png" width="672" /></p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="grain-yield-meta-analysis.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">&quot;paper/figures/Fig2_means_difference.png&quot;</span>,</span>
<span id="cb9-2"><a href="grain-yield-meta-analysis.html#cb9-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">height =</span> <span class="dv">3</span>,</span>
<span id="cb9-3"><a href="grain-yield-meta-analysis.html#cb9-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">dpi =</span> <span class="dv">500</span>)</span></code></pre></div>
<pre><code>## Saving 7 x 3 in image</code></pre>
<p>Let’s investigate the treatment contrasts</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="grain-yield-meta-analysis.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">&quot;R/simple_summary.R&quot;</span>) <span class="co">#function to provide a table that includes the treatment names in the contrasts</span></span>
<span id="cb11-2"><a href="grain-yield-meta-analysis.html#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">glht</span>(PM_mv, <span class="at">linfct =</span> <span class="fu">cbind</span>(<span class="fu">contrMat</span>(<span class="fu">rep</span>(</span>
<span id="cb11-3"><a href="grain-yield-meta-analysis.html#cb11-3" aria-hidden="true" tabindex="-1"></a>   <span class="dv">1</span>, <span class="dv">6</span></span>
<span id="cb11-4"><a href="grain-yield-meta-analysis.html#cb11-4" aria-hidden="true" tabindex="-1"></a>), <span class="at">type =</span> <span class="st">&quot;Tukey&quot;</span>))), <span class="at">test =</span> <span class="fu">adjusted</span>(<span class="st">&quot;none&quot;</span>))</span></code></pre></div>
<pre><code>## 
##   Simultaneous Tests for General Linear Hypotheses
## 
## Fit: rma.mv(yi = grain_yield.t.ha., V = vi, mods = ~spray_management, 
##     random = list(~spray_management | trial, ~1 | id), struct = &quot;UN&quot;, 
##     data = PM_MB_dat, method = &quot;ML&quot;, control = list(optimizer = &quot;optim&quot;))
## 
## Linear Hypotheses:
##            Estimate Std. Error z value             Pr(&gt;|z|)    
## 2 - 1 == 0 -1.06788    0.11122   -9.60 &lt; 0.0000000000000002 ***
## 3 - 1 == 0 -0.93704    0.09144  -10.25 &lt; 0.0000000000000002 ***
## 4 - 1 == 0 -0.88526    0.08297  -10.67 &lt; 0.0000000000000002 ***
## 5 - 1 == 0 -0.93995    0.08869  -10.60 &lt; 0.0000000000000002 ***
## 6 - 1 == 0 -0.94449    0.08454  -11.17 &lt; 0.0000000000000002 ***
## 3 - 2 == 0  0.13084    0.02960    4.42            0.0000098 ***
## 4 - 2 == 0  0.18263    0.04906    3.72               0.0002 ***
## 5 - 2 == 0  0.12793    0.04655    2.75               0.0060 ** 
## 6 - 2 == 0  0.12340    0.06187    1.99               0.0461 *  
## 4 - 3 == 0  0.05179    0.03460    1.50               0.1344    
## 5 - 3 == 0 -0.00291    0.03316   -0.09               0.9300    
## 6 - 3 == 0 -0.00744    0.04878   -0.15               0.8787    
## 5 - 4 == 0 -0.05470    0.03830   -1.43               0.1532    
## 6 - 4 == 0 -0.05923    0.04674   -1.27               0.2051    
## 6 - 5 == 0 -0.00453    0.04781   -0.09               0.9244    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## (Adjusted p values reported -- none method)</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="grain-yield-meta-analysis.html#cb13-1" aria-hidden="true" tabindex="-1"></a>contrast_Ssum <span class="ot">&lt;-</span></span>
<span id="cb13-2"><a href="grain-yield-meta-analysis.html#cb13-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">simple_summary</span>(<span class="fu">summary</span>(<span class="fu">glht</span>(PM_mv, <span class="at">linfct =</span> <span class="fu">cbind</span>(</span>
<span id="cb13-3"><a href="grain-yield-meta-analysis.html#cb13-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">contrMat</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">6</span>), <span class="at">type =</span> <span class="st">&quot;Tukey&quot;</span>)</span>
<span id="cb13-4"><a href="grain-yield-meta-analysis.html#cb13-4" aria-hidden="true" tabindex="-1"></a>   )), <span class="at">test =</span> <span class="fu">adjusted</span>(<span class="st">&quot;none&quot;</span>)))</span>
<span id="cb13-5"><a href="grain-yield-meta-analysis.html#cb13-5" aria-hidden="true" tabindex="-1"></a>contrast_Ssum</span></code></pre></div>
<pre><code>##                             contrast coefficients  StdErr    Zvalue       pvals
## 2 - 1                Early - control    -1.067884 0.11122  -9.60163 0.000000000
## 3 - 1          Recommended - control    -0.937043 0.09144 -10.24816 0.000000000
## 4 - 1     Recommended_plus - control    -0.885258 0.08297 -10.67019 0.000000000
## 5 - 1                 Late - control    -0.939954 0.08869 -10.59764 0.000000000
## 6 - 1            Late_plus - control    -0.944488 0.08454 -11.17167 0.000000000
## 3 - 2            Recommended - Early     0.130840 0.02960   4.42099 0.000009825
## 4 - 2       Recommended_plus - Early     0.182626 0.04906   3.72233 0.000197393
## 5 - 2                   Late - Early     0.127930 0.04655   2.74850 0.005986804
## 6 - 2              Late_plus - Early     0.123396 0.06187   1.99432 0.046117626
## 4 - 3 Recommended_plus - Recommended     0.051786 0.03460   1.49681 0.134441646
## 5 - 3             Late - Recommended    -0.002911 0.03316  -0.08779 0.930040204
## 6 - 3        Late_plus - Recommended    -0.007445 0.04878  -0.15262 0.878695438
## 5 - 4        Late - Recommended_plus    -0.054697 0.03830  -1.42820 0.153234339
## 6 - 4   Late_plus - Recommended_plus    -0.059230 0.04674  -1.26723 0.205074724
## 6 - 5               Late_plus - Late    -0.004534 0.04781  -0.09483 0.924449336
##       sig
## 2 - 1 ***
## 3 - 1 ***
## 4 - 1 ***
## 5 - 1 ***
## 6 - 1 ***
## 3 - 2 ***
## 4 - 2 ***
## 5 - 2  **
## 6 - 2   *
## 4 - 3    
## 5 - 3    
## 6 - 3    
## 5 - 4    
## 6 - 4    
## 6 - 5</code></pre>
<p>These contrasts can be viewed in a plot</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="grain-yield-meta-analysis.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">13</span>, <span class="dv">4</span>, <span class="dv">2</span>) <span class="sc">+</span> <span class="fl">0.1</span>)</span>
<span id="cb15-2"><a href="grain-yield-meta-analysis.html#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">glht</span>(PM_mv, <span class="at">linfct =</span> <span class="fu">cbind</span>(<span class="fu">contrMat</span>(<span class="fu">rep</span>(</span>
<span id="cb15-3"><a href="grain-yield-meta-analysis.html#cb15-3" aria-hidden="true" tabindex="-1"></a>   <span class="dv">1</span>, <span class="dv">6</span></span>
<span id="cb15-4"><a href="grain-yield-meta-analysis.html#cb15-4" aria-hidden="true" tabindex="-1"></a>), <span class="at">type =</span> <span class="st">&quot;Tukey&quot;</span>))), <span class="at">yaxt =</span> <span class="st">&#39;n&#39;</span>)</span>
<span id="cb15-5"><a href="grain-yield-meta-analysis.html#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(</span>
<span id="cb15-6"><a href="grain-yield-meta-analysis.html#cb15-6" aria-hidden="true" tabindex="-1"></a>   <span class="dv">2</span>,</span>
<span id="cb15-7"><a href="grain-yield-meta-analysis.html#cb15-7" aria-hidden="true" tabindex="-1"></a>   <span class="at">at =</span> <span class="fu">seq_along</span>(contrast_Ssum<span class="sc">$</span>contrast),</span>
<span id="cb15-8"><a href="grain-yield-meta-analysis.html#cb15-8" aria-hidden="true" tabindex="-1"></a>   <span class="at">labels =</span> <span class="fu">rev</span>(contrast_Ssum<span class="sc">$</span>contrast),</span>
<span id="cb15-9"><a href="grain-yield-meta-analysis.html#cb15-9" aria-hidden="true" tabindex="-1"></a>   <span class="at">las =</span> <span class="dv">2</span>,</span>
<span id="cb15-10"><a href="grain-yield-meta-analysis.html#cb15-10" aria-hidden="true" tabindex="-1"></a>   <span class="at">cex.axis =</span> <span class="fl">0.8</span></span>
<span id="cb15-11"><a href="grain-yield-meta-analysis.html#cb15-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="_main_files/figure-html/plotContrasts-1.png" width="672" /></p>
<div id="profile-plots" class="section level3" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Profile plots</h3>
<p>Let’s inspect the profile plots to ensure the model is not over-fitted.
We expect to see the estimate align with the peak of the curve.
Also that the shape of the line is a curve.
Caution! this will take some time to run.</p>
</div>
<div id="forest-plot-of-trial-treatment-effect-per-trial" class="section level3" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> Forest plot of trial treatment effect per trial</h3>
<p>Let’s look at the trial variability in this model with a forest plot</p>
<hr />
</div>
</div>
<div id="netmeta-analysis" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> netmeta analysis</h2>
<p>We can use the <code>netmeta</code> package to give a graphical representation of the pairwise comparisons.</p>
<p>Let’s analyse the data again using a different statistical approach to see if our outcome with the <code>metafor</code> package was robust.
The <code>netmeta</code> package uses a frequentist approach to the analysis and focuses on the pairwise comparisons between treatments.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="grain-yield-meta-analysis.html#cb16-1" aria-hidden="true" tabindex="-1"></a>datPM3 <span class="ot">&lt;-</span> PM_MB_dat <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="grain-yield-meta-analysis.html#cb16-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">group_by</span>(trial, spray_management, n) <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="grain-yield-meta-analysis.html#cb16-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">summarize</span>(<span class="at">yi_mean =</span> <span class="fu">mean</span>(grain_yield.t.ha.),</span>
<span id="cb16-4"><a href="grain-yield-meta-analysis.html#cb16-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">vi_mean =</span> <span class="fu">mean</span>(vi)) <span class="sc">%&gt;%</span></span>
<span id="cb16-5"><a href="grain-yield-meta-analysis.html#cb16-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">ungroup</span>()</span></code></pre></div>
<pre><code>## `summarise()` has grouped output by &#39;trial&#39;, &#39;spray_management&#39;. You can override using the `.groups` argument.</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="grain-yield-meta-analysis.html#cb18-1" aria-hidden="true" tabindex="-1"></a>PM_con <span class="ot">&lt;-</span> <span class="fu">pairwise</span>(</span>
<span id="cb18-2"><a href="grain-yield-meta-analysis.html#cb18-2" aria-hidden="true" tabindex="-1"></a>   <span class="at">treat =</span> spray_management,</span>
<span id="cb18-3"><a href="grain-yield-meta-analysis.html#cb18-3" aria-hidden="true" tabindex="-1"></a>   <span class="at">n =</span> n,</span>
<span id="cb18-4"><a href="grain-yield-meta-analysis.html#cb18-4" aria-hidden="true" tabindex="-1"></a>   <span class="at">mean =</span> yi_mean,</span>
<span id="cb18-5"><a href="grain-yield-meta-analysis.html#cb18-5" aria-hidden="true" tabindex="-1"></a>   <span class="at">sd =</span> <span class="fu">sqrt</span>(vi_mean),</span>
<span id="cb18-6"><a href="grain-yield-meta-analysis.html#cb18-6" aria-hidden="true" tabindex="-1"></a>   <span class="at">studlab =</span> trial,</span>
<span id="cb18-7"><a href="grain-yield-meta-analysis.html#cb18-7" aria-hidden="true" tabindex="-1"></a>   <span class="at">data =</span> datPM3,</span>
<span id="cb18-8"><a href="grain-yield-meta-analysis.html#cb18-8" aria-hidden="true" tabindex="-1"></a>   <span class="at">sm =</span> <span class="st">&quot;MD&quot;</span></span>
<span id="cb18-9"><a href="grain-yield-meta-analysis.html#cb18-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-10"><a href="grain-yield-meta-analysis.html#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="grain-yield-meta-analysis.html#cb18-11" aria-hidden="true" tabindex="-1"></a>net_con <span class="ot">&lt;-</span> <span class="fu">netmeta</span>(TE,</span>
<span id="cb18-12"><a href="grain-yield-meta-analysis.html#cb18-12" aria-hidden="true" tabindex="-1"></a>                   seTE,</span>
<span id="cb18-13"><a href="grain-yield-meta-analysis.html#cb18-13" aria-hidden="true" tabindex="-1"></a>                   treat1,</span>
<span id="cb18-14"><a href="grain-yield-meta-analysis.html#cb18-14" aria-hidden="true" tabindex="-1"></a>                   treat2,</span>
<span id="cb18-15"><a href="grain-yield-meta-analysis.html#cb18-15" aria-hidden="true" tabindex="-1"></a>                   studlab,</span>
<span id="cb18-16"><a href="grain-yield-meta-analysis.html#cb18-16" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> PM_con,</span>
<span id="cb18-17"><a href="grain-yield-meta-analysis.html#cb18-17" aria-hidden="true" tabindex="-1"></a>                   <span class="at">sm =</span> <span class="st">&quot;MD&quot;</span>)</span>
<span id="cb18-18"><a href="grain-yield-meta-analysis.html#cb18-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-19"><a href="grain-yield-meta-analysis.html#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(net_con)</span></code></pre></div>
<pre><code>## Number of studies: k = 23
## Number of treatments: n = 6
## Number of pairwise comparisons: m = 126
## Number of designs: d = 7
## 
## Fixed effects model
## 
## Treatment estimate (sm = &#39;MD&#39;):
##                  control   Early    Late Late_plus Recommended Recommended_plus
## control                . -0.0489 -0.0738   -0.1726     -0.0696          -0.1256
## Early             0.0489       . -0.0249   -0.1236     -0.0206          -0.0766
## Late              0.0738  0.0249       .   -0.0988      0.0042          -0.0518
## Late_plus         0.1726  0.1236  0.0988         .      0.1030           0.0470
## Recommended       0.0696  0.0206 -0.0042   -0.1030           .          -0.0560
## Recommended_plus  0.1256  0.0766  0.0518   -0.0470      0.0560                .
## 
## Lower 95%-confidence limit:
##                  control   Early    Late Late_plus Recommended Recommended_plus
## control                . -0.1273 -0.1103   -0.2274     -0.1050          -0.1668
## Early            -0.0295       . -0.1057   -0.2156     -0.1019          -0.1599
## Late              0.0372 -0.0560       .   -0.1521     -0.0304          -0.0916
## Late_plus         0.1178  0.0317  0.0455         .      0.0474          -0.0080
## Recommended       0.0341 -0.0606 -0.0388   -0.1586           .          -0.0966
## Recommended_plus  0.0843 -0.0066  0.0120   -0.1020      0.0154                .
## 
## Upper 95%-confidence limit:
##                  control  Early    Late Late_plus Recommended Recommended_plus
## control                . 0.0295 -0.0372   -0.1178     -0.0341          -0.0843
## Early             0.1273      .  0.0560   -0.0317      0.0606           0.0066
## Late              0.1103 0.1057       .   -0.0455      0.0388          -0.0120
## Late_plus         0.2274 0.2156  0.1521         .      0.1586           0.1020
## Recommended       0.1050 0.1019  0.0304   -0.0474           .          -0.0154
## Recommended_plus  0.1668 0.1599  0.0916    0.0080      0.0966                .
## 
## Random effects model
## 
## Treatment estimate (sm = &#39;MD&#39;):
##                  control   Early    Late Late_plus Recommended Recommended_plus
## control                . -0.0514 -0.1312   -0.1943     -0.0953          -0.1501
## Early             0.0514       . -0.0798   -0.1429     -0.0440          -0.0987
## Late              0.1312  0.0798       .   -0.0631      0.0359          -0.0189
## Late_plus         0.1943  0.1429  0.0631         .      0.0990           0.0442
## Recommended       0.0953  0.0440 -0.0359   -0.0990           .          -0.0548
## Recommended_plus  0.1501  0.0987  0.0189   -0.0442      0.0548                .
## 
## Lower 95%-confidence limit:
##                  control   Early    Late Late_plus Recommended Recommended_plus
## control                . -0.1647 -0.2138   -0.3064     -0.1634          -0.2231
## Early            -0.0619       . -0.2029   -0.2945     -0.1627          -0.2189
## Late              0.0486 -0.0432       .   -0.1828     -0.0493          -0.1058
## Late_plus         0.0822 -0.0086 -0.0566         .     -0.0181          -0.0741
## Recommended       0.0273 -0.0748 -0.1210   -0.2160           .          -0.1296
## Recommended_plus  0.0771 -0.0215 -0.0680   -0.1625     -0.0201                .
## 
## Upper 95%-confidence limit:
##                  control  Early    Late Late_plus Recommended Recommended_plus
## control                . 0.0619 -0.0486   -0.0822     -0.0273          -0.0771
## Early             0.1647      .  0.0432    0.0086      0.0748           0.0215
## Late              0.2138 0.2029       .    0.0566      0.1210           0.0680
## Late_plus         0.3064 0.2945  0.1828         .      0.2160           0.1625
## Recommended       0.1634 0.1627  0.0493    0.0181           .           0.0201
## Recommended_plus  0.2231 0.2189  0.1058    0.0741      0.1296                .
## 
## Quantifying heterogeneity / inconsistency:
## tau^2 = 0.0120; tau = 0.1095; I^2 = 60.8% [47.6%; 70.7%]
## 
## Tests of heterogeneity (within designs) and inconsistency (between designs):
##                      Q d.f.  p-value
## Total           140.45   55 &lt; 0.0001
## Within designs   93.96   44 &lt; 0.0001
## Between designs  46.49   11 &lt; 0.0001</code></pre>
<p>Now let’s visualise this as a forest plot.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="grain-yield-meta-analysis.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">forest</span>(</span>
<span id="cb20-2"><a href="grain-yield-meta-analysis.html#cb20-2" aria-hidden="true" tabindex="-1"></a>   net_con,</span>
<span id="cb20-3"><a href="grain-yield-meta-analysis.html#cb20-3" aria-hidden="true" tabindex="-1"></a>   <span class="at">reference.group =</span> <span class="dv">1</span>,</span>
<span id="cb20-4"><a href="grain-yield-meta-analysis.html#cb20-4" aria-hidden="true" tabindex="-1"></a>   <span class="at">rightcols =</span> <span class="fu">c</span>(<span class="st">&quot;effect&quot;</span>, <span class="st">&quot;ci&quot;</span>, <span class="st">&quot;Pscore&quot;</span>),</span>
<span id="cb20-5"><a href="grain-yield-meta-analysis.html#cb20-5" aria-hidden="true" tabindex="-1"></a>   <span class="at">rightlabs =</span> <span class="st">&quot;P-Score&quot;</span>,</span>
<span id="cb20-6"><a href="grain-yield-meta-analysis.html#cb20-6" aria-hidden="true" tabindex="-1"></a>   <span class="at">small.values =</span> <span class="st">&quot;bad&quot;</span></span>
<span id="cb20-7"><a href="grain-yield-meta-analysis.html#cb20-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="_main_files/figure-html/netmeta-forest-1.png" width="672" /></p>
<p>The <code>netmeta</code> analysis suggests the spray schedule commencing early are no different to any other treatment including the no spray <code>control</code>.
It estimates the mean is very similar to the recommended treatments.
The <code>Recommended_plus</code> and <code>Late_plus</code> treatments show higher mean estimates, however are not significantly different from the <code>Early</code> estimate.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="grain-yield-meta-analysis.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">netgraph</span>(</span>
<span id="cb21-2"><a href="grain-yield-meta-analysis.html#cb21-2" aria-hidden="true" tabindex="-1"></a>   net_con,</span>
<span id="cb21-3"><a href="grain-yield-meta-analysis.html#cb21-3" aria-hidden="true" tabindex="-1"></a>   <span class="at">plastic =</span> <span class="cn">FALSE</span>,</span>
<span id="cb21-4"><a href="grain-yield-meta-analysis.html#cb21-4" aria-hidden="true" tabindex="-1"></a>   <span class="at">col =</span> <span class="fu">usq_cols</span>(<span class="st">&quot;support orange&quot;</span>),</span>
<span id="cb21-5"><a href="grain-yield-meta-analysis.html#cb21-5" aria-hidden="true" tabindex="-1"></a>   <span class="at">thickness =</span>  <span class="st">&quot;number.of.studies&quot;</span>,</span>
<span id="cb21-6"><a href="grain-yield-meta-analysis.html#cb21-6" aria-hidden="true" tabindex="-1"></a>   <span class="at">points =</span> <span class="cn">FALSE</span>,</span>
<span id="cb21-7"><a href="grain-yield-meta-analysis.html#cb21-7" aria-hidden="true" tabindex="-1"></a>   <span class="at">col.points =</span> <span class="fu">usq_cols</span>(<span class="st">&quot;usq charcoal&quot;</span>),</span>
<span id="cb21-8"><a href="grain-yield-meta-analysis.html#cb21-8" aria-hidden="true" tabindex="-1"></a>   <span class="at">cex.points =</span> <span class="dv">1</span>,</span>
<span id="cb21-9"><a href="grain-yield-meta-analysis.html#cb21-9" aria-hidden="true" tabindex="-1"></a>   <span class="at">number.of.studies =</span> <span class="cn">TRUE</span>,</span>
<span id="cb21-10"><a href="grain-yield-meta-analysis.html#cb21-10" aria-hidden="true" tabindex="-1"></a>   <span class="at">cex.number.of.studies =</span> <span class="dv">1</span>,</span>
<span id="cb21-11"><a href="grain-yield-meta-analysis.html#cb21-11" aria-hidden="true" tabindex="-1"></a>   <span class="at">col.number.of.studies =</span> <span class="st">&quot;black&quot;</span>,</span>
<span id="cb21-12"><a href="grain-yield-meta-analysis.html#cb21-12" aria-hidden="true" tabindex="-1"></a>   <span class="at">bg.number.of.studies =</span> <span class="fu">usq_cols</span>(<span class="st">&quot;support orange&quot;</span>),</span>
<span id="cb21-13"><a href="grain-yield-meta-analysis.html#cb21-13" aria-hidden="true" tabindex="-1"></a>   <span class="at">multiarm =</span> <span class="cn">FALSE</span>,</span>
<span id="cb21-14"><a href="grain-yield-meta-analysis.html#cb21-14" aria-hidden="true" tabindex="-1"></a>   <span class="at">col.multiarm =</span> <span class="fu">usq_cols</span>(<span class="st">&quot;support turquiose&quot;</span>),</span>
<span id="cb21-15"><a href="grain-yield-meta-analysis.html#cb21-15" aria-hidden="true" tabindex="-1"></a>   <span class="at">pos.number.of.studies =</span> <span class="fl">0.4</span></span>
<span id="cb21-16"><a href="grain-yield-meta-analysis.html#cb21-16" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="_main_files/figure-html/netgraphGW-1.png" width="672" /></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="grain-yield-meta-analysis.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">netleague</span>(net_con)</span></code></pre></div>
<pre><code>## League table (fixed effects model):
##                                                       
##                     control -0.1047 [-0.1936; -0.0157]
##  -0.0489 [-0.1273;  0.0295]                      Early
##  -0.0738 [-0.1103; -0.0372] -0.0249 [-0.1057;  0.0560]
##  -0.1726 [-0.2274; -0.1178] -0.1236 [-0.2156; -0.0317]
##  -0.0696 [-0.1050; -0.0341] -0.0206 [-0.1019;  0.0606]
##  -0.1256 [-0.1668; -0.0843] -0.0766 [-0.1599;  0.0066]
##                                                       
##  -0.0674 [-0.1122; -0.0226] -0.2666 [-0.3469; -0.1862]
##  -0.1503 [-0.2707; -0.0299]                          .
##                        Late -0.0684 [-0.1392;  0.0024]
##  -0.0988 [-0.1521; -0.0455]                  Late_plus
##   0.0042 [-0.0304;  0.0388]  0.1030 [ 0.0474;  0.1586]
##  -0.0518 [-0.0916; -0.0120]  0.0470 [-0.0080;  0.1020]
##                                                       
##  -0.0615 [-0.0980; -0.0251] -0.1243 [-0.1680; -0.0807]
##  -0.0778 [-0.2109;  0.0554] -0.1506 [-0.2839; -0.0172]
##   0.0041 [-0.0350;  0.0432] -0.0473 [-0.0944; -0.0002]
##   0.1602 [ 0.0643;  0.2561] -0.0018 [-0.0742;  0.0706]
##                 Recommended -0.0433 [-0.0856; -0.0010]
##  -0.0560 [-0.0966; -0.0154]           Recommended_plus
## 
## League table (random effects model):
##                                                       
##                     control -0.0858 [-0.2149;  0.0433]
##  -0.0514 [-0.1647;  0.0619]                      Early
##  -0.1312 [-0.2138; -0.0486] -0.0798 [-0.2029;  0.0432]
##  -0.1943 [-0.3064; -0.0822] -0.1429 [-0.2945;  0.0086]
##  -0.0953 [-0.1634; -0.0273] -0.0440 [-0.1627;  0.0748]
##  -0.1501 [-0.2231; -0.0771] -0.0987 [-0.2189;  0.0215]
##                                                       
##  -0.1334 [-0.2262; -0.0406] -0.2425 [-0.3756; -0.1093]
##  -0.1196 [-0.2756;  0.0364]                          .
##                        Late -0.0441 [-0.1914;  0.1032]
##  -0.0631 [-0.1828;  0.0566]                  Late_plus
##   0.0359 [-0.0493;  0.1210]  0.0990 [-0.0181;  0.2160]
##  -0.0189 [-0.1058;  0.0680]  0.0442 [-0.0741;  0.1625]
##                                                       
##  -0.0948 [-0.1642; -0.0253] -0.1449 [-0.2206; -0.0691]
##  -0.0850 [-0.2475;  0.0775] -0.1621 [-0.3237; -0.0004]
##   0.0368 [-0.0581;  0.1318] -0.0510 [-0.1467;  0.0446]
##   0.1455 [-0.0163;  0.3073]  0.0047 [-0.1563;  0.1658]
##                 Recommended -0.0541 [-0.1303;  0.0221]
##  -0.0548 [-0.1296;  0.0201]           Recommended_plus</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="grain-yield-meta-analysis.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">decomp.design</span>(net_con)</span></code></pre></div>
<pre><code>## Q statistics to assess homogeneity / consistency
## 
##                      Q df  p-value
## Total           140.45 55 &lt; 0.0001
## Within designs   93.96 44 &lt; 0.0001
## Between designs  46.49 11 &lt; 0.0001
## 
## Design-specific decomposition of within-designs Q statistic
## 
##                                               Design     Q df  p-value
##                                    control:Late_plus  0.70  2   0.7036
##                                  control:Recommended  0.10  1   0.7469
##      control:Early:Late:Recommended:Recommended_plus 28.07 20   0.1077
##  control:Late:Late_plus:Recommended:Recommended_plus 18.73  8   0.0164
##            control:Late:Recommended:Recommended_plus  0.66  3   0.8830
##                 control:Recommended:Recommended_plus 45.70 10 &lt; 0.0001
## 
## Between-designs Q statistic after detaching of single designs
## 
##                                      Detached design     Q df  p-value
##                                        control:Early 42.19 10 &lt; 0.0001
##                                    control:Late_plus 45.30 10 &lt; 0.0001
##                                  control:Recommended 45.51 10 &lt; 0.0001
##      control:Early:Late:Recommended:Recommended_plus 34.79  7 &lt; 0.0001
##  control:Late:Late_plus:Recommended:Recommended_plus 21.47  7   0.0031
##            control:Late:Recommended:Recommended_plus 23.37  8   0.0029
##                 control:Recommended:Recommended_plus 45.22  9 &lt; 0.0001
## 
## Q statistic to assess consistency under the assumption of
## a full design-by-treatment interaction random effects model
## 
##                     Q df p-value tau.within tau2.within
## Between designs 11.15 11  0.4309     0.1063      0.0113</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="grain-yield-meta-analysis.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">netsplit</span>(net_con)</span></code></pre></div>
<pre><code>## Separate indirect from direct evidence (SIDE) using back-calculation method
## 
## Fixed effects model: 
## 
##                    comparison  k prop     nma  direct  indir.    Diff     z p-value
##                 control:Early  7 0.78 -0.0489 -0.1047  0.1463 -0.2510 -2.61  0.0091
##                  control:Late 11 0.67 -0.0738 -0.0674 -0.0865  0.0192  0.48  0.6278
##             control:Late_plus  6 0.47 -0.1726 -0.2666 -0.0908 -0.1758 -3.14  0.0017
##           control:Recommended 19 0.94 -0.0696 -0.0615 -0.1991  0.1375  1.78  0.0745
##      control:Recommended_plus 17 0.89 -0.1256 -0.1243 -0.1358  0.0115  0.17  0.8666
##                    Early:Late  6 0.45 -0.0249 -0.1503  0.0782 -0.2285 -2.76  0.0058
##               Early:Late_plus  0    0 -0.1236       . -0.1236       .     .       .
##             Early:Recommended  6 0.37 -0.0206 -0.0778  0.0133 -0.0911 -1.06  0.2882
##        Early:Recommended_plus  6 0.39 -0.0766 -0.1506 -0.0295 -0.1210 -1.39  0.1645
##                Late:Late_plus  3 0.57 -0.0988 -0.0684 -0.1384  0.0700  1.28  0.2018
##              Late:Recommended 11 0.78  0.0042  0.0041  0.0047 -0.0006 -0.01  0.9895
##         Late:Recommended_plus 11 0.71 -0.0518 -0.0473 -0.0630  0.0157  0.35  0.7268
##         Late_plus:Recommended  3 0.34  0.1030  0.1602  0.0741  0.0861  1.43  0.1516
##    Late_plus:Recommended_plus  3 0.58  0.0470 -0.0018  0.1137 -0.1155 -2.03  0.0421
##  Recommended:Recommended_plus 17 0.92 -0.0560 -0.0433 -0.2017  0.1584  2.08  0.0376
## 
## Random effects model: 
## 
##                    comparison  k prop     nma  direct  indir.    Diff     z p-value
##                 control:Early  7 0.77 -0.0514 -0.0858  0.0640 -0.1498 -1.09  0.2757
##                  control:Late 11 0.79 -0.1312 -0.1334 -0.1228 -0.0106 -0.10  0.9192
##             control:Late_plus  6 0.71 -0.1943 -0.2425 -0.0770 -0.1654 -1.31  0.1888
##           control:Recommended 19 0.96 -0.0953 -0.0948 -0.1089  0.0141  0.08  0.9351
##      control:Recommended_plus 17 0.93 -0.1501 -0.1449 -0.2187  0.0739  0.51  0.6102
##                    Early:Late  6 0.62 -0.0798 -0.1196 -0.0142 -0.1054 -0.81  0.4159
##               Early:Late_plus  0    0 -0.1429       . -0.1429       .     .       .
##             Early:Recommended  6 0.53 -0.0440 -0.0850  0.0030 -0.0880 -0.72  0.4688
##        Early:Recommended_plus  6 0.55 -0.0987 -0.1621 -0.0204 -0.1417 -1.15  0.2507
##                Late:Late_plus  3 0.66 -0.0631 -0.0441 -0.1001  0.0560  0.43  0.6642
##              Late:Recommended 11 0.80  0.0359  0.0368  0.0318  0.0050  0.05  0.9633
##         Late:Recommended_plus 11 0.83 -0.0189 -0.0510  0.1329 -0.1839 -1.58  0.1151
##         Late_plus:Recommended  3 0.52  0.0990  0.1455  0.0479  0.0976  0.82  0.4140
##    Late_plus:Recommended_plus  3 0.54  0.0442  0.0047  0.0904 -0.0857 -0.71  0.4790
##  Recommended:Recommended_plus 17 0.96 -0.0548 -0.0541 -0.0731  0.0190  0.09  0.9264
## 
## Legend:
##  comparison - Treatment comparison
##  k          - Number of studies providing direct evidence
##  prop       - Direct evidence proportion
##  nma        - Estimated treatment effect (MD) in network meta-analysis
##  direct     - Estimated treatment effect (MD) derived from direct evidence
##  indir.     - Estimated treatment effect (MD) derived from indirect evidence
##  Diff       - Difference between direct and indirect treatment estimates
##  z          - z-value of test for disagreement (direct versus indirect)
##  p-value    - p-value of test for disagreement (direct versus indirect)</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="grain-yield-meta-analysis.html#cb28-1" aria-hidden="true" tabindex="-1"></a>nm1 <span class="ot">&lt;-</span> <span class="fu">netmeasures</span>(net_con)</span>
<span id="cb28-2"><a href="grain-yield-meta-analysis.html#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="grain-yield-meta-analysis.html#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb28-4"><a href="grain-yield-meta-analysis.html#cb28-4" aria-hidden="true" tabindex="-1"></a>   nm1<span class="sc">$</span>meanpath,</span>
<span id="cb28-5"><a href="grain-yield-meta-analysis.html#cb28-5" aria-hidden="true" tabindex="-1"></a>   nm1<span class="sc">$</span>minpar,</span>
<span id="cb28-6"><a href="grain-yield-meta-analysis.html#cb28-6" aria-hidden="true" tabindex="-1"></a>   <span class="at">pch =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb28-7"><a href="grain-yield-meta-analysis.html#cb28-7" aria-hidden="true" tabindex="-1"></a>   <span class="at">xlab =</span> <span class="st">&quot;Mean path length&quot;</span>,</span>
<span id="cb28-8"><a href="grain-yield-meta-analysis.html#cb28-8" aria-hidden="true" tabindex="-1"></a>   <span class="at">ylab =</span> <span class="st">&quot;Minimal parallelism&quot;</span></span>
<span id="cb28-9"><a href="grain-yield-meta-analysis.html#cb28-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-10"><a href="grain-yield-meta-analysis.html#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(nm1<span class="sc">$</span>meanpath, nm1<span class="sc">$</span>minpar, <span class="fu">names</span>(nm1<span class="sc">$</span>meanpath), <span class="at">cex =</span> <span class="fl">0.8</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="grain-yield-meta-analysis.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(efficacy,</span>
<span id="cb29-2"><a href="grain-yield-meta-analysis.html#cb29-2" aria-hidden="true" tabindex="-1"></a>     PM_MB_dat,</span>
<span id="cb29-3"><a href="grain-yield-meta-analysis.html#cb29-3" aria-hidden="true" tabindex="-1"></a>     PM_mv,</span>
<span id="cb29-4"><a href="grain-yield-meta-analysis.html#cb29-4" aria-hidden="true" tabindex="-1"></a>     contrast_Ssum,</span>
<span id="cb29-5"><a href="grain-yield-meta-analysis.html#cb29-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">file =</span> <span class="fu">here</span>(<span class="st">&quot;cache/Meta-analysisData.Rdata&quot;</span>))</span></code></pre></div>

<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-Viechtbauer2010" class="csl-entry">
Viechtbauer, Wolfgang. 2010. <span>“Conducting Meta-Analyses in <span>R</span> with the <span class="nocase">metafor</span> Package.”</span> <em>Journal of Statistical Software</em> 36 (3): 1–48. <a href="https://doi.org/10.18637/jss.v036.i03">https://doi.org/10.18637/jss.v036.i03</a>.
</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="prepare-data-for-meta-analysis.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
