<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Meta-analysis | A meta-analysis of powdery mildew yield loss mitigation strategies in Australian mungbean</title>
  <meta name="description" content="A meta-analysis of fungicide use in mungbean to control for yield loss due to powdery mildew." />
  <meta name="generator" content="bookdown 0.19 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Meta-analysis | A meta-analysis of powdery mildew yield loss mitigation strategies in Australian mungbean" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A meta-analysis of fungicide use in mungbean to control for yield loss due to powdery mildew." />
  <meta name="github-repo" content="OpenPlantPathology/Mungbean_PM" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Meta-analysis | A meta-analysis of powdery mildew yield loss mitigation strategies in Australian mungbean" />
  
  <meta name="twitter:description" content="A meta-analysis of fungicide use in mungbean to control for yield loss due to powdery mildew." />
  

<meta name="author" content="Paul Melloy, Emerson Del Ponte and Adam H. Sparks" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="prepare-data-for-meta-analysis.html"/>
<link rel="next" href="aupdc-meta-analysis.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Home</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#contents"><i class="fa fa-check"></i><b>1.1</b> Contents</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#other-research-questions-which-are-not-the-focus-of-this-study"><i class="fa fa-check"></i><b>1.2</b> Other research questions, which are not the focus of this study</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#possible-sources-of-variation-in-this-analysis."><i class="fa fa-check"></i><b>1.3</b> Possible sources of variation in this analysis.</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="studies-considered-in-meta-analysis.html"><a href="studies-considered-in-meta-analysis.html"><i class="fa fa-check"></i><b>2</b> Studies considered in meta-analysis</a><ul>
<li class="chapter" data-level="2.1" data-path="studies-considered-in-meta-analysis.html"><a href="studies-considered-in-meta-analysis.html#summary-of-trials"><i class="fa fa-check"></i><b>2.1</b> Summary of trials</a></li>
<li class="chapter" data-level="2.2" data-path="studies-considered-in-meta-analysis.html"><a href="studies-considered-in-meta-analysis.html#powdery-mildew-rating-scales"><i class="fa fa-check"></i><b>2.2</b> Powdery mildew rating scales</a><ul>
<li class="chapter" data-level="2.2.1" data-path="studies-considered-in-meta-analysis.html"><a href="studies-considered-in-meta-analysis.html#powdery-mildew-rating-scale"><i class="fa fa-check"></i><b>2.2.1</b> 1 - 5 powdery mildew rating scale</a></li>
<li class="chapter" data-level="2.2.2" data-path="studies-considered-in-meta-analysis.html"><a href="studies-considered-in-meta-analysis.html#powdery-mildew-rating-scale-1"><i class="fa fa-check"></i><b>2.2.2</b> 1 - 9 powdery mildew rating scale</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="studies-considered-in-meta-analysis.html"><a href="studies-considered-in-meta-analysis.html#experiment-locations"><i class="fa fa-check"></i><b>2.3</b> Experiment locations</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html"><i class="fa fa-check"></i><b>3</b> Preliminary Analysis</a><ul>
<li class="chapter" data-level="3.1" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#explore-and-visualise-data"><i class="fa fa-check"></i><b>3.1</b> Explore and Visualise Data</a><ul>
<li class="chapter" data-level="3.1.1" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#fungicides"><i class="fa fa-check"></i><b>3.1.1</b> Fungicides</a></li>
<li class="chapter" data-level="3.1.2" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#mungbean-cultivars"><i class="fa fa-check"></i><b>3.1.2</b> Mungbean cultivars</a></li>
<li class="chapter" data-level="3.1.3" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#row-spacing"><i class="fa fa-check"></i><b>3.1.3</b> Row spacing</a></li>
<li class="chapter" data-level="3.1.4" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#yield-vs-in-season-rain"><i class="fa fa-check"></i><b>3.1.4</b> Yield vs in-season rain</a></li>
<li class="chapter" data-level="3.1.5" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#season-range-and-first-incidence"><i class="fa fa-check"></i><b>3.1.5</b> Season range and first incidence</a></li>
<li class="chapter" data-level="3.1.6" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#audpc-visualise-raw-data"><i class="fa fa-check"></i><b>3.1.6</b> AUDPC visualise raw data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html"><i class="fa fa-check"></i><b>4</b> Prepare data for meta-analysis</a><ul>
<li class="chapter" data-level="4.1" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#set-environment-and-import-data"><i class="fa fa-check"></i><b>4.1</b> Set environment and import data</a></li>
<li class="chapter" data-level="4.2" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#standardising-sample-variance"><i class="fa fa-check"></i><b>4.2</b> Standardising sample variance</a><ul>
<li class="chapter" data-level="4.2.1" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#converting-least-squares-to-sample-variance"><i class="fa fa-check"></i><b>4.2.1</b> Converting least-squares to sample variance</a></li>
<li class="chapter" data-level="4.2.2" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#converting-standard-deviation-to-sample-variance"><i class="fa fa-check"></i><b>4.2.2</b> Converting standard deviation to sample variance</a></li>
<li class="chapter" data-level="4.2.3" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#check-variance-of-data-set"><i class="fa fa-check"></i><b>4.2.3</b> Check variance of data-set</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#reduce-data-set-to-required-variables"><i class="fa fa-check"></i><b>4.3</b> Reduce data set to required variables</a><ul>
<li class="chapter" data-level="4.3.1" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#cluster-fungicide-applications"><i class="fa fa-check"></i><b>4.3.1</b> Cluster fungicide applications</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#test-dose-effect"><i class="fa fa-check"></i><b>4.4</b> Test dose effect</a><ul>
<li class="chapter" data-level="4.4.1" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#disease-pressure-factor"><i class="fa fa-check"></i><b>4.4.1</b> Disease pressure factor</a></li>
<li class="chapter" data-level="4.4.2" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#row-spacing-1"><i class="fa fa-check"></i><b>4.4.2</b> Row spacing</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="meta-analysis.html"><a href="meta-analysis.html"><i class="fa fa-check"></i><b>5</b> Meta-analysis</a><ul>
<li class="chapter" data-level="5.1" data-path="meta-analysis.html"><a href="meta-analysis.html#grain-yield-meta-analysis"><i class="fa fa-check"></i><b>5.1</b> Grain yield meta-analysis</a><ul>
<li class="chapter" data-level="5.1.1" data-path="meta-analysis.html"><a href="meta-analysis.html#formatting-variance"><i class="fa fa-check"></i><b>5.1.1</b> Formatting Variance</a></li>
<li class="chapter" data-level="5.1.2" data-path="meta-analysis.html"><a href="meta-analysis.html#calculate-standardised-mean-differences"><i class="fa fa-check"></i><b>5.1.2</b> Calculate standardised mean differences</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="meta-analysis.html"><a href="meta-analysis.html#meta-analysis-1"><i class="fa fa-check"></i><b>5.2</b> Meta-analysis</a><ul>
<li class="chapter" data-level="5.2.1" data-path="meta-analysis.html"><a href="meta-analysis.html#metafor-package"><i class="fa fa-check"></i><b>5.2.1</b> metafor package</a></li>
<li class="chapter" data-level="5.2.2" data-path="meta-analysis.html"><a href="meta-analysis.html#profile-plots"><i class="fa fa-check"></i><b>5.2.2</b> Profile plots</a></li>
<li class="chapter" data-level="5.2.3" data-path="meta-analysis.html"><a href="meta-analysis.html#metafor-comparisons"><i class="fa fa-check"></i><b>5.2.3</b> Metafor comparisons</a></li>
<li class="chapter" data-level="5.2.4" data-path="meta-analysis.html"><a href="meta-analysis.html#disease-pressure-effect"><i class="fa fa-check"></i><b>5.2.4</b> Disease pressure effect</a></li>
<li class="chapter" data-level="5.2.5" data-path="meta-analysis.html"><a href="meta-analysis.html#netmeta-package"><i class="fa fa-check"></i><b>5.2.5</b> netmeta package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="aupdc-meta-analysis.html"><a href="aupdc-meta-analysis.html"><i class="fa fa-check"></i><b>6</b> AUPDC meta-analysis</a><ul>
<li class="chapter" data-level="6.0.1" data-path="aupdc-meta-analysis.html"><a href="aupdc-meta-analysis.html#spray-management-and-audpc"><i class="fa fa-check"></i><b>6.0.1</b> Spray management and AUDPC</a></li>
<li class="chapter" data-level="6.1" data-path="aupdc-meta-analysis.html"><a href="aupdc-meta-analysis.html#aupdc-impact-on-grain-yield-meta-analysis"><i class="fa fa-check"></i><b>6.1</b> AUPDC impact on grain yield meta-analysis</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html"><i class="fa fa-check"></i><b>7</b> Manuscript wire frame</a><ul>
<li class="chapter" data-level="7.1" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#who-are-the-intended-readers---list-3-to-5-of-them-by-name"><i class="fa fa-check"></i><b>7.1</b> Who are the intended readers? - list 3 to 5 of them by name</a></li>
<li class="chapter" data-level="7.2" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-did-you-do-limit---50-words"><i class="fa fa-check"></i><b>7.2</b> what did you do? (limit - 50 words)</a></li>
<li class="chapter" data-level="7.3" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#why-did-you-do-it-limit---50-words"><i class="fa fa-check"></i><b>7.3</b> Why did you do it? (limit - 50 words)</a></li>
<li class="chapter" data-level="7.4" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-happened-limit---50-words"><i class="fa fa-check"></i><b>7.4</b> what happened? (limit - 50 words)</a></li>
<li class="chapter" data-level="7.5" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-do-the-results-mean-in-theory-limit---50-words"><i class="fa fa-check"></i><b>7.5</b> What do the results mean in theory? (limit - 50 words)</a></li>
<li class="chapter" data-level="7.6" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-do-the-results-mean-in-practice-limit---50-words"><i class="fa fa-check"></i><b>7.6</b> What do the results mean in practice? (limit - 50 words)</a></li>
<li class="chapter" data-level="7.7" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-is-the-key-benefit-for-your-readers-limit---25-words."><i class="fa fa-check"></i><b>7.7</b> what is the key benefit for your readers? (limit - 25 words).</a></li>
<li class="chapter" data-level="7.8" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-remains-unresolved-no-word-limit."><i class="fa fa-check"></i><b>7.8</b> What remains unresolved? (no word limit).</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="manuscript.html"><a href="manuscript.html"><i class="fa fa-check"></i><b>8</b> Manuscript</a><ul>
<li class="chapter" data-level="8.1" data-path="manuscript.html"><a href="manuscript.html#introduction"><i class="fa fa-check"></i><b>8.1</b> Introduction</a><ul>
<li class="chapter" data-level="8.1.1" data-path="manuscript.html"><a href="manuscript.html#managements-strategies"><i class="fa fa-check"></i><b>8.1.1</b> Managements strategies</a></li>
<li class="chapter" data-level="8.1.2" data-path="manuscript.html"><a href="manuscript.html#fungicide-resistance"><i class="fa fa-check"></i><b>8.1.2</b> Fungicide resistance</a></li>
<li class="chapter" data-level="8.1.3" data-path="manuscript.html"><a href="manuscript.html#previous-studies---fungicide-work"><i class="fa fa-check"></i><b>8.1.3</b> Previous studies - fungicide work</a></li>
<li class="chapter" data-level="8.1.4" data-path="manuscript.html"><a href="manuscript.html#meta-analysis-2"><i class="fa fa-check"></i><b>8.1.4</b> Meta-analysis</a></li>
<li class="chapter" data-level="8.1.5" data-path="manuscript.html"><a href="manuscript.html#aims"><i class="fa fa-check"></i><b>8.1.5</b> Aims</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="manuscript.html"><a href="manuscript.html#materials-and-methods"><i class="fa fa-check"></i><b>8.2</b> Materials and methods</a></li>
<li class="chapter" data-level="8.3" data-path="manuscript.html"><a href="manuscript.html#results"><i class="fa fa-check"></i><b>8.3</b> Results</a></li>
<li class="chapter" data-level="8.4" data-path="manuscript.html"><a href="manuscript.html#discussion"><i class="fa fa-check"></i><b>8.4</b> Discussion</a><ul>
<li class="chapter" data-level="8.4.1" data-path="manuscript.html"><a href="manuscript.html#fungicide-resistance-1"><i class="fa fa-check"></i><b>8.4.1</b> Fungicide resistance</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A meta-analysis of powdery mildew yield loss mitigation strategies in Australian mungbean</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="meta-analysis" class="section level1">
<h1><span class="header-section-number">5</span> Meta-analysis</h1>
<div id="grain-yield-meta-analysis" class="section level2">
<h2><span class="header-section-number">5.1</span> Grain yield meta-analysis</h2>
<p>Let’s get started with the analysis by first finding the best model fit that answers our research question.</p>
<blockquote>
<p>Which spray management scenario provides the greatest yield protection from powdery mildew.</p>
</blockquote>
<p>To do this, in our model:</p>
<ul>
<li><p>Grain yield is our response variable and will be converted to kg / ha</p></li>
<li><p>Trial, which resolves combinations of categorical variables: year, location, row spacing, fungicide dose and cultivar; is set as a random intercept</p></li>
<li><p>We will test spray management (our treatment) as a fixed effect and random slope to trial</p></li>
</ul>
<p>First, how well the data is compared across the trial years and trials.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="meta-analysis.html#cb1-1"></a><span class="kw">kable</span>(</span>
<span id="cb1-2"><a href="meta-analysis.html#cb1-2"></a>   <span class="kw">table</span>(slimmer_PM_dat<span class="op">$</span>spray_management, slimmer_PM_dat<span class="op">$</span>year),</span>
<span id="cb1-3"><a href="meta-analysis.html#cb1-3"></a>   <span class="dt">align =</span> <span class="kw">rep</span>(<span class="st">&#39;c&#39;</span>, <span class="dv">8</span>),</span>
<span id="cb1-4"><a href="meta-analysis.html#cb1-4"></a>   <span class="dt">caption =</span> <span class="st">&quot;Which treatments and how many treatments are represented in each year&quot;</span></span>
<span id="cb1-5"><a href="meta-analysis.html#cb1-5"></a>) <span class="op">%&gt;%</span></span>
<span id="cb1-6"><a href="meta-analysis.html#cb1-6"></a><span class="st">   </span><span class="kw">kable_styling</span>(</span>
<span id="cb1-7"><a href="meta-analysis.html#cb1-7"></a>      <span class="st">&quot;striped&quot;</span>,</span>
<span id="cb1-8"><a href="meta-analysis.html#cb1-8"></a>      <span class="dt">fixed_thead =</span> <span class="ot">TRUE</span>,</span>
<span id="cb1-9"><a href="meta-analysis.html#cb1-9"></a>      <span class="dt">full_width =</span> <span class="ot">FALSE</span>,</span>
<span id="cb1-10"><a href="meta-analysis.html#cb1-10"></a>      <span class="dt">position =</span> <span class="st">&quot;center&quot;</span></span>
<span id="cb1-11"><a href="meta-analysis.html#cb1-11"></a>   )</span></code></pre></div>
<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:table_of_nTreatments)Which treatments and how many treatments are represented in each year
</caption>
<thead>
<tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
2011
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
2012
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
2013
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
2015
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
2016
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
2017
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
2018
</th>
<th style="text-align:center;position: sticky; top:0; background-color: #FFFFFF;">
2019
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
control
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
18
</td>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Early
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Late
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Late_plus
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Recommended
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
12
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Recommended_plus
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
24
</td>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
2
</td>
</tr>
</tbody>
</table>
<p>Before analysis let’s have a look at the trimmed down modified data.</p>
<p>Treatments Late_plus and early don’t have very good comparison to other treatments.</p>
<p>Let’s visualise the spread of data in each treatments with box-plots.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="meta-analysis.html#cb2-1"></a><span class="co"># class spray_management as a factor and reorder them for the plot</span></span>
<span id="cb2-2"><a href="meta-analysis.html#cb2-2"></a>slimmer_PM_dat<span class="op">$</span>spray_management &lt;-</span>
<span id="cb2-3"><a href="meta-analysis.html#cb2-3"></a><span class="st">   </span><span class="kw">factor</span>(slimmer_PM_dat<span class="op">$</span>spray_management,</span>
<span id="cb2-4"><a href="meta-analysis.html#cb2-4"></a>          <span class="kw">levels</span>(<span class="kw">factor</span>(slimmer_PM_dat<span class="op">$</span>spray_management))[<span class="kw">rev</span>(<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">3</span>, <span class="dv">4</span>))])</span>
<span id="cb2-5"><a href="meta-analysis.html#cb2-5"></a></span>
<span id="cb2-6"><a href="meta-analysis.html#cb2-6"></a>slimmer_PM_dat <span class="op">%&gt;%</span></span>
<span id="cb2-7"><a href="meta-analysis.html#cb2-7"></a><span class="st">   </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> grain_yield.t.ha, <span class="dt">x =</span> spray_management)) <span class="op">+</span></span>
<span id="cb2-8"><a href="meta-analysis.html#cb2-8"></a><span class="st">   </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></span>
<span id="cb2-9"><a href="meta-analysis.html#cb2-9"></a><span class="st">   </span><span class="co">#geom_point(position = &quot;jitter&quot;, alpha = 1/5)+</span></span>
<span id="cb2-10"><a href="meta-analysis.html#cb2-10"></a><span class="st">   </span><span class="kw">geom_jitter</span>(<span class="dt">width =</span> <span class="fl">0.1</span>, <span class="dt">alpha =</span> <span class="dv">1</span> <span class="op">/</span><span class="st"> </span><span class="dv">5</span>) <span class="op">+</span></span>
<span id="cb2-11"><a href="meta-analysis.html#cb2-11"></a><span class="st">   </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Spray management variable&quot;</span>,</span>
<span id="cb2-12"><a href="meta-analysis.html#cb2-12"></a>        <span class="dt">y =</span> <span class="st">&quot;Grain yield (t/Ha)&quot;</span>,</span>
<span id="cb2-13"><a href="meta-analysis.html#cb2-13"></a>        <span class="dt">title =</span> <span class="st">&quot;Mean grain yield from each treatment </span><span class="ch">\n</span><span class="st"> categorised by spray management scenario&quot;</span>) <span class="op">+</span></span>
<span id="cb2-14"><a href="meta-analysis.html#cb2-14"></a><span class="st">   </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>)) <span class="op">+</span></span>
<span id="cb2-15"><a href="meta-analysis.html#cb2-15"></a><span class="st">   </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>, <span class="dt">linetype =</span> <span class="dv">2</span>) <span class="op">+</span></span>
<span id="cb2-16"><a href="meta-analysis.html#cb2-16"></a><span class="st">   </span><span class="kw">coord_flip</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/treatment_means_plot-1.png" width="672" /></p>
<p>There seems like little difference between the treatments, with exception to <code>Late_plus</code>.
Let’s do this plot again, but let’s look at the proportional mean difference between the treatments and the no spray control for each study, this should reduce variation in yield due between trials.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="meta-analysis.html#cb3-1"></a>slimmer_PM_dat<span class="op">$</span>spray_management &lt;-</span>
<span id="cb3-2"><a href="meta-analysis.html#cb3-2"></a><span class="st">   </span><span class="kw">factor</span>(slimmer_PM_dat<span class="op">$</span>spray_management, <span class="kw">rev</span>(</span>
<span id="cb3-3"><a href="meta-analysis.html#cb3-3"></a>      <span class="kw">c</span>(</span>
<span id="cb3-4"><a href="meta-analysis.html#cb3-4"></a>         <span class="st">&quot;control&quot;</span>,</span>
<span id="cb3-5"><a href="meta-analysis.html#cb3-5"></a>         <span class="st">&quot;Early&quot;</span>,</span>
<span id="cb3-6"><a href="meta-analysis.html#cb3-6"></a>         <span class="st">&quot;Recommended&quot;</span>,</span>
<span id="cb3-7"><a href="meta-analysis.html#cb3-7"></a>         <span class="st">&quot;Recommended_plus&quot;</span>,</span>
<span id="cb3-8"><a href="meta-analysis.html#cb3-8"></a>         <span class="st">&quot;Late&quot;</span>,</span>
<span id="cb3-9"><a href="meta-analysis.html#cb3-9"></a>         <span class="st">&quot;Late_plus&quot;</span></span>
<span id="cb3-10"><a href="meta-analysis.html#cb3-10"></a>      )</span>
<span id="cb3-11"><a href="meta-analysis.html#cb3-11"></a>   ))</span>
<span id="cb3-12"><a href="meta-analysis.html#cb3-12"></a></span>
<span id="cb3-13"><a href="meta-analysis.html#cb3-13"></a>slimmer_PM_dat <span class="op">%&gt;%</span></span>
<span id="cb3-14"><a href="meta-analysis.html#cb3-14"></a><span class="st">   </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> prop_yield_gain, <span class="dt">x =</span> spray_management)) <span class="op">+</span></span>
<span id="cb3-15"><a href="meta-analysis.html#cb3-15"></a><span class="st">   </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></span>
<span id="cb3-16"><a href="meta-analysis.html#cb3-16"></a><span class="st">   </span><span class="kw">geom_jitter</span>(<span class="dt">width =</span> <span class="fl">0.1</span>, <span class="dt">alpha =</span> <span class="dv">1</span> <span class="op">/</span><span class="st"> </span><span class="dv">5</span>) <span class="op">+</span></span>
<span id="cb3-17"><a href="meta-analysis.html#cb3-17"></a><span class="st">   </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Spray management variable&quot;</span>,</span>
<span id="cb3-18"><a href="meta-analysis.html#cb3-18"></a>        <span class="dt">y =</span> <span class="st">&quot;Grain yield (t/Ha)&quot;</span>,</span>
<span id="cb3-19"><a href="meta-analysis.html#cb3-19"></a>        <span class="dt">title =</span> <span class="st">&quot;Mean grain yield difference to the control for each treatment </span><span class="ch">\n</span><span class="st"> categorised by spray management scenario&quot;</span>) <span class="op">+</span></span>
<span id="cb3-20"><a href="meta-analysis.html#cb3-20"></a><span class="st">   </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>)) <span class="op">+</span></span>
<span id="cb3-21"><a href="meta-analysis.html#cb3-21"></a><span class="st">   </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>, <span class="dt">linetype =</span> <span class="dv">2</span>) <span class="op">+</span></span>
<span id="cb3-22"><a href="meta-analysis.html#cb3-22"></a><span class="st">   </span><span class="kw">coord_flip</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 40 rows containing non-finite values (stat_boxplot).</code></pre>
<pre><code>## Warning: Removed 40 rows containing missing values (geom_point).</code></pre>
<p><img src="_main_files/figure-html/plot_yieldProportion-1.png" width="672" /></p>
<p>Using the mean difference in the treatment effect seems to show the effect of each treatment better than just raw yield and reduces the variability in the treatments.
We know there is a good deal of variability in our studies and between them.
Mungbean produces variable yields between seasons so we should use a response that highlights the difference in the treatment effects that we are interested in and reduce the variability.
Let’s calculate the standardised mean difference for each treatment to reduce the variability in the meta-analysis.</p>
<div id="formatting-variance" class="section level3">
<h3><span class="header-section-number">5.1.1</span> Formatting Variance</h3>
<p>First lets remove any entries missing variance.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="meta-analysis.html#cb6-1"></a><span class="kw">any</span>(<span class="kw">is.na</span>(slimmer_PM_dat<span class="op">$</span>yield_error))</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="meta-analysis.html#cb8-1"></a>slimmer_PM_dat &lt;-<span class="st"> </span></span>
<span id="cb8-2"><a href="meta-analysis.html#cb8-2"></a><span class="st">   </span>slimmer_PM_dat[<span class="op">!</span><span class="kw">is.na</span>(slimmer_PM_dat<span class="op">$</span>yield_error),]</span>
<span id="cb8-3"><a href="meta-analysis.html#cb8-3"></a></span>
<span id="cb8-4"><a href="meta-analysis.html#cb8-4"></a>slimmer_PM_dat<span class="op">$</span>vi &lt;-<span class="st"> </span>slimmer_PM_dat<span class="op">$</span>yield_error</span></code></pre></div>
<div id="calculate-sample-variance-from-mean-square-errors" class="section level4">
<h4><span class="header-section-number">5.1.1.1</span> Calculate sample variance from mean square errors</h4>
<p>Currently our data frame has the sample variance calculated earlier, however we can approximate it using the mean squared error.
Let’s show the rational for our calculation and then add a secondary variance column (<code>vi2</code>).</p>
<p><span class="math inline">\(MSE = Var + bias\)</span></p>
<p>However if our MSE was calculated from an unbiased sample we can assume <span class="math inline">\(bias = 0\)</span> and therefore:</p>
<p><span class="math inline">\(MSE = Var\)</span></p>
<p>To calculate the sample variance (for each treatment in the trial) from the mean square error (Trial variance) all we need to do is divide by the number of samples in each treatment.
We can show this because:
<span class="math inline">\(MSE = \frac{\sum_{y_1}^{y_n}(y_i - \overline{y})^2}{n - 1}\)</span>
Where the sum of squares for the fungicide treatment estimator (<span class="math inline">\(y\)</span>) is divided by the number of fungicide treatments (<span class="math inline">\(n\)</span>).</p>
<p>The sample variance is a similar formula except we use <span class="math inline">\(x\)</span> instead of <span class="math inline">\(y\)</span>.
<span class="math inline">\(S_{Var} = \frac{\sum_{x_1}^{x_n}(x_i - \overline{x})^2}{n - 1}\)</span><br />
<span class="math inline">\(x\)</span> being each observation within the experiment and <span class="math inline">\(n\)</span> being the number of samples in the whole trial.
Therefore:
<span class="math inline">\(S_{Var}\approx\frac{1}{n_{x}}\frac{\sum_{y_1}^{y_n}(y_i - \overline{y})^2}{n_y - 1}\)</span><br />
Where <span class="math inline">\(n_x\)</span> is the number of samples within each treatment.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="meta-analysis.html#cb9-1"></a><span class="co">#calculation when using log of response</span></span>
<span id="cb9-2"><a href="meta-analysis.html#cb9-2"></a><span class="co"># slimmer_PM_dat$vi &lt;-</span></span>
<span id="cb9-3"><a href="meta-analysis.html#cb9-3"></a><span class="co">#    slimmer_PM_dat$Y_Msquare / (slimmer_PM_dat$n * slimmer_PM_dat$grain_yield.t.ha ^</span></span>
<span id="cb9-4"><a href="meta-analysis.html#cb9-4"></a><span class="co">#                                   2)</span></span>
<span id="cb9-5"><a href="meta-analysis.html#cb9-5"></a><span class="co">#</span></span>
<span id="cb9-6"><a href="meta-analysis.html#cb9-6"></a>slimmer_PM_dat<span class="op">$</span>vi2 &lt;-<span class="st"> </span></span>
<span id="cb9-7"><a href="meta-analysis.html#cb9-7"></a><span class="st">   </span>slimmer_PM_dat<span class="op">$</span>Y_Msquare <span class="op">/</span><span class="st"> </span></span>
<span id="cb9-8"><a href="meta-analysis.html#cb9-8"></a><span class="st">   </span>slimmer_PM_dat<span class="op">$</span>n</span></code></pre></div>
<p>We have removed the studies that don’t report any variance from the analysis.</p>
</div>
</div>
<div id="calculate-standardised-mean-differences" class="section level3">
<h3><span class="header-section-number">5.1.2</span> Calculate standardised mean differences</h3>
<p>Let’s calculate standardised mean differences and add them to the data frame.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="meta-analysis.html#cb10-1"></a>slimmer_PM_dat<span class="op">$</span>pooledSD &lt;-<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb10-2"><a href="meta-analysis.html#cb10-2"></a>slimmer_PM_dat<span class="op">$</span>vi_C &lt;-<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb10-3"><a href="meta-analysis.html#cb10-3"></a><span class="cf">for</span> (T_ref <span class="cf">in</span> slimmer_PM_dat<span class="op">$</span>trial_ref) {</span>
<span id="cb10-4"><a href="meta-analysis.html#cb10-4"></a>   <span class="co"># First we need to Calculate the pooled standard deviation</span></span>
<span id="cb10-5"><a href="meta-analysis.html#cb10-5"></a>   slimmer_PM_dat[slimmer_PM_dat<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>T_ref, <span class="st">&quot;pooledSD&quot;</span>] &lt;-</span>
<span id="cb10-6"><a href="meta-analysis.html#cb10-6"></a><span class="st">      </span><span class="kw">sqrt</span>(<span class="kw">sum</span>((slimmer_PM_dat[slimmer_PM_dat<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>T_ref, <span class="st">&quot;n&quot;</span>] <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">*</span><span class="st"> </span>slimmer_PM_dat[slimmer_PM_dat<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>T_ref, <span class="st">&quot;yield_error&quot;</span>]) <span class="op">/</span></span>
<span id="cb10-7"><a href="meta-analysis.html#cb10-7"></a><span class="st">              </span>(<span class="kw">sum</span>(slimmer_PM_dat[slimmer_PM_dat<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>T_ref, <span class="st">&quot;n&quot;</span>]) <span class="op">-</span><span class="st"> </span><span class="kw">nrow</span>(slimmer_PM_dat[slimmer_PM_dat<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>T_ref,])))</span>
<span id="cb10-8"><a href="meta-analysis.html#cb10-8"></a>   </span>
<span id="cb10-9"><a href="meta-analysis.html#cb10-9"></a>   <span class="co"># Then Create a column with the value of the mean grain yield of the no spray control for comparisons to the treatments means</span></span>
<span id="cb10-10"><a href="meta-analysis.html#cb10-10"></a>   slimmer_PM_dat[slimmer_PM_dat<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>T_ref, <span class="st">&quot;yi_C&quot;</span>] &lt;-</span>
<span id="cb10-11"><a href="meta-analysis.html#cb10-11"></a><span class="st">      </span><span class="kw">mean</span>(slimmer_PM_dat[slimmer_PM_dat<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>T_ref <span class="op">&amp;</span></span>
<span id="cb10-12"><a href="meta-analysis.html#cb10-12"></a><span class="st">                             </span>slimmer_PM_dat<span class="op">$</span>fungicide_ai <span class="op">==</span><span class="st"> &quot;control&quot;</span>,</span>
<span id="cb10-13"><a href="meta-analysis.html#cb10-13"></a>                          <span class="st">&quot;grain_yield.t.ha&quot;</span>], <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span>
<span id="cb10-14"><a href="meta-analysis.html#cb10-14"></a>   </span>
<span id="cb10-15"><a href="meta-analysis.html#cb10-15"></a>}</span>
<span id="cb10-16"><a href="meta-analysis.html#cb10-16"></a><span class="co"># Calculate standardised mean difference</span></span>
<span id="cb10-17"><a href="meta-analysis.html#cb10-17"></a>slimmer_PM_dat<span class="op">$</span>grain_SMD &lt;-</span>
<span id="cb10-18"><a href="meta-analysis.html#cb10-18"></a><span class="st">   </span>(slimmer_PM_dat<span class="op">$</span>grain_yield.t.ha <span class="op">-</span><span class="st"> </span>slimmer_PM_dat<span class="op">$</span>yi_C) <span class="op">/</span><span class="st"> </span>slimmer_PM_dat<span class="op">$</span>pooledSD </span></code></pre></div>
<p>We can use the same sample variance with the standardised mean difference.
This is because if you add or subtract from a random variable, the variance does not change.</p>
<p>Let’s simplify our data.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="meta-analysis.html#cb11-1"></a>dat1 &lt;-</span>
<span id="cb11-2"><a href="meta-analysis.html#cb11-2"></a><span class="st">   </span>slimmer_PM_dat <span class="op">%&gt;%</span></span>
<span id="cb11-3"><a href="meta-analysis.html#cb11-3"></a><span class="st">   </span><span class="kw">filter</span>(fungicide_ai <span class="op">!=</span><span class="st"> &quot;control&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="co">#remove controls from the data</span></span>
<span id="cb11-4"><a href="meta-analysis.html#cb11-4"></a><span class="st">   </span><span class="kw">mutate</span>(<span class="dt">spray_management =</span></span>
<span id="cb11-5"><a href="meta-analysis.html#cb11-5"></a>             <span class="kw">factor</span>(</span>
<span id="cb11-6"><a href="meta-analysis.html#cb11-6"></a>                spray_management,</span>
<span id="cb11-7"><a href="meta-analysis.html#cb11-7"></a>                <span class="kw">c</span>(</span>
<span id="cb11-8"><a href="meta-analysis.html#cb11-8"></a>                   <span class="st">&quot;Early&quot;</span>,</span>
<span id="cb11-9"><a href="meta-analysis.html#cb11-9"></a>                   <span class="st">&quot;Recommended&quot;</span>,</span>
<span id="cb11-10"><a href="meta-analysis.html#cb11-10"></a>                   <span class="st">&quot;Recommended_plus&quot;</span>,</span>
<span id="cb11-11"><a href="meta-analysis.html#cb11-11"></a>                   <span class="st">&quot;Late&quot;</span>,</span>
<span id="cb11-12"><a href="meta-analysis.html#cb11-12"></a>                   <span class="st">&quot;Late_plus&quot;</span></span>
<span id="cb11-13"><a href="meta-analysis.html#cb11-13"></a>                )</span>
<span id="cb11-14"><a href="meta-analysis.html#cb11-14"></a>             ),</span>
<span id="cb11-15"><a href="meta-analysis.html#cb11-15"></a>          <span class="dt">D_pres =</span> </span>
<span id="cb11-16"><a href="meta-analysis.html#cb11-16"></a>             <span class="kw">factor</span>(D_pres,</span>
<span id="cb11-17"><a href="meta-analysis.html#cb11-17"></a>                    <span class="kw">c</span>(<span class="st">&quot;lowD&quot;</span>,</span>
<span id="cb11-18"><a href="meta-analysis.html#cb11-18"></a>                      <span class="st">&quot;highD&quot;</span>))) <span class="op">%&gt;%</span></span>
<span id="cb11-19"><a href="meta-analysis.html#cb11-19"></a><span class="st">   </span><span class="kw">select</span>(</span>
<span id="cb11-20"><a href="meta-analysis.html#cb11-20"></a>      trial,</span>
<span id="cb11-21"><a href="meta-analysis.html#cb11-21"></a>      trial_ref,</span>
<span id="cb11-22"><a href="meta-analysis.html#cb11-22"></a>      location,</span>
<span id="cb11-23"><a href="meta-analysis.html#cb11-23"></a>      year,</span>
<span id="cb11-24"><a href="meta-analysis.html#cb11-24"></a>      row_spacing,</span>
<span id="cb11-25"><a href="meta-analysis.html#cb11-25"></a>      host_genotype ,</span>
<span id="cb11-26"><a href="meta-analysis.html#cb11-26"></a>      spray_management,</span>
<span id="cb11-27"><a href="meta-analysis.html#cb11-27"></a>      fungicide_ai,</span>
<span id="cb11-28"><a href="meta-analysis.html#cb11-28"></a>      D_pres,</span>
<span id="cb11-29"><a href="meta-analysis.html#cb11-29"></a>      grain_yield.t.ha,</span>
<span id="cb11-30"><a href="meta-analysis.html#cb11-30"></a>      grain_SMD,</span>
<span id="cb11-31"><a href="meta-analysis.html#cb11-31"></a>      dose,</span>
<span id="cb11-32"><a href="meta-analysis.html#cb11-32"></a>      vi,</span>
<span id="cb11-33"><a href="meta-analysis.html#cb11-33"></a>      vi2</span>
<span id="cb11-34"><a href="meta-analysis.html#cb11-34"></a>      )</span></code></pre></div>
</div>
</div>
<div id="meta-analysis-1" class="section level2">
<h2><span class="header-section-number">5.2</span> Meta-analysis</h2>
<div id="metafor-package" class="section level3">
<h3><span class="header-section-number">5.2.1</span> metafor package</h3>
<p>Let’s inspect the data to determine if we need to transform the response variable.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="meta-analysis.html#cb12-1"></a><span class="kw">hist_usq</span>(dat1<span class="op">$</span>grain_yield.t.ha)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="meta-analysis.html#cb13-1"></a><span class="kw">hist_usq</span>(<span class="kw">log</span>(dat1<span class="op">$</span>grain_yield.t.ha))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-1-2.png" width="672" /></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="meta-analysis.html#cb14-1"></a><span class="kw">hist_usq</span>(<span class="kw">sqrt</span>(dat1<span class="op">$</span>grain_yield.t.ha))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-1-3.png" width="672" /></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="meta-analysis.html#cb15-1"></a><span class="kw">hist_usq</span>(dat1<span class="op">$</span>grain_SMD)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-1-4.png" width="672" /></p>
<p>Standardised mean differences have a bit of a long tail however this is not bad and transformations with log or square root will not work on negative values.</p>
<p>Let’s undertake the meta-analysis using the package <code>metafor</code>.
We are using the <code>spray_management</code> variable as a moderator and an interactive term to the <code>trial</code> random variable.<br />
Because we want to know the difference between all treatments and we have no reference treatment, we will remove the intercept.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="meta-analysis.html#cb16-1"></a>PM_mv &lt;-<span class="st"> </span><span class="kw">rma.mv</span>(</span>
<span id="cb16-2"><a href="meta-analysis.html#cb16-2"></a>   <span class="dt">yi =</span> grain_SMD,</span>
<span id="cb16-3"><a href="meta-analysis.html#cb16-3"></a>   vi,</span>
<span id="cb16-4"><a href="meta-analysis.html#cb16-4"></a>   <span class="dt">mods =</span> <span class="op">~</span><span class="st"> </span>spray_management <span class="op">-</span><span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb16-5"><a href="meta-analysis.html#cb16-5"></a>   <span class="dt">method =</span> <span class="st">&quot;ML&quot;</span>,</span>
<span id="cb16-6"><a href="meta-analysis.html#cb16-6"></a>   <span class="dt">random =</span> <span class="op">~</span><span class="st"> </span>spray_management <span class="op">|</span><span class="st"> </span>trial,</span>
<span id="cb16-7"><a href="meta-analysis.html#cb16-7"></a>   <span class="dt">struct =</span> <span class="st">&quot;UN&quot;</span>,</span>
<span id="cb16-8"><a href="meta-analysis.html#cb16-8"></a>   <span class="dt">data =</span> dat1</span>
<span id="cb16-9"><a href="meta-analysis.html#cb16-9"></a>)</span></code></pre></div>
<pre><code>## Warning: Some combinations of the levels of the inner factor never occurred.
## Corresponding rho value(s) fixed to 0.</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="meta-analysis.html#cb18-1"></a><span class="kw">summary</span>(PM_mv)</span></code></pre></div>
<pre><code>## 
## Multivariate Meta-Analysis Model (k = 116; method: ML)
## 
##    logLik   Deviance        AIC        BIC       AICc 
## -332.6369   913.7003   703.2738   755.5921   711.1905   
## 
## Variance Components:
## 
## outer factor: trial            (nlvls = 33)
## inner factor: spray_management (nlvls = 5)
## 
##             estim    sqrt  k.lvl  fixed             level 
## tau^2.1    0.8485  0.9212     13     no             Early 
## tau^2.2    1.2170  1.1032     27     no       Recommended 
## tau^2.3    2.8727  1.6949     40     no  Recommended_plus 
## tau^2.4    1.6346  1.2785     17     no              Late 
## tau^2.5    2.3998  1.5491     19     no         Late_plus 
## 
##                   rho.Erly  rho.Rcmm  rho.Rcm_  rho.Late  rho.Lt_p    Erly 
## Early                    1    0.8139    0.6429    0.6456    0.0000       - 
## Recommended         0.8139         1    0.8971    0.8959    0.9103      12 
## Recommended_plus    0.6429    0.8971         1    0.9372    0.9985      12 
## Late                0.6456    0.8959    0.9372         1    0.9538      12 
## Late_plus           0.0000    0.9103    0.9985    0.9538         1       0 
##                   Rcmm  Rcm_  Late  Lt_p 
## Early               no    no    no   yes 
## Recommended          -    no    no    no 
## Recommended_plus    24     -    no    no 
## Late                17    17     -    no 
## Late_plus            3     3     3     - 
## 
## Test for Residual Heterogeneity:
## QE(df = 111) = 47501.7646, p-val &lt; .0001
## 
## Test of Moderators (coefficients 1:5):
## QM(df = 5) = 24.4769, p-val = 0.0002
## 
## Model Results:
## 
##                                   estimate      se    zval    pval    ci.lb 
## spray_managementEarly               0.3142  0.2093  1.5011  0.1333  -0.0960 
## spray_managementRecommended         0.7806  0.1998  3.9078  &lt;.0001   0.3891 
## spray_managementRecommended_plus    1.1970  0.3015  3.9695  &lt;.0001   0.6060 
## spray_managementLate                0.8181  0.2397  3.4136  0.0006   0.3484 
## spray_managementLate_plus           1.2155  0.2773  4.3825  &lt;.0001   0.6719 
##                                    ci.ub 
## spray_managementEarly             0.7244      
## spray_managementRecommended       1.1721  *** 
## spray_managementRecommended_plus  1.7880  *** 
## spray_managementLate              1.2879  *** 
## spray_managementLate_plus         1.7591  *** 
## 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>In this result we can see that the <code>Early</code> treatment is not significantly different to zero, which in this case is the mean of the no spray control.
However the other treatments are significantly different to zero.
The <span class="math inline">\(Q_M\)</span> <a href="http://www.metafor-project.org/doku.php/tips:models_with_or_without_intercept?s%5B%5D=anova">omnibus test</a> of moderators, shows the moderators significantly influence the model (<span class="math inline">\(Q_M = 24.4769, df = 5, p = 0.0002\)</span>) and we can reject the null hypothesis (<span class="math inline">\(H_0 : \beta_1 = \beta_2 = \beta_3 =\beta_4 = 0\)</span>) that there is no difference between the moderators <span class="citation">(Viechtbauer <a href="#ref-Viechtbauer2010" role="doc-biblioref">2010</a>)</span>.
The analysis shows there is still a significant amount of residual heterogeneity (<span class="math inline">\(Q_E = 47501.76, df = 111, p &lt; 0.0001\)</span>) not captured by the spray management moderator indicating other possible moderators which might influence grain yield.</p>
<p>Let’s see if we can improve this model by including some other random effects and improving the random effect structure in the model.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="meta-analysis.html#cb20-1"></a>PM_mv_St &lt;-<span class="st"> </span><span class="kw">rma.mv</span>(</span>
<span id="cb20-2"><a href="meta-analysis.html#cb20-2"></a>   <span class="dt">yi =</span> grain_SMD,</span>
<span id="cb20-3"><a href="meta-analysis.html#cb20-3"></a>   vi, </span>
<span id="cb20-4"><a href="meta-analysis.html#cb20-4"></a>   <span class="dt">mods =</span> <span class="op">~</span><span class="st"> </span>spray_management,</span>
<span id="cb20-5"><a href="meta-analysis.html#cb20-5"></a>   <span class="dt">method =</span> <span class="st">&quot;ML&quot;</span>,</span>
<span id="cb20-6"><a href="meta-analysis.html#cb20-6"></a>   <span class="dt">random =</span> <span class="kw">list</span>(<span class="op">~</span><span class="st"> </span><span class="dv">1</span><span class="op">|</span>trial),</span>
<span id="cb20-7"><a href="meta-analysis.html#cb20-7"></a>   <span class="dt">data =</span> dat1</span>
<span id="cb20-8"><a href="meta-analysis.html#cb20-8"></a>)</span>
<span id="cb20-9"><a href="meta-analysis.html#cb20-9"></a></span>
<span id="cb20-10"><a href="meta-analysis.html#cb20-10"></a></span>
<span id="cb20-11"><a href="meta-analysis.html#cb20-11"></a>PM_mv_St1 &lt;-<span class="st"> </span><span class="kw">rma.mv</span>(</span>
<span id="cb20-12"><a href="meta-analysis.html#cb20-12"></a>   <span class="dt">yi =</span> grain_SMD,</span>
<span id="cb20-13"><a href="meta-analysis.html#cb20-13"></a>   vi, </span>
<span id="cb20-14"><a href="meta-analysis.html#cb20-14"></a>   <span class="dt">mods =</span> <span class="op">~</span><span class="st"> </span>spray_management,</span>
<span id="cb20-15"><a href="meta-analysis.html#cb20-15"></a>   <span class="dt">method =</span> <span class="st">&quot;ML&quot;</span>,</span>
<span id="cb20-16"><a href="meta-analysis.html#cb20-16"></a>   <span class="dt">random =</span> <span class="kw">list</span>(<span class="op">~</span><span class="st"> </span><span class="dv">1</span><span class="op">|</span>location<span class="op">/</span>year<span class="op">/</span>trial_ref<span class="op">/</span>dose<span class="op">/</span>host_genotype<span class="op">/</span><span class="kw">factor</span>(row_spacing)<span class="op">/</span>spray_management),</span>
<span id="cb20-17"><a href="meta-analysis.html#cb20-17"></a>   <span class="dt">data =</span> dat1</span>
<span id="cb20-18"><a href="meta-analysis.html#cb20-18"></a>)</span>
<span id="cb20-19"><a href="meta-analysis.html#cb20-19"></a></span>
<span id="cb20-20"><a href="meta-analysis.html#cb20-20"></a></span>
<span id="cb20-21"><a href="meta-analysis.html#cb20-21"></a><span class="kw">AIC</span>(PM_mv) <span class="co"># Printing the AIC of the model helps differentiate the models in the anova output</span></span></code></pre></div>
<pre><code>## [1] 703.2738</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="meta-analysis.html#cb22-1"></a><span class="kw">anova</span>(PM_mv, PM_mv_St1) <span class="co"># PM_mv is the better model</span></span></code></pre></div>
<pre><code>## 
##         df      AIC      BIC     AICc    logLik     LRT   pval         QE 
## Full    19 703.2738 755.5921 711.1905 -332.6369                47501.7646 
## Reduced 12 719.8492 752.8923 722.8783 -347.9246 30.5753 &lt;.0001 47501.7646</code></pre>
<p>The simpler <code>PM_mv_St</code> model explains significantly less variation as the more complicated model <code>PM_mv</code>.
So we will keep the original model <code>PM_mv</code>.</p>
<p>The first table in this output shows the tau^2 (variance) of each random effects and the number of occurrences for each treatment in the analysis.
The second table is in two parts(left and right).
The left part, rho, is the correlation of variation between the specified treatments.
All comparisons were acceptable except for a comparison between <code>Early</code> and <code>Late_plus</code>, <code>0.000</code> rho. <code>Early</code> and <code>Late_plus</code> treatments never occurred within the same trial which is indicated by the right side of the table (hence the warning).</p>
<p>The fixed effects, in the last table, showed that yields in single early spray treatments are not significantly different from zero, or the no spray control.</p>
</div>
<div id="profile-plots" class="section level3">
<h3><span class="header-section-number">5.2.2</span> Profile plots</h3>
<p>Let’s inspect the profile plots to ensure the model is not over-fitted.
We expect to see the estimate align with the peak of the curve.
Also that the shape of the line is a curve.
Caution! this will take some time to run.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="meta-analysis.html#cb24-1"></a><span class="kw">profile</span>(PM_mv, <span class="dt">tau2 =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/profile_plots-1.png" width="672" /></p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="meta-analysis.html#cb25-1"></a><span class="kw">profile</span>(PM_mv, <span class="dt">tau2 =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/profile_plots-2.png" width="672" /></p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="meta-analysis.html#cb26-1"></a><span class="kw">profile</span>(PM_mv, <span class="dt">tau2 =</span> <span class="dv">3</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/profile_plots-3.png" width="672" /></p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="meta-analysis.html#cb27-1"></a><span class="kw">profile</span>(PM_mv, <span class="dt">tau2 =</span> <span class="dv">4</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/profile_plots-4.png" width="672" /></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="meta-analysis.html#cb28-1"></a><span class="kw">profile</span>(PM_mv, <span class="dt">tau2 =</span> <span class="dv">5</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/profile_plots-5.png" width="672" /></p>
<hr />
</div>
<div id="metafor-comparisons" class="section level3">
<h3><span class="header-section-number">5.2.3</span> Metafor comparisons</h3>
<p>To make it easier to compare each of the treatments we can compute the meta-analysis contrasts.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="meta-analysis.html#cb29-1"></a>meta_cont &lt;-<span class="st"> </span><span class="kw">anova</span>(PM_mv, <span class="dt">L =</span> <span class="kw">rbind</span>(</span>
<span id="cb29-2"><a href="meta-analysis.html#cb29-2"></a>   <span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb29-3"><a href="meta-analysis.html#cb29-3"></a>   <span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb29-4"><a href="meta-analysis.html#cb29-4"></a>   <span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb29-5"><a href="meta-analysis.html#cb29-5"></a>   <span class="kw">c</span>(<span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb29-6"><a href="meta-analysis.html#cb29-6"></a>   <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">-1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb29-7"><a href="meta-analysis.html#cb29-7"></a>   <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">-1</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb29-8"><a href="meta-analysis.html#cb29-8"></a>   <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">-1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb29-9"><a href="meta-analysis.html#cb29-9"></a>   <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">-1</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb29-10"><a href="meta-analysis.html#cb29-10"></a>   <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">-1</span>, <span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb29-11"><a href="meta-analysis.html#cb29-11"></a>   <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">-1</span>, <span class="dv">1</span>)</span>
<span id="cb29-12"><a href="meta-analysis.html#cb29-12"></a>))</span>
<span id="cb29-13"><a href="meta-analysis.html#cb29-13"></a></span>
<span id="cb29-14"><a href="meta-analysis.html#cb29-14"></a>change_labels &lt;-<span class="st"> </span><span class="cf">function</span>(x1) {</span>
<span id="cb29-15"><a href="meta-analysis.html#cb29-15"></a>   x1 &lt;-<span class="st"> </span><span class="kw">gsub</span>(<span class="dt">pattern =</span> <span class="st">&quot;spray_management&quot;</span>,</span>
<span id="cb29-16"><a href="meta-analysis.html#cb29-16"></a>              <span class="dt">replacement =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb29-17"><a href="meta-analysis.html#cb29-17"></a>              <span class="dt">x =</span> x1)</span>
<span id="cb29-18"><a href="meta-analysis.html#cb29-18"></a>   x1</span>
<span id="cb29-19"><a href="meta-analysis.html#cb29-19"></a>}</span>
<span id="cb29-20"><a href="meta-analysis.html#cb29-20"></a></span>
<span id="cb29-21"><a href="meta-analysis.html#cb29-21"></a><span class="kw">source</span>(<span class="st">&quot;R/p_star.R&quot;</span>)</span>
<span id="cb29-22"><a href="meta-analysis.html#cb29-22"></a></span>
<span id="cb29-23"><a href="meta-analysis.html#cb29-23"></a><span class="kw">data.frame</span>(</span>
<span id="cb29-24"><a href="meta-analysis.html#cb29-24"></a>   <span class="dt">contrasts =</span> <span class="kw">change_labels</span>(meta_cont<span class="op">$</span>hyp[, <span class="dv">1</span>]),</span>
<span id="cb29-25"><a href="meta-analysis.html#cb29-25"></a>   <span class="dt">estimates =</span> meta_cont<span class="op">$</span>Lb,</span>
<span id="cb29-26"><a href="meta-analysis.html#cb29-26"></a>   <span class="dt">se =</span> meta_cont<span class="op">$</span>se,</span>
<span id="cb29-27"><a href="meta-analysis.html#cb29-27"></a>   <span class="dt">z_val =</span> meta_cont<span class="op">$</span>zval,</span>
<span id="cb29-28"><a href="meta-analysis.html#cb29-28"></a>   <span class="dt">pval =</span> meta_cont<span class="op">$</span>pval,</span>
<span id="cb29-29"><a href="meta-analysis.html#cb29-29"></a>   <span class="dt">VisP =</span> <span class="kw">p_star</span>(meta_cont<span class="op">$</span>pval)</span>
<span id="cb29-30"><a href="meta-analysis.html#cb29-30"></a>)</span></code></pre></div>
<pre><code>##                              contrasts   estimates         se      z_val
## 1             -Early + Recommended = 0  0.46641849 0.17959360  2.5970774
## 2        -Early + Recommended_plus = 0  0.88279371 0.27576460  3.2012583
## 3                    -Early + Late = 0  0.50396169 0.23848955  2.1131396
## 4               -Early + Late_plus = 0  0.90130002 0.25716136  3.5048035
## 5  -Recommended + Recommended_plus = 0  0.41637522 0.16828322  2.4742527
## 6              -Recommended + Late = 0  0.03754321 0.13986869  0.2684175
## 7         -Recommended + Late_plus = 0  0.43488153 0.14843610  2.9297558
## 8         -Recommended_plus + Late = 0 -0.37883201 0.14933397 -2.5368108
## 9    -Recommended_plus + Late_plus = 0  0.01850631 0.06458647  0.2865354
## 10               -Late + Late_plus = 0  0.39733832 0.12526511  3.1719792
##            pval VisP
## 1  0.0094020739   **
## 2  0.0013682882   **
## 3  0.0345888245    *
## 4  0.0004569444  ***
## 5  0.0133515210    *
## 6  0.7883779546     
## 7  0.0033922844   **
## 8  0.0111867408    *
## 9  0.7744680870     
## 10 0.0015140386   **</code></pre>
<p>Results show with the exclusion of the no spray control, <code>Early</code> applications are significantly worse than all other treatments leading to lower yield estimates.
<code>Late_plus</code> is estimated as saving the most yield compared and is significantly higher than all other treatments except <code>recommended_plus</code>.
Let’s view these comparisons in a plot.</p>
<p>First we will format the results into a data frame.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="meta-analysis.html#cb31-1"></a>results_AI &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="kw">cbind</span>(PM_mv<span class="op">$</span>b,</span>
<span id="cb31-2"><a href="meta-analysis.html#cb31-2"></a>                               PM_mv<span class="op">$</span>ci.lb,</span>
<span id="cb31-3"><a href="meta-analysis.html#cb31-3"></a>                               PM_mv<span class="op">$</span>ci.ub))</span>
<span id="cb31-4"><a href="meta-analysis.html#cb31-4"></a></span>
<span id="cb31-5"><a href="meta-analysis.html#cb31-5"></a>efficacy &lt;-<span class="st"> </span><span class="kw">tbl_df</span>(results_AI)</span>
<span id="cb31-6"><a href="meta-analysis.html#cb31-6"></a>efficacy<span class="op">$</span>Treatment &lt;-</span>
<span id="cb31-7"><a href="meta-analysis.html#cb31-7"></a><span class="st">   </span><span class="kw">factor</span>(<span class="kw">c</span>(</span>
<span id="cb31-8"><a href="meta-analysis.html#cb31-8"></a>      <span class="st">&quot;Early&quot;</span>,</span>
<span id="cb31-9"><a href="meta-analysis.html#cb31-9"></a>      <span class="st">&quot;Recommended&quot;</span>,</span>
<span id="cb31-10"><a href="meta-analysis.html#cb31-10"></a>      <span class="st">&quot;Recommended_plus&quot;</span>,</span>
<span id="cb31-11"><a href="meta-analysis.html#cb31-11"></a>      <span class="st">&quot;Late&quot;</span>,</span>
<span id="cb31-12"><a href="meta-analysis.html#cb31-12"></a>      <span class="st">&quot;Late_plus&quot;</span></span>
<span id="cb31-13"><a href="meta-analysis.html#cb31-13"></a>   ))</span>
<span id="cb31-14"><a href="meta-analysis.html#cb31-14"></a></span>
<span id="cb31-15"><a href="meta-analysis.html#cb31-15"></a>efficacy<span class="op">$</span>se &lt;-<span class="st"> </span>PM_mv<span class="op">$</span>se</span>
<span id="cb31-16"><a href="meta-analysis.html#cb31-16"></a><span class="kw">colnames</span>(efficacy) &lt;-</span>
<span id="cb31-17"><a href="meta-analysis.html#cb31-17"></a><span class="st">   </span><span class="kw">c</span>(<span class="st">&quot;Mean&quot;</span>, <span class="st">&quot;CIs_lower&quot;</span>, <span class="st">&quot;CI_upper&quot;</span>, <span class="st">&quot;Treatment&quot;</span>, <span class="st">&quot;SE&quot;</span>)</span>
<span id="cb31-18"><a href="meta-analysis.html#cb31-18"></a>efficacy</span></code></pre></div>
<pre><code>## # A tibble: 5 x 5
##    Mean CIs_lower CI_upper Treatment           SE
##   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;fct&gt;            &lt;dbl&gt;
## 1 0.314   -0.0960    0.724 Early            0.209
## 2 0.781    0.389     1.17  Recommended      0.200
## 3 1.20     0.606     1.79  Recommended_plus 0.302
## 4 0.818    0.348     1.29  Late             0.240
## 5 1.22     0.672     1.76  Late_plus        0.277</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="meta-analysis.html#cb33-1"></a>efficacy <span class="op">%&gt;%</span></span>
<span id="cb33-2"><a href="meta-analysis.html#cb33-2"></a><span class="st">   </span><span class="kw">mutate</span>(<span class="dt">Treatment =</span> <span class="kw">factor</span>(Treatment, <span class="dt">levels =</span> <span class="kw">rev</span>(<span class="kw">c</span>(<span class="st">&quot;Early&quot;</span>, <span class="st">&quot;Recommended&quot;</span>, <span class="st">&quot;Recommended_plus&quot;</span>,<span class="st">&quot;Late&quot;</span>,<span class="st">&quot;Late_plus&quot;</span>))))<span class="op">%&gt;%</span></span>
<span id="cb33-3"><a href="meta-analysis.html#cb33-3"></a><span class="st">   </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(Treatment, Mean)) <span class="op">+</span></span>
<span id="cb33-4"><a href="meta-analysis.html#cb33-4"></a><span class="st">   </span><span class="kw">geom_hline</span>(</span>
<span id="cb33-5"><a href="meta-analysis.html#cb33-5"></a>      <span class="dt">yintercept =</span> <span class="kw">seq</span>(<span class="op">-</span><span class="fl">0.4</span>, <span class="fl">1.8</span>, <span class="dt">by =</span> <span class="fl">0.2</span>),</span>
<span id="cb33-6"><a href="meta-analysis.html#cb33-6"></a>      <span class="dt">color =</span> <span class="kw">usq_cols</span>(<span class="st">&quot;usq charcoal&quot;</span>),</span>
<span id="cb33-7"><a href="meta-analysis.html#cb33-7"></a>      <span class="dt">linetype =</span> <span class="dv">3</span></span>
<span id="cb33-8"><a href="meta-analysis.html#cb33-8"></a>   ) <span class="op">+</span></span>
<span id="cb33-9"><a href="meta-analysis.html#cb33-9"></a><span class="st">   </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>)<span class="op">+</span></span>
<span id="cb33-10"><a href="meta-analysis.html#cb33-10"></a><span class="st">   </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">size =</span> <span class="dv">1</span> <span class="op">/</span><span class="st"> </span>SE), <span class="dt">shape =</span> <span class="dv">15</span>) <span class="op">+</span></span>
<span id="cb33-11"><a href="meta-analysis.html#cb33-11"></a><span class="st">   </span><span class="kw">geom_linerange</span>(<span class="kw">aes</span>(<span class="dt">ymin =</span> CIs_lower, <span class="dt">ymax =</span> CI_upper)) <span class="op">+</span></span>
<span id="cb33-12"><a href="meta-analysis.html#cb33-12"></a><span class="st">   </span><span class="kw">coord_flip</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/metafor_plot-1.png" width="672" /></p>
<p>Let’s look at how well each of the number treatments compare to each other.</p>
</div>
<div id="disease-pressure-effect" class="section level3">
<h3><span class="header-section-number">5.2.4</span> Disease pressure effect</h3>
<p>We also want to know if disease pressure exerts an effect on the desicion for spray control.
Above we can see spraying at the first sign of powdery mildew or with in 7 - 13 days after first sign is effective at mitigating yield loss.
Does this change between years of low and high disease pressure.</p>
<p>We will add the intercept back into this model for ease of interpretation.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="meta-analysis.html#cb34-1"></a>PM_mv_Dp &lt;-<span class="st"> </span><span class="kw">rma.mv</span>(</span>
<span id="cb34-2"><a href="meta-analysis.html#cb34-2"></a>   <span class="dt">yi =</span> grain_SMD,</span>
<span id="cb34-3"><a href="meta-analysis.html#cb34-3"></a>   vi,</span>
<span id="cb34-4"><a href="meta-analysis.html#cb34-4"></a>   <span class="dt">mods =</span> <span class="op">~</span><span class="st"> </span>spray_management <span class="op">*</span>D_pres,</span>
<span id="cb34-5"><a href="meta-analysis.html#cb34-5"></a>   <span class="dt">method =</span> <span class="st">&quot;ML&quot;</span>,</span>
<span id="cb34-6"><a href="meta-analysis.html#cb34-6"></a>   <span class="dt">random =</span> <span class="op">~</span><span class="st"> </span>spray_management <span class="op">|</span><span class="st"> </span>trial,</span>
<span id="cb34-7"><a href="meta-analysis.html#cb34-7"></a>   <span class="dt">struct =</span> <span class="st">&quot;UN&quot;</span>,</span>
<span id="cb34-8"><a href="meta-analysis.html#cb34-8"></a>   <span class="dt">data =</span> dat1</span>
<span id="cb34-9"><a href="meta-analysis.html#cb34-9"></a>)</span></code></pre></div>
<pre><code>## Warning: Some combinations of the levels of the inner factor never occurred.
## Corresponding rho value(s) fixed to 0.</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="meta-analysis.html#cb36-1"></a><span class="kw">summary</span>(PM_mv_Dp)</span></code></pre></div>
<pre><code>## 
## Multivariate Meta-Analysis Model (k = 116; method: ML)
## 
##    logLik   Deviance        AIC        BIC       AICc 
## -329.2760   906.9785   706.5521   772.6382   719.7389   
## 
## Variance Components:
## 
## outer factor: trial            (nlvls = 33)
## inner factor: spray_management (nlvls = 5)
## 
##             estim    sqrt  k.lvl  fixed             level 
## tau^2.1    0.5243  0.7241     13     no             Early 
## tau^2.2    1.1356  1.0656     27     no       Recommended 
## tau^2.3    2.7768  1.6664     40     no  Recommended_plus 
## tau^2.4    1.5102  1.2289     17     no              Late 
## tau^2.5    1.9744  1.4052     19     no         Late_plus 
## 
##                   rho.Erly  rho.Rcmm  rho.Rcm_  rho.Late  rho.Lt_p    Erly 
## Early                    1    0.6965    0.5020    0.4831    0.0000       - 
## Recommended         0.6965         1    0.8951    0.8961    0.9419      12 
## Recommended_plus    0.5020    0.8951         1    0.9322    0.9768      12 
## Late                0.4831    0.8961    0.9322         1    0.9822      12 
## Late_plus           0.0000    0.9419    0.9768    0.9822         1       0 
##                   Rcmm  Rcm_  Late  Lt_p 
## Early               no    no    no   yes 
## Recommended          -    no    no    no 
## Recommended_plus    24     -    no    no 
## Late                17    17     -    no 
## Late_plus            3     3     3     - 
## 
## Test for Residual Heterogeneity:
## QE(df = 106) = 22163.7723, p-val &lt; .0001
## 
## Test of Moderators (coefficients 2:10):
## QM(df = 9) = 70.8016, p-val &lt; .0001
## 
## Model Results:
## 
##                                               estimate      se     zval    pval 
## intrcpt                                         1.8610  0.7305   2.5476  0.0108 
## spray_managementRecommended                    -1.0497  0.8363  -1.2553  0.2094 
## spray_managementRecommended_plus               -0.4434  0.9840  -0.4505  0.6523 
## spray_managementLate                           -0.8317  0.8820  -0.9430  0.3457 
## spray_managementLate_plus                      -0.2667  0.9140  -0.2918  0.7704 
## D_preshighD                                    -1.6463  0.7552  -2.1800  0.0293 
## spray_managementRecommended:D_preshighD         1.6013  0.8595   1.8630  0.0625 
## spray_managementRecommended_plus:D_preshighD    1.3903  1.0351   1.3431  0.1792 
## spray_managementLate:D_preshighD                1.3881  0.9229   1.5041  0.1326 
## spray_managementLate_plus:D_preshighD           0.8981  0.9588   0.9367  0.3489 
##                                                 ci.lb    ci.ub 
## intrcpt                                        0.4292   3.2927  * 
## spray_managementRecommended                   -2.6888   0.5893    
## spray_managementRecommended_plus              -2.3720   1.4853    
## spray_managementLate                          -2.5603   0.8970    
## spray_managementLate_plus                     -2.0582   1.5247    
## D_preshighD                                   -3.1265  -0.1662  * 
## spray_managementRecommended:D_preshighD       -0.0833   3.2860  . 
## spray_managementRecommended_plus:D_preshighD  -0.6385   3.4192    
## spray_managementLate:D_preshighD              -0.4207   3.1970    
## spray_managementLate_plus:D_preshighD         -0.9810   2.7772    
## 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>These results show that the spray management variable we tested are not significantly better or worse between the two levels of disease pressure.
It also shows that in trials with high disease pressure all treatments produced lower standardised mean differences.
Indicating that fungicide treatments were less effective at mitigating yeild loss in seasons which developed heavier infestations.<br />
Finally lets compare the disease pressure model to the orignal model to see which one fits better.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="meta-analysis.html#cb38-1"></a><span class="kw">anova</span>(PM_mv, PM_mv_Dp)</span></code></pre></div>
<pre><code>## 
##         df      AIC      BIC     AICc    logLik    LRT   pval         QE 
## Full    24 706.5521 772.6382 719.7389 -329.2760               22163.7723 
## Reduced 19 703.2738 755.5921 711.1905 -332.6369 6.7218 0.2422 47501.7646</code></pre>
<p>No significant difference which informs us to use the origninal model <code>PM_mv</code> which is the simplest.</p>
<hr />
<p>We can use the netmeta package to give a graphical representation of the pairwise comparisons.</p>
</div>
<div id="netmeta-package" class="section level3">
<h3><span class="header-section-number">5.2.5</span> netmeta package</h3>
<p>Let’s analyse the data again using a different statistical approach to see if our outcome with the <code>metafor</code> package was robust.
The <code>netmeta</code> package uses a frequentist approach to the analysis and focuses on the pairwise comparisons between treatments.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="meta-analysis.html#cb40-1"></a>datPM3 &lt;-<span class="st"> </span>slimmer_PM_dat <span class="op">%&gt;%</span></span>
<span id="cb40-2"><a href="meta-analysis.html#cb40-2"></a><span class="st">   </span><span class="kw">group_by</span>(trial, spray_management, n) <span class="op">%&gt;%</span></span>
<span id="cb40-3"><a href="meta-analysis.html#cb40-3"></a><span class="st">   </span><span class="kw">summarize</span>(<span class="dt">yi_mean =</span> <span class="kw">mean</span>(grain_SMD),</span>
<span id="cb40-4"><a href="meta-analysis.html#cb40-4"></a>             <span class="dt">vi_mean =</span> <span class="kw">mean</span>(yield_error)) <span class="op">%&gt;%</span></span>
<span id="cb40-5"><a href="meta-analysis.html#cb40-5"></a><span class="st">   </span><span class="kw">ungroup</span>()</span>
<span id="cb40-6"><a href="meta-analysis.html#cb40-6"></a></span>
<span id="cb40-7"><a href="meta-analysis.html#cb40-7"></a>PM_con &lt;-<span class="st"> </span><span class="kw">pairwise</span>(</span>
<span id="cb40-8"><a href="meta-analysis.html#cb40-8"></a>   <span class="dt">treat =</span> spray_management,</span>
<span id="cb40-9"><a href="meta-analysis.html#cb40-9"></a>   <span class="dt">n =</span> n,</span>
<span id="cb40-10"><a href="meta-analysis.html#cb40-10"></a>   <span class="dt">mean =</span> yi_mean,</span>
<span id="cb40-11"><a href="meta-analysis.html#cb40-11"></a>   <span class="dt">sd =</span> <span class="kw">sqrt</span>(vi_mean),</span>
<span id="cb40-12"><a href="meta-analysis.html#cb40-12"></a>   <span class="dt">studlab =</span> trial,</span>
<span id="cb40-13"><a href="meta-analysis.html#cb40-13"></a>   <span class="dt">data =</span> datPM3,</span>
<span id="cb40-14"><a href="meta-analysis.html#cb40-14"></a>   <span class="dt">sm =</span> <span class="st">&quot;MD&quot;</span></span>
<span id="cb40-15"><a href="meta-analysis.html#cb40-15"></a>)</span>
<span id="cb40-16"><a href="meta-analysis.html#cb40-16"></a></span>
<span id="cb40-17"><a href="meta-analysis.html#cb40-17"></a>net_con &lt;-<span class="st"> </span><span class="kw">netmeta</span>(TE,</span>
<span id="cb40-18"><a href="meta-analysis.html#cb40-18"></a>                   seTE,</span>
<span id="cb40-19"><a href="meta-analysis.html#cb40-19"></a>                   treat1,</span>
<span id="cb40-20"><a href="meta-analysis.html#cb40-20"></a>                   treat2,</span>
<span id="cb40-21"><a href="meta-analysis.html#cb40-21"></a>                   studlab,</span>
<span id="cb40-22"><a href="meta-analysis.html#cb40-22"></a>                   <span class="dt">data =</span> PM_con,</span>
<span id="cb40-23"><a href="meta-analysis.html#cb40-23"></a>                   <span class="dt">sm =</span> <span class="st">&quot;MD&quot;</span>)</span>
<span id="cb40-24"><a href="meta-analysis.html#cb40-24"></a></span>
<span id="cb40-25"><a href="meta-analysis.html#cb40-25"></a><span class="kw">summary</span>(net_con)</span></code></pre></div>
<pre><code>## Number of studies: k = 30
## Number of treatments: n = 6
## Number of pairwise comparisons: m = 163
## Number of designs: d = 9
## 
## Fixed effects model
## 
## Treatment estimate (sm = &#39;MD&#39;):
##                  control   Early    Late Late_plus Recommended Recommended_plus
## control                . -0.0697 -0.3927   -1.3904     -0.5792          -1.0015
## Early             0.0697       . -0.3230   -1.3208     -0.5095          -0.9318
## Late              0.3927  0.3230       .   -0.9977     -0.1865          -0.6088
## Late_plus         1.3904  1.3208  0.9977         .      0.8113           0.3889
## Recommended       0.5792  0.5095  0.1865   -0.8113           .          -0.4223
## Recommended_plus  1.0015  0.9318  0.6088   -0.3889      0.4223                .
## 
## Lower 95%-confidence limit:
##                  control   Early    Late Late_plus Recommended Recommended_plus
## control                . -0.1087 -0.4278   -1.4420     -0.6112          -1.0403
## Early             0.0307       . -0.3611   -1.3775     -0.5358          -0.9737
## Late              0.3576  0.2850       .   -1.0489     -0.2173          -0.6458
## Late_plus         1.3388  1.2640  0.9465         .      0.7593           0.3363
## Recommended       0.5472  0.4832  0.1557   -0.8632           .          -0.4575
## Recommended_plus  0.9627  0.8900  0.5718   -0.4416      0.3872                .
## 
## Upper 95%-confidence limit:
##                  control   Early    Late Late_plus Recommended Recommended_plus
## control                . -0.0307 -0.3576   -1.3388     -0.5472          -0.9627
## Early             0.1087       . -0.2850   -1.2640     -0.4832          -0.8900
## Late              0.4278  0.3611       .   -0.9465     -0.1557          -0.5718
## Late_plus         1.4420  1.3775  1.0489         .      0.8632           0.4416
## Recommended       0.6112  0.5358  0.2173   -0.7593           .          -0.3872
## Recommended_plus  1.0403  0.9737  0.6458   -0.3363      0.4575                .
## 
## Random effects model
## 
## Treatment estimate (sm = &#39;MD&#39;):
##                  control   Early    Late Late_plus Recommended Recommended_plus
## control                . -0.3464 -0.7404   -1.2386     -0.6412          -1.0911
## Early             0.3464       . -0.3940   -0.8922     -0.2948          -0.7446
## Late              0.7404  0.3940       .   -0.4982      0.0992          -0.3507
## Late_plus         1.2386  0.8922  0.4982         .      0.5975           0.1476
## Recommended       0.6412  0.2948 -0.0992   -0.5975           .          -0.4499
## Recommended_plus  1.0911  0.7446  0.3507   -0.1476      0.4499                .
## 
## Lower 95%-confidence limit:
##                  control   Early    Late Late_plus Recommended Recommended_plus
## control                . -0.9832 -1.3142   -2.0980     -1.1365          -1.6026
## Early            -0.2903       . -1.0184   -1.8897     -0.8917          -1.3448
## Late              0.1666 -0.2304       .   -1.4310     -0.4327          -0.8864
## Late_plus         0.3793 -0.1053 -0.4345         .     -0.3056          -0.7606
## Recommended       0.1458 -0.3022 -0.6312   -1.5005           .          -0.9181
## Recommended_plus  0.5795  0.1444 -0.1851   -1.0557     -0.0184                .
## 
## Upper 95%-confidence limit:
##                  control  Early    Late Late_plus Recommended Recommended_plus
## control                . 0.2903 -0.1666   -0.3793     -0.1458          -0.5795
## Early             0.9832      .  0.2304    0.1053      0.3022          -0.1444
## Late              1.3142 1.0184       .    0.4345      0.6312           0.1851
## Late_plus         2.0980 1.8897  1.4310         .      1.5005           1.0557
## Recommended       1.1365 0.8917  0.4327    0.3056           .           0.0184
## Recommended_plus  1.6026 1.3448  0.8864    0.7606      0.9181                .
## 
## Quantifying heterogeneity / inconsistency:
## tau^2 = 1.3743; tau = 1.1723; I^2 = 99.5% [99.4%; 99.5%]
## 
## Tests of heterogeneity (within designs) and inconsistency (between designs):
##                        Q d.f. p-value
## Total           13705.55   74       0
## Within designs   7488.00   59       0
## Between designs  6217.55   15       0</code></pre>
<p>Now let’s visualise this as a forest plot.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="meta-analysis.html#cb42-1"></a><span class="kw">forest</span>(</span>
<span id="cb42-2"><a href="meta-analysis.html#cb42-2"></a>   net_con,</span>
<span id="cb42-3"><a href="meta-analysis.html#cb42-3"></a>   <span class="dt">reference.group =</span> <span class="dv">5</span>,</span>
<span id="cb42-4"><a href="meta-analysis.html#cb42-4"></a>   <span class="dt">rightcols =</span> <span class="kw">c</span>(<span class="st">&quot;effect&quot;</span>, <span class="st">&quot;ci&quot;</span>, <span class="st">&quot;Pscore&quot;</span>),</span>
<span id="cb42-5"><a href="meta-analysis.html#cb42-5"></a>   <span class="dt">rightlabs =</span> <span class="st">&quot;P-Score&quot;</span>,</span>
<span id="cb42-6"><a href="meta-analysis.html#cb42-6"></a>   <span class="dt">small.values =</span> <span class="st">&quot;bad&quot;</span></span>
<span id="cb42-7"><a href="meta-analysis.html#cb42-7"></a>)</span></code></pre></div>
<p><img src="_main_files/figure-html/netmeta-forest-1.png" width="672" /></p>
<p>The <code>netmeta</code> analysis suggests the spray schedule commencing early are no different to any other treatment including the no spray control.
It estimates the mean is very similar to the recommended treatments.
The recommended plus and late_plus treatments show higher mean estimates, however are not significantly different from the early estimate.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="meta-analysis.html#cb43-1"></a><span class="kw">netgraph</span>(</span>
<span id="cb43-2"><a href="meta-analysis.html#cb43-2"></a>   net_con,</span>
<span id="cb43-3"><a href="meta-analysis.html#cb43-3"></a>   <span class="dt">plastic =</span> <span class="ot">FALSE</span>,</span>
<span id="cb43-4"><a href="meta-analysis.html#cb43-4"></a>   <span class="dt">col =</span> <span class="kw">usq_cols</span>(<span class="st">&quot;support orange&quot;</span>),</span>
<span id="cb43-5"><a href="meta-analysis.html#cb43-5"></a>   <span class="dt">thickness =</span>  <span class="st">&quot;number.of.studies&quot;</span>,</span>
<span id="cb43-6"><a href="meta-analysis.html#cb43-6"></a>   <span class="dt">points =</span> <span class="ot">FALSE</span>,</span>
<span id="cb43-7"><a href="meta-analysis.html#cb43-7"></a>   <span class="dt">col.points =</span> <span class="kw">usq_cols</span>(<span class="st">&quot;usq charcoal&quot;</span>),</span>
<span id="cb43-8"><a href="meta-analysis.html#cb43-8"></a>   <span class="dt">cex.points =</span> <span class="dv">1</span>,</span>
<span id="cb43-9"><a href="meta-analysis.html#cb43-9"></a>   <span class="dt">number.of.studies =</span> <span class="ot">TRUE</span>,</span>
<span id="cb43-10"><a href="meta-analysis.html#cb43-10"></a>   <span class="dt">cex.number.of.studies =</span> <span class="dv">1</span>,</span>
<span id="cb43-11"><a href="meta-analysis.html#cb43-11"></a>   <span class="dt">col.number.of.studies =</span> <span class="st">&quot;black&quot;</span>,</span>
<span id="cb43-12"><a href="meta-analysis.html#cb43-12"></a>   <span class="dt">bg.number.of.studies =</span> <span class="kw">usq_cols</span>(<span class="st">&quot;support orange&quot;</span>),</span>
<span id="cb43-13"><a href="meta-analysis.html#cb43-13"></a>   <span class="dt">multiarm =</span> <span class="ot">FALSE</span>,</span>
<span id="cb43-14"><a href="meta-analysis.html#cb43-14"></a>   <span class="dt">col.multiarm =</span> <span class="kw">usq_cols</span>(<span class="st">&quot;support turquiose&quot;</span>),</span>
<span id="cb43-15"><a href="meta-analysis.html#cb43-15"></a>   <span class="dt">pos.number.of.studies =</span> <span class="fl">0.5</span></span>
<span id="cb43-16"><a href="meta-analysis.html#cb43-16"></a>)</span></code></pre></div>
<p><img src="_main_files/figure-html/netgraphGW-1.png" width="672" /></p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="meta-analysis.html#cb44-1"></a><span class="kw">netleague</span>(net_con)</span></code></pre></div>
<pre><code>## League table (fixed effects model):
##                                                       
##                     control -0.8515 [-0.9261; -0.7770]
##  -0.0697 [-0.1087; -0.0307]                      Early
##  -0.3927 [-0.4278; -0.3576] -0.3230 [-0.3611; -0.2850]
##  -1.3904 [-1.4420; -1.3388] -1.3208 [-1.3775; -1.2640]
##  -0.5792 [-0.6112; -0.5472] -0.5095 [-0.5358; -0.4832]
##  -1.0015 [-1.0403; -0.9627] -0.9318 [-0.9737; -0.8900]
##                                                       
##  -0.4574 [-0.5014; -0.4134] -2.1195 [-2.1913; -2.0476]
##  -0.5933 [-0.6661; -0.5206]                          .
##                        Late -0.7501 [-0.8209; -0.6793]
##  -0.9977 [-1.0489; -0.9465]                  Late_plus
##  -0.1865 [-0.2173; -0.1557]  0.8113 [ 0.7593;  0.8632]
##  -0.6088 [-0.6458; -0.5718]  0.3889 [ 0.3363;  0.4416]
##                                                       
##  -0.5350 [-0.5701; -0.4999] -1.0238 [-1.0669; -0.9806]
##  -0.5656 [-0.5933; -0.5378] -0.5934 [-0.6844; -0.5025]
##  -0.1021 [-0.1386; -0.0655] -0.5647 [-0.6089; -0.5205]
##   1.5746 [ 1.4787;  1.6705] -0.0375 [-0.1099;  0.0348]
##                 Recommended -0.4359 [-0.4737; -0.3981]
##  -0.4223 [-0.4575; -0.3872]           Recommended_plus
## 
## League table (random effects model):
##                                                       
##                     control -0.4687 [-1.3454;  0.4080]
##  -0.3464 [-0.9832;  0.2903]                      Early
##  -0.7404 [-1.3142; -0.1666] -0.3940 [-1.0184;  0.2304]
##  -1.2386 [-2.0980; -0.3793] -0.8922 [-1.8897;  0.1053]
##  -0.6412 [-1.1365; -0.1458] -0.2948 [-0.8917;  0.3022]
##  -1.0911 [-1.6026; -0.5795] -0.7446 [-1.3448; -0.1444]
##                                                       
##  -0.8799 [-1.5781; -0.1817] -1.5881 [-2.5430; -0.6333]
##  -0.3917 [-1.0633;  0.2798]                          .
##                        Late -0.4061 [-1.7354;  0.9232]
##  -0.4982 [-1.4310;  0.4345]                  Late_plus
##   0.0992 [-0.4327;  0.6312]  0.5975 [-0.3056;  1.5005]
##  -0.3507 [-0.8864;  0.1851]  0.1476 [-0.7606;  1.0557]
##                                                       
##  -0.6354 [-1.1662; -0.1047] -0.9986 [-1.5597; -0.4375]
##  -0.4255 [-1.0968;  0.2458] -0.7939 [-1.4650; -0.1229]
##   0.1053 [-0.4575;  0.6682] -0.3850 [-0.9478;  0.1777]
##   1.1656 [-0.1655;  2.4967]  0.0365 [-1.2950;  1.3681]
##                 Recommended -0.4652 [-0.9380;  0.0076]
##  -0.4499 [-0.9181;  0.0184]           Recommended_plus</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="meta-analysis.html#cb46-1"></a><span class="kw">decomp.design</span>(net_con)</span></code></pre></div>
<pre><code>## Q statistics to assess homogeneity / consistency
## 
##                        Q df p-value
## Total           13705.55 74       0
## Within designs   7488.00 59       0
## Between designs  6217.55 15       0
## 
## Design-specific decomposition of within-designs Q statistic
## 
##                                               Design       Q df  p-value
##                                    control:Late_plus    4.49  2   0.1058
##                                  control:Recommended    5.71  1   0.0169
##      control:Early:Late:Recommended:Recommended_plus  666.27 20 &lt; 0.0001
##  control:Late:Late_plus:Recommended:Recommended_plus 3178.16  8        0
##            control:Late:Recommended:Recommended_plus  108.58  3 &lt; 0.0001
##                 control:Recommended:Recommended_plus 2689.87 10        0
##              Early:Late:Recommended:Recommended_plus  834.92 15 &lt; 0.0001
## 
## Between-designs Q statistic after detaching of single designs
## 
##                                      Detached design       Q df p-value
##                                        control:Early 5534.62 14       0
##                                    control:Late_plus 5627.52 14       0
##                                  control:Recommended 6176.40 14       0
##                         Recommended:Recommended_plus 5511.16 14       0
##      control:Early:Late:Recommended:Recommended_plus 6074.27 11       0
##  control:Late:Late_plus:Recommended:Recommended_plus 2248.74 11       0
##            control:Late:Recommended:Recommended_plus 5233.10 12       0
##                 control:Recommended:Recommended_plus 5873.97 13       0
##              Early:Late:Recommended:Recommended_plus 5911.40 12       0
## 
## Q statistic to assess consistency under the assumption of
## a full design-by-treatment interaction random effects model
## 
##                     Q df p-value tau.within tau2.within
## Between designs 18.44 15  0.2403     1.1440      1.3087</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="meta-analysis.html#cb48-1"></a><span class="kw">netsplit</span>(net_con)</span></code></pre></div>
<pre><code>## Separate indirect from direct evidence (SIDE) using back-calculation method
## 
## Fixed effects model: 
## 
##                    comparison  k prop     nma  direct  indir.    Diff      z  p-value
##                 control:Early  7 0.27 -0.0697 -0.8515  0.2247 -1.0763 -24.12 &lt; 0.0001
##                  control:Late 11 0.64 -0.3927 -0.4574 -0.2793 -0.1782  -4.78 &lt; 0.0001
##             control:Late_plus  6 0.52 -1.3904 -2.1195 -0.6143 -1.5052 -28.58 &lt; 0.0001
##           control:Recommended 19 0.83 -0.5792 -0.5350 -0.7991  0.2641   6.04 &lt; 0.0001
##      control:Recommended_plus 17 0.81 -1.0015 -1.0238 -0.9059 -0.1179  -2.33   0.0198
##                    Early:Late 12 0.27 -0.3230 -0.5933 -0.2212 -0.3721  -8.55 &lt; 0.0001
##               Early:Late_plus  0    0 -1.3208       . -1.3208       .      .        .
##             Early:Recommended 12 0.90 -0.5095 -0.5656 -0.0158 -0.5497 -12.41 &lt; 0.0001
##        Early:Recommended_plus 12 0.21 -0.9318 -0.5934 -1.0226  0.4291   8.21 &lt; 0.0001
##                Late:Late_plus  3 0.52 -0.9977 -0.7501 -1.2685  0.5185   9.92 &lt; 0.0001
##              Late:Recommended 17 0.71 -0.1865 -0.1021 -0.3930  0.2910   8.40 &lt; 0.0001
##         Late:Recommended_plus 17 0.70 -0.6088 -0.5647 -0.7117  0.1470   3.57   0.0004
##         Late_plus:Recommended  3 0.29  0.8113  1.5746  0.4941  1.0805  18.56 &lt; 0.0001
##    Late_plus:Recommended_plus  3 0.53  0.3889 -0.0375  0.8671 -0.9047 -16.82 &lt; 0.0001
##  Recommended:Recommended_plus 24 0.87 -0.4223 -0.4359 -0.3342 -0.1017  -1.93   0.0539
## 
## Random effects model: 
## 
##                    comparison  k prop     nma  direct  indir.    Diff     z p-value
##                 control:Early  7 0.53 -0.3464 -0.4687 -0.2099 -0.2588 -0.40  0.6909
##                  control:Late 11 0.68 -0.7404 -0.8799 -0.4502 -0.4297 -0.69  0.4919
##             control:Late_plus  6 0.81 -1.2386 -1.5881  0.2508 -1.8389 -1.65  0.0999
##           control:Recommended 19 0.87 -0.6412 -0.6354 -0.6801  0.0447  0.06  0.9528
##      control:Recommended_plus 17 0.83 -1.0911 -0.9986 -1.5460  0.5474  0.79  0.4320
##                    Early:Late 12 0.86 -0.3940 -0.3917 -0.4082  0.0165  0.02  0.9859
##               Early:Late_plus  0    0 -0.8922       . -0.8922       .     .       .
##             Early:Recommended 12 0.79 -0.2948 -0.4255  0.1990 -0.6245 -0.83  0.4042
##        Early:Recommended_plus 12 0.80 -0.7446 -0.7939 -0.5474 -0.2466 -0.32  0.7474
##                Late:Late_plus  3 0.49 -0.4982 -0.4061 -0.5876  0.1815  0.19  0.8488
##              Late:Recommended 17 0.89  0.0992  0.1053  0.0480  0.0573  0.07  0.9480
##         Late:Recommended_plus 17 0.91 -0.3507 -0.3850 -0.0183 -0.3668 -0.39  0.6957
##         Late_plus:Recommended  3 0.46  0.5975  1.1656  0.1130  1.0526  1.14  0.2548
##    Late_plus:Recommended_plus  3 0.47  0.1476  0.0365  0.2442 -0.2076 -0.22  0.8232
##  Recommended:Recommended_plus 24 0.98 -0.4499 -0.4652  0.3371 -0.8023 -0.46  0.6458
## 
## Legend:
##  comparison - Treatment comparison
##  k          - Number of studies providing direct evidence
##  prop       - Direct evidence proportion
##  nma        - Estimated treatment effect (MD) in network meta-analysis
##  direct     - Estimated treatment effect (MD) derived from direct evidence
##  indir.     - Estimated treatment effect (MD) derived from indirect evidence
##  Diff       - Difference between direct and indirect treatment estimates
##  z          - z-value of test for disagreement (direct versus indirect)
##  p-value    - p-value of test for disagreement (direct versus indirect)</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="meta-analysis.html#cb50-1"></a>nm1 &lt;-<span class="st"> </span><span class="kw">netmeasures</span>(net_con)</span>
<span id="cb50-2"><a href="meta-analysis.html#cb50-2"></a></span>
<span id="cb50-3"><a href="meta-analysis.html#cb50-3"></a><span class="kw">plot</span>(</span>
<span id="cb50-4"><a href="meta-analysis.html#cb50-4"></a>   nm1<span class="op">$</span>meanpath,</span>
<span id="cb50-5"><a href="meta-analysis.html#cb50-5"></a>   nm1<span class="op">$</span>minpar,</span>
<span id="cb50-6"><a href="meta-analysis.html#cb50-6"></a>   <span class="dt">pch =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb50-7"><a href="meta-analysis.html#cb50-7"></a>   <span class="dt">xlab =</span> <span class="st">&quot;Mean path length&quot;</span>,</span>
<span id="cb50-8"><a href="meta-analysis.html#cb50-8"></a>   <span class="dt">ylab =</span> <span class="st">&quot;Minimal parallelism&quot;</span></span>
<span id="cb50-9"><a href="meta-analysis.html#cb50-9"></a>)</span>
<span id="cb50-10"><a href="meta-analysis.html#cb50-10"></a><span class="kw">text</span>(nm1<span class="op">$</span>meanpath, nm1<span class="op">$</span>minpar, <span class="kw">names</span>(nm1<span class="op">$</span>meanpath), <span class="dt">cex =</span> <span class="fl">0.8</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="meta-analysis.html#cb51-1"></a><span class="kw">write.csv</span>(slimmer_PM_dat, <span class="dt">file =</span> <span class="st">&quot;data/GYmeta_data.csv&quot;</span>)</span></code></pre></div>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-Viechtbauer2010">
<p>Viechtbauer, Wolfgang. 2010. “Conducting meta-analyses in R with the metafor.” <em>Journal of Statistical Software</em> 36 (3): 1–48. <a href="https://doi.org/10.18637/jss.v036.i03">https://doi.org/10.18637/jss.v036.i03</a>.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="prepare-data-for-meta-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="aupdc-meta-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
