<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 Post-hoc analysis and ploting | A meta-analysis of powdery mildew yield loss mitigation strategies in Australian mungbean</title>
  <meta name="description" content="A meta-analysis of fungicide use in mungbean to control for yield loss due to powdery mildew." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="6 Post-hoc analysis and ploting | A meta-analysis of powdery mildew yield loss mitigation strategies in Australian mungbean" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A meta-analysis of fungicide use in mungbean to control for yield loss due to powdery mildew." />
  <meta name="github-repo" content="OpenPlantPathology/Mungbean_PM" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Post-hoc analysis and ploting | A meta-analysis of powdery mildew yield loss mitigation strategies in Australian mungbean" />
  
  <meta name="twitter:description" content="A meta-analysis of fungicide use in mungbean to control for yield loss due to powdery mildew." />
  

<meta name="author" content="Paul Melloy, Emerson Del Ponte and Adam H. Sparks" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="grain-yield-meta-analysis.html"/>
<link rel="next" href="import-and-format-data.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Home</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#contents"><i class="fa fa-check"></i><b>1.1</b> Contents</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#other-research-questions-which-are-not-the-focus-of-this-study"><i class="fa fa-check"></i><b>1.2</b> Other research questions, which are not the focus of this study</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#possible-sources-of-variation-in-this-analysis."><i class="fa fa-check"></i><b>1.3</b> Possible sources of variation in this analysis.</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html"><i class="fa fa-check"></i><b>2</b> Trials considered for inclusion in meta-analysis</a><ul>
<li class="chapter" data-level="2.1" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html#criteria-for-inclusion-in-meta-analysis"><i class="fa fa-check"></i><b>2.1</b> Criteria for inclusion in meta-analysis</a></li>
<li class="chapter" data-level="2.2" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html#import-data-and-apply-selection-criteria"><i class="fa fa-check"></i><b>2.2</b> Import data and apply selection criteria</a><ul>
<li class="chapter" data-level="2.2.1" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html#import-data-from-trials-we-have-the-raw-data"><i class="fa fa-check"></i><b>2.2.1</b> Import data from trials we have the raw data</a></li>
<li class="chapter" data-level="2.2.2" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html#import-dataset-of-manual-entries"><i class="fa fa-check"></i><b>2.2.2</b> Import dataset of manual entries</a></li>
<li class="chapter" data-level="2.2.3" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html#summary-of-all-trials"><i class="fa fa-check"></i><b>2.2.3</b> Summary of all trials</a></li>
<li class="chapter" data-level="2.2.4" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html#experiment-locations"><i class="fa fa-check"></i><b>2.2.4</b> Experiment locations</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html#subset-data-to-selection-criteria"><i class="fa fa-check"></i><b>2.3</b> Subset data to selection criteria</a><ul>
<li class="chapter" data-level="2.3.1" data-path="trials-considered-for-inclusion-in-meta-analysis.html"><a href="trials-considered-for-inclusion-in-meta-analysis.html#classify-dataset-variables"><i class="fa fa-check"></i><b>2.3.1</b> Classify dataset variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html"><i class="fa fa-check"></i><b>3</b> Preliminary Analysis</a><ul>
<li class="chapter" data-level="3.1" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#explore-and-visualise-data"><i class="fa fa-check"></i><b>3.1</b> Explore and Visualise Data</a><ul>
<li class="chapter" data-level="3.1.1" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#descriptive-statistics"><i class="fa fa-check"></i><b>3.1.1</b> Descriptive statistics</a></li>
<li class="chapter" data-level="3.1.2" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#fungicides"><i class="fa fa-check"></i><b>3.1.2</b> Fungicides</a></li>
<li class="chapter" data-level="3.1.3" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#mungbean-cultivars"><i class="fa fa-check"></i><b>3.1.3</b> Mungbean cultivars</a></li>
<li class="chapter" data-level="3.1.4" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#row-spacing"><i class="fa fa-check"></i><b>3.1.4</b> Row spacing</a></li>
<li class="chapter" data-level="3.1.5" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#yield-loss-in-cultivar-jade"><i class="fa fa-check"></i><b>3.1.5</b> Yield loss in cultivar Jade</a></li>
<li class="chapter" data-level="3.1.6" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#fao-mungbean-data"><i class="fa fa-check"></i><b>3.1.6</b> FAO mungbean data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html"><i class="fa fa-check"></i><b>4</b> Prepare data for meta-analysis</a><ul>
<li class="chapter" data-level="4.1" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#set-environment-and-import-data"><i class="fa fa-check"></i><b>4.1</b> Set environment and import data</a></li>
<li class="chapter" data-level="4.2" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#subset-to-trials-containing-dmi-fungicides"><i class="fa fa-check"></i><b>4.2</b> Subset to trials containing DMI fungicides</a></li>
<li class="chapter" data-level="4.3" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#standardising-sample-variance"><i class="fa fa-check"></i><b>4.3</b> Standardising sample variance</a><ul>
<li class="chapter" data-level="4.3.1" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#converting-least-squares-to-sample-variance"><i class="fa fa-check"></i><b>4.3.1</b> Converting least-squares to sample variance</a></li>
<li class="chapter" data-level="4.3.2" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#converting-standard-deviation-to-sample-variance"><i class="fa fa-check"></i><b>4.3.2</b> Converting standard deviation to sample variance</a></li>
<li class="chapter" data-level="4.3.3" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#check-variance-of-data-set"><i class="fa fa-check"></i><b>4.3.3</b> Check variance of data-set</a></li>
<li class="chapter" data-level="4.3.4" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#inspect-variance-and-response-for-analysis"><i class="fa fa-check"></i><b>4.3.4</b> Inspect variance and response for analysis</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#classifying-fungicide-treatment"><i class="fa fa-check"></i><b>4.4</b> Classifying fungicide treatment</a></li>
<li class="chapter" data-level="4.5" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#trial-factor"><i class="fa fa-check"></i><b>4.5</b> Trial factor</a></li>
<li class="chapter" data-level="4.6" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#test-dose-effect"><i class="fa fa-check"></i><b>4.6</b> Test dose effect</a></li>
<li class="chapter" data-level="4.7" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#row-spacing"><i class="fa fa-check"></i><b>4.7</b> Row spacing</a></li>
<li class="chapter" data-level="4.8" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#remove-unnecersary-variables"><i class="fa fa-check"></i><b>4.8</b> Remove unnecersary variables</a></li>
<li class="chapter" data-level="4.9" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#final-data-check"><i class="fa fa-check"></i><b>4.9</b> Final data check</a><ul>
<li class="chapter" data-level="4.9.1" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#simplify-and-save-data"><i class="fa fa-check"></i><b>4.9.1</b> Simplify and save data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="grain-yield-meta-analysis.html"><a href="grain-yield-meta-analysis.html"><i class="fa fa-check"></i><b>5</b> Grain yield meta-analysis</a><ul>
<li class="chapter" data-level="5.1" data-path="grain-yield-meta-analysis.html"><a href="grain-yield-meta-analysis.html#metafor-analysis"><i class="fa fa-check"></i><b>5.1</b> metafor analysis</a><ul>
<li class="chapter" data-level="5.1.1" data-path="grain-yield-meta-analysis.html"><a href="grain-yield-meta-analysis.html#profile-plots"><i class="fa fa-check"></i><b>5.1.1</b> Profile plots</a></li>
<li class="chapter" data-level="5.1.2" data-path="grain-yield-meta-analysis.html"><a href="grain-yield-meta-analysis.html#forest-plot-of-trial-treatment-effect-per-trial"><i class="fa fa-check"></i><b>5.1.2</b> Forest plot of trial treatment effect per trial</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="grain-yield-meta-analysis.html"><a href="grain-yield-meta-analysis.html#netmeta-analysis"><i class="fa fa-check"></i><b>5.2</b> netmeta analysis</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="post-hoc-analysis-and-ploting.html"><a href="post-hoc-analysis-and-ploting.html"><i class="fa fa-check"></i><b>6</b> Post-hoc analysis and ploting</a><ul>
<li class="chapter" data-level="6.0.1" data-path="post-hoc-analysis-and-ploting.html"><a href="post-hoc-analysis-and-ploting.html#mungbeans-age-and-yield-saved"><i class="fa fa-check"></i><b>6.0.1</b> Mungbeans age and yield saved</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="import-and-format-data.html"><a href="import-and-format-data.html"><i class="fa fa-check"></i><b>7</b> Import and Format Data</a><ul>
<li class="chapter" data-level="7.1" data-path="import-and-format-data.html"><a href="import-and-format-data.html#non-wrangled-trials"><i class="fa fa-check"></i><b>7.1</b> Non-wrangled trials</a></li>
<li class="chapter" data-level="7.2" data-path="import-and-format-data.html"><a href="import-and-format-data.html#import-libraries"><i class="fa fa-check"></i><b>7.2</b> Import Libraries</a></li>
<li class="chapter" data-level="7.3" data-path="import-and-format-data.html"><a href="import-and-format-data.html#functions"><i class="fa fa-check"></i><b>7.3</b> Functions</a></li>
<li class="chapter" data-level="7.4" data-path="import-and-format-data.html"><a href="import-and-format-data.html#data-wrangling-for-each-trial"><i class="fa fa-check"></i><b>7.4</b> Data wrangling for each trial</a><ul>
<li class="chapter" data-level="7.4.1" data-path="import-and-format-data.html"><a href="import-and-format-data.html#hermitage-2010"><i class="fa fa-check"></i><b>7.4.1</b> Hermitage 2010</a></li>
<li class="chapter" data-level="7.4.2" data-path="import-and-format-data.html"><a href="import-and-format-data.html#hermitage-2011"><i class="fa fa-check"></i><b>7.4.2</b> Hermitage 2011</a></li>
<li class="chapter" data-level="7.4.3" data-path="import-and-format-data.html"><a href="import-and-format-data.html#kingaroy-2011"><i class="fa fa-check"></i><b>7.4.3</b> Kingaroy 2011</a></li>
<li class="chapter" data-level="7.4.4" data-path="import-and-format-data.html"><a href="import-and-format-data.html#goolhi-2013"><i class="fa fa-check"></i><b>7.4.4</b> Goolhi 2013</a></li>
<li class="chapter" data-level="7.4.5" data-path="import-and-format-data.html"><a href="import-and-format-data.html#marys-mount-2013"><i class="fa fa-check"></i><b>7.4.5</b> Mary’s Mount 2013</a></li>
<li class="chapter" data-level="7.4.6" data-path="import-and-format-data.html"><a href="import-and-format-data.html#premer-2013"><i class="fa fa-check"></i><b>7.4.6</b> Premer 2013</a></li>
<li class="chapter" data-level="7.4.7" data-path="import-and-format-data.html"><a href="import-and-format-data.html#millmerran-2013"><i class="fa fa-check"></i><b>7.4.7</b> Millmerran 2013</a></li>
<li class="chapter" data-level="7.4.8" data-path="import-and-format-data.html"><a href="import-and-format-data.html#hermitage-2015"><i class="fa fa-check"></i><b>7.4.8</b> Hermitage 2015</a></li>
<li class="chapter" data-level="7.4.9" data-path="import-and-format-data.html"><a href="import-and-format-data.html#hermitage-2016"><i class="fa fa-check"></i><b>7.4.9</b> Hermitage 2016</a></li>
<li class="chapter" data-level="7.4.10" data-path="import-and-format-data.html"><a href="import-and-format-data.html#kingaroy-2016"><i class="fa fa-check"></i><b>7.4.10</b> Kingaroy 2016</a></li>
<li class="chapter" data-level="7.4.11" data-path="import-and-format-data.html"><a href="import-and-format-data.html#missen-flats-2017"><i class="fa fa-check"></i><b>7.4.11</b> Missen Flats 2017</a></li>
<li class="chapter" data-level="7.4.12" data-path="import-and-format-data.html"><a href="import-and-format-data.html#hermitage-2017"><i class="fa fa-check"></i><b>7.4.12</b> Hermitage 2017</a></li>
<li class="chapter" data-level="7.4.13" data-path="import-and-format-data.html"><a href="import-and-format-data.html#wellcamp-2018"><i class="fa fa-check"></i><b>7.4.13</b> Wellcamp 2018</a></li>
<li class="chapter" data-level="7.4.14" data-path="import-and-format-data.html"><a href="import-and-format-data.html#hermitage-2019"><i class="fa fa-check"></i><b>7.4.14</b> Hermitage 2019</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>8</b> Introduction</a><ul>
<li class="chapter" data-level="8.1" data-path="introduction.html"><a href="introduction.html#criteria-for-trial-data-inclusion"><i class="fa fa-check"></i><b>8.1</b> Criteria for Trial Data Inclusion</a></li>
<li class="chapter" data-level="8.2" data-path="introduction.html"><a href="introduction.html#response-variable"><i class="fa fa-check"></i><b>8.2</b> Response Variable</a></li>
<li class="chapter" data-level="8.3" data-path="introduction.html"><a href="introduction.html#trial-variables-and-moderators"><i class="fa fa-check"></i><b>8.3</b> Trial Variables and Moderators</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A meta-analysis of powdery mildew yield loss mitigation strategies in Australian mungbean</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="post-hoc-analysis-and-ploting" class="section level1">
<h1><span class="header-section-number">6</span> Post-hoc analysis and ploting</h1>
<div id="mungbeans-age-and-yield-saved" class="section level3">
<h3><span class="header-section-number">6.0.1</span> Mungbeans age and yield saved</h3>
<p>The time at which powdery mildew infects in the seasons and the age of the plant might affect the AUDPC and the loss in yield.
Let’s have a look at the age of each trial when powdery mildew infected it.
We will use the difference between <code>planting_date</code> and <code>first_sign_disease</code> as a proxy for crop maturity when it became infected.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="post-hoc-analysis-and-ploting.html#cb1-1"></a>dat1 &lt;-<span class="st"> </span>PM_MB_dat_full <span class="op">%&gt;%</span></span>
<span id="cb1-2"><a href="post-hoc-analysis-and-ploting.html#cb1-2"></a><span class="st">   </span><span class="kw">mutate</span>(<span class="dt">days2PM =</span> first_sign_disease <span class="op">-</span><span class="st"> </span>planting_date) <span class="op">%&gt;%</span></span>
<span id="cb1-3"><a href="post-hoc-analysis-and-ploting.html#cb1-3"></a><span class="st">   </span><span class="kw">arrange</span>(<span class="kw">desc</span>(days2PM)) <span class="op">%&gt;%</span></span>
<span id="cb1-4"><a href="post-hoc-analysis-and-ploting.html#cb1-4"></a><span class="st">   </span><span class="kw">select</span>(</span>
<span id="cb1-5"><a href="post-hoc-analysis-and-ploting.html#cb1-5"></a>      trial_ref,</span>
<span id="cb1-6"><a href="post-hoc-analysis-and-ploting.html#cb1-6"></a>      year,</span>
<span id="cb1-7"><a href="post-hoc-analysis-and-ploting.html#cb1-7"></a>      location,</span>
<span id="cb1-8"><a href="post-hoc-analysis-and-ploting.html#cb1-8"></a>      spray_management,</span>
<span id="cb1-9"><a href="post-hoc-analysis-and-ploting.html#cb1-9"></a>      days2PM,</span>
<span id="cb1-10"><a href="post-hoc-analysis-and-ploting.html#cb1-10"></a>      grain_yield.t.ha.,</span>
<span id="cb1-11"><a href="post-hoc-analysis-and-ploting.html#cb1-11"></a>      yield_gain,</span>
<span id="cb1-12"><a href="post-hoc-analysis-and-ploting.html#cb1-12"></a>      AUDPC_m,</span>
<span id="cb1-13"><a href="post-hoc-analysis-and-ploting.html#cb1-13"></a>      PM_final_severity</span>
<span id="cb1-14"><a href="post-hoc-analysis-and-ploting.html#cb1-14"></a>   )</span>
<span id="cb1-15"><a href="post-hoc-analysis-and-ploting.html#cb1-15"></a>dat1</span></code></pre></div>
<pre><code>##       trial_ref year     location spray_management days2PM grain_yield.t.ha.
## 1        AM1304 2013  Marys Mount          control 82 days            1.0938
## 2        AM1304 2013  Marys Mount            Early 82 days            1.2654
## 3   mung1819/01 2019    Hermitage      Recommended 67 days            0.5432
## 4   mung1819/01 2019    Hermitage Recommended_plus 67 days            0.5636
## 5   mung1819/01 2019    Hermitage             Late 67 days            0.5713
## 6   mung1819/01 2019    Hermitage          control 67 days            0.5872
## 7   mung1011/01 2011    Hermitage          control 63 days            1.6619
## 8   mung1011/01 2011    Hermitage      Recommended 63 days            1.7693
## 9   mung1011/01 2011    Hermitage          control 63 days            1.3876
## 10  mung1011/01 2011    Hermitage      Recommended 63 days            1.5439
## 11       AM1303 2013       Premer          control 62 days            1.4216
## 12       AM1303 2013       Premer Recommended_plus 62 days            1.3337
## 13       AM1303 2013       Premer      Recommended 62 days            1.4502
## 14       AM1303 2013       Premer Recommended_plus 62 days            1.3446
## 15       AM1305 2013       Goolhi          control 61 days            0.6944
## 16       AM1305 2013       Goolhi Recommended_plus 61 days            0.6042
## 17       AM1305 2013       Goolhi      Recommended 61 days            0.6528
## 18       AM1305 2013       Goolhi Recommended_plus 61 days            0.7222
## 19       BB1305 2013   Millmerran          control 60 days            0.8021
## 20       BB1305 2013   Millmerran      Recommended 60 days            0.8027
## 21       BB1305 2013   Millmerran Recommended_plus 60 days            0.7714
## 22       BB1305 2013   Millmerran Recommended_plus 60 days            0.7439
## 23  mung1415/01 2015    Hermitage          control 56 days            2.0449
## 24  mung1415/01 2015    Hermitage      Recommended 56 days            2.0183
## 25  mung1415/01 2015    Hermitage Recommended_plus 56 days            2.1524
## 26  mung1415/01 2015    Hermitage             Late 56 days            2.1240
## 27  mung1415/01 2015    Hermitage        Late_plus 56 days            2.1755
## 28  mung1819/02 2019    Hermitage      Recommended 53 days            0.2962
## 29  mung1819/02 2019    Hermitage Recommended_plus 53 days            0.3117
## 30  mung1819/02 2019    Hermitage             Late 53 days            0.2759
## 31  mung1819/02 2019    Hermitage          control 53 days            0.2894
## 32  mung1011/02 2011     Kingaroy          control 48 days            0.7985
## 33  mung1011/02 2011     Kingaroy      Recommended 48 days            1.0586
## 34  mung1011/02 2011     Kingaroy Recommended_plus 48 days            0.9862
## 35  mung1011/02 2011     Kingaroy          control 48 days            0.7985
## 36  mung1011/02 2011     Kingaroy      Recommended 48 days            0.7302
## 37  mung1011/02 2011     Kingaroy Recommended_plus 48 days            0.8754
## 38  mung1617/02 2017 Missen Flats          control 39 days            1.6419
## 39  mung1617/02 2017 Missen Flats          control 39 days            2.0839
## 40  mung1617/02 2017 Missen Flats          control 39 days            1.8249
## 41  mung1617/02 2017 Missen Flats          control 39 days            1.5046
## 42  mung1617/02 2017 Missen Flats          control 39 days            1.4828
## 43  mung1617/02 2017 Missen Flats          control 39 days            1.6085
## 44  mung1617/02 2017 Missen Flats          control 39 days            1.4484
## 45  mung1617/02 2017 Missen Flats          control 39 days            1.2265
## 46  mung1617/02 2017 Missen Flats          control 39 days            1.2279
## 47  mung1617/02 2017 Missen Flats            Early 39 days            1.7914
## 48  mung1617/02 2017 Missen Flats            Early 39 days            1.7243
## 49  mung1617/02 2017 Missen Flats            Early 39 days            1.7330
## 50  mung1617/02 2017 Missen Flats            Early 39 days            1.7173
## 51  mung1617/02 2017 Missen Flats            Early 39 days            1.1302
## 52  mung1617/02 2017 Missen Flats            Early 39 days            1.4435
## 53  mung1617/02 2017 Missen Flats      Recommended 39 days            2.1006
## 54  mung1617/02 2017 Missen Flats      Recommended 39 days            1.9219
## 55  mung1617/02 2017 Missen Flats      Recommended 39 days            1.8592
## 56  mung1617/02 2017 Missen Flats      Recommended 39 days            1.8610
## 57  mung1617/02 2017 Missen Flats      Recommended 39 days            1.4981
## 58  mung1617/02 2017 Missen Flats      Recommended 39 days            1.3891
## 59  mung1617/02 2017 Missen Flats Recommended_plus 39 days            2.1017
## 60  mung1617/02 2017 Missen Flats Recommended_plus 39 days            2.5263
## 61  mung1617/02 2017 Missen Flats Recommended_plus 39 days            2.1795
## 62  mung1617/02 2017 Missen Flats Recommended_plus 39 days            2.0006
## 63  mung1617/02 2017 Missen Flats Recommended_plus 39 days            1.9737
## 64  mung1617/02 2017 Missen Flats Recommended_plus 39 days            1.7988
## 65  mung1617/02 2017 Missen Flats             Late 39 days            2.1434
## 66  mung1617/02 2017 Missen Flats             Late 39 days            1.8778
## 67  mung1617/02 2017 Missen Flats             Late 39 days            1.8279
## 68  mung1617/02 2017 Missen Flats             Late 39 days            1.7806
## 69  mung1617/02 2017 Missen Flats             Late 39 days            1.7564
## 70  mung1617/02 2017 Missen Flats             Late 39 days            1.5337
## 71  mung1617/02 2017 Missen Flats Recommended_plus 39 days            2.3121
## 72  mung1617/02 2017 Missen Flats Recommended_plus 39 days            2.2779
## 73  mung1617/02 2017 Missen Flats Recommended_plus 39 days            2.1126
## 74  mung1617/02 2017 Missen Flats Recommended_plus 39 days            1.3569
## 75  mung1617/02 2017 Missen Flats Recommended_plus 39 days            1.7922
## 76  mung1617/02 2017 Missen Flats Recommended_plus 39 days            1.7424
## 77  mung1617/01 2017    Hermitage          control 39 days            0.4047
## 78  mung1617/01 2017    Hermitage          control 39 days            0.5589
## 79  mung1617/01 2017    Hermitage          control 39 days            0.3163
## 80  mung1617/01 2017    Hermitage          control 39 days            0.3191
## 81  mung1617/01 2017    Hermitage          control 39 days            0.6205
## 82  mung1617/01 2017    Hermitage          control 39 days            0.4736
## 83  mung1617/01 2017    Hermitage          control 39 days            0.6152
## 84  mung1617/01 2017    Hermitage          control 39 days            0.5020
## 85  mung1617/01 2017    Hermitage          control 39 days            0.4721
## 86  mung1617/01 2017    Hermitage            Early 39 days            0.3594
## 87  mung1617/01 2017    Hermitage            Early 39 days            0.5928
## 88  mung1617/01 2017    Hermitage            Early 39 days            0.6020
## 89  mung1617/01 2017    Hermitage            Early 39 days            0.5593
## 90  mung1617/01 2017    Hermitage            Early 39 days            0.5031
## 91  mung1617/01 2017    Hermitage            Early 39 days            0.4824
## 92  mung1617/01 2017    Hermitage Recommended_plus 39 days            0.5060
## 93  mung1617/01 2017    Hermitage Recommended_plus 39 days            0.3798
## 94  mung1617/01 2017    Hermitage Recommended_plus 39 days            0.4386
## 95  mung1617/01 2017    Hermitage Recommended_plus 39 days            0.4444
## 96  mung1617/01 2017    Hermitage Recommended_plus 39 days            0.5183
## 97  mung1617/01 2017    Hermitage Recommended_plus 39 days            0.4407
## 98  mung1617/01 2017    Hermitage      Recommended 39 days            0.6467
## 99  mung1617/01 2017    Hermitage      Recommended 39 days            0.6123
## 100 mung1617/01 2017    Hermitage      Recommended 39 days            0.5530
## 101 mung1617/01 2017    Hermitage      Recommended 39 days            0.4574
## 102 mung1617/01 2017    Hermitage      Recommended 39 days            0.4664
## 103 mung1617/01 2017    Hermitage      Recommended 39 days            0.5208
## 104 mung1617/01 2017    Hermitage Recommended_plus 39 days            0.6590
## 105 mung1617/01 2017    Hermitage Recommended_plus 39 days            0.5448
## 106 mung1617/01 2017    Hermitage Recommended_plus 39 days            0.4199
## 107 mung1617/01 2017    Hermitage Recommended_plus 39 days            0.3415
## 108 mung1617/01 2017    Hermitage Recommended_plus 39 days            0.5638
## 109 mung1617/01 2017    Hermitage Recommended_plus 39 days            0.6566
## 110 mung1617/01 2017    Hermitage             Late 39 days            0.3900
## 111 mung1617/01 2017    Hermitage             Late 39 days            0.4781
## 112 mung1617/01 2017    Hermitage             Late 39 days            0.3266
## 113 mung1617/01 2017    Hermitage             Late 39 days            0.5341
## 114 mung1617/01 2017    Hermitage             Late 39 days            0.5008
## 115 mung1617/01 2017    Hermitage             Late 39 days            0.6831
## 116 mung1112/02 2012     Kingaroy          control 38 days            0.7510
## 117 mung1112/02 2012     Kingaroy      Recommended 38 days            1.0900
## 118 mung1112/02 2012     Kingaroy Recommended_plus 38 days            1.0980
## 119 mung1112/02 2012     Kingaroy      Recommended 38 days            1.0360
## 120 mung1112/02 2012     Kingaroy Recommended_plus 38 days            1.2010
## 121 mung1112/02 2012     Kingaroy      Recommended 38 days            1.0570
## 122 mung1112/02 2012     Kingaroy Recommended_plus 38 days            1.3230
## 123 mung1718/01 2018     Wellcamp        Late_plus 36 days            1.5559
## 124 mung1718/01 2018     Wellcamp        Late_plus 36 days            1.5820
## 125 mung1718/01 2018     Wellcamp          control 36 days            0.9007
## 126 mung1718/01 2018     Wellcamp        Late_plus 36 days            1.4725
## 127 mung1718/01 2018     Wellcamp        Late_plus 36 days            1.5675
## 128 mung1718/01 2018     Wellcamp          control 36 days            1.0891
## 129 mung1718/01 2018     Wellcamp        Late_plus 36 days            1.0845
## 130 mung1718/01 2018     Wellcamp        Late_plus 36 days            1.1543
## 131 mung1718/01 2018     Wellcamp          control 36 days            1.0928
## 132 mung1718/01 2018     Wellcamp        Late_plus 36 days            1.5754
## 133 mung1718/01 2018     Wellcamp        Late_plus 36 days            1.6521
## 134 mung1718/01 2018     Wellcamp          control 36 days            1.5731
## 135 mung1718/01 2018     Wellcamp        Late_plus 36 days            1.2170
## 136 mung1718/01 2018     Wellcamp        Late_plus 36 days            1.6903
## 137 mung1718/01 2018     Wellcamp          control 36 days            1.4513
## 138 mung1718/01 2018     Wellcamp        Late_plus 36 days            1.2344
## 139 mung1718/01 2018     Wellcamp        Late_plus 36 days            1.1731
## 140 mung1718/01 2018     Wellcamp          control 36 days            1.0561
## 141 mung1516/01 2016    Hermitage          control 34 days            1.8029
## 142 mung1516/01 2016    Hermitage             Late 34 days            2.2159
## 143 mung1516/01 2016    Hermitage        Late_plus 34 days            2.3701
## 144 mung1516/01 2016    Hermitage        Late_plus 34 days            2.2930
## 145 mung1516/01 2016    Hermitage      Recommended 34 days            2.1414
## 146 mung1516/01 2016    Hermitage Recommended_plus 34 days            2.3381
## 147 mung1516/01 2016    Hermitage        Late_plus 34 days            2.3346
## 148 mung1516/02 2016     Kingaroy          control 27 days            0.8107
## 149 mung1516/02 2016     Kingaroy             Late 27 days            1.0309
## 150 mung1516/02 2016     Kingaroy        Late_plus 27 days            1.0339
## 151 mung1516/02 2016     Kingaroy        Late_plus 27 days            0.8728
## 152 mung1516/02 2016     Kingaroy      Recommended 27 days            0.8990
## 153 mung1516/02 2016     Kingaroy Recommended_plus 27 days            0.9438
## 154 mung1516/02 2016     Kingaroy        Late_plus 27 days            0.9443
##        yield_gain    AUDPC_m PM_final_severity
## 1              NA  47.125000            3.0000
## 2    0.1716000000  30.583333            3.1667
## 3   -0.0440000000  28.000000            5.0000
## 4   -0.0236000000  28.000000            5.0000
## 5   -0.0159000000  42.666667            7.1667
## 6              NA  41.000000            7.5000
## 7              NA  38.500000            4.6667
## 8    0.2445500000  10.500000            2.0000
## 9              NA  42.000000            5.0000
## 10   0.0191500000  14.000000            2.3333
## 11             NA  24.500000            8.0000
## 12  -0.0879000000   3.500000            2.0000
## 13   0.0286000000  23.916667            7.8333
## 14  -0.0770000000   4.083333            2.1667
## 15             NA 161.000000            7.0000
## 16  -0.0902000000   0.000000            1.0000
## 17  -0.0416000000  37.375000            3.7500
## 18   0.0278000000  14.875000            2.7500
## 19             NA 153.625000            8.0000
## 20   0.0006000000  66.500000            8.0000
## 21  -0.0307000000  49.062500            5.6250
## 22  -0.0582000000  11.062500            1.6250
## 23             NA  82.600000            7.8000
## 24  -0.0266000000  61.800000            6.6000
## 25   0.1075000000  55.400000            5.4000
## 26   0.0791000000  79.400000            6.6000
## 27   0.1306000000  73.700000            6.4000
## 28   0.0068000000  49.800000            5.6000
## 29   0.0223000000  47.800000            4.6000
## 30  -0.0135000000  83.000000            7.3333
## 31             NA  78.333333            7.8333
## 32             NA 211.000000            8.0000
## 33   0.2601000000  96.333333            5.3333
## 34   0.1877000000  55.333333            3.3333
## 35             NA 173.166667            7.6667
## 36  -0.0683000000  50.333333            4.3333
## 37   0.0769000000  45.500000            4.0000
## 38             NA 233.666667            9.0000
## 39             NA 239.500000            9.0000
## 40             NA 241.833333            9.0000
## 41             NA 242.333333            9.0000
## 42             NA 239.500000            9.0000
## 43             NA 241.833333            9.0000
## 44             NA 237.333333            9.0000
## 45             NA 241.000000            8.6667
## 46             NA 239.500000            9.0000
## 47  -0.0588333333 212.166667            8.6667
## 48  -0.1259333333 223.833333            9.0000
## 49   0.2010333333 230.666667            8.6667
## 50   0.1853333333 224.166667            9.0000
## 51  -0.1707333333 229.000000            9.0000
## 52   0.1425666667 223.666667            9.0000
## 53   0.2503666667 159.833333            8.0000
## 54   0.0716666667 197.166667            8.6667
## 55   0.3272333333 168.666667            8.3333
## 56   0.3290333333 198.500000            8.3333
## 57   0.1971666667 175.166667            8.6667
## 58   0.0881666667 186.833333            8.0000
## 59   0.2514666667 174.166667            8.0000
## 60   0.6760666667 158.333333            8.0000
## 61   0.6475333333 149.666667            7.6667
## 62   0.4686333333 191.500000            8.0000
## 63   0.6727666667 153.166667            8.0000
## 64   0.4978666667 188.000000            8.0000
## 65   0.2931666667 199.333333            8.0000
## 66   0.0275666667 207.333333            8.0000
## 67   0.2959333333 207.333333            8.0000
## 68   0.2486333333 218.500000            8.0000
## 69   0.4554666667 192.833333            8.0000
## 70   0.2327666667 218.500000            8.0000
## 71   0.4618666667 201.666667            8.0000
## 72   0.4276666667 214.333333            7.6667
## 73   0.5806333333 204.333333            8.0000
## 74  -0.1750666667 215.666667            8.0000
## 75   0.4912666667 202.833333            8.0000
## 76   0.4414666667 207.500000            8.0000
## 77             NA 246.500000            8.0000
## 78             NA 222.666667            8.0000
## 79             NA 212.000000            8.0000
## 80             NA 235.500000            8.0000
## 81             NA 226.833333            8.0000
## 82             NA 212.333333            8.0000
## 83             NA 235.166667            8.0000
## 84             NA 222.833333            8.0000
## 85             NA 241.500000            8.0000
## 86  -0.0869333333 140.000000            8.0000
## 87   0.0323333333 123.833333            7.6667
## 88   0.1813333333 125.500000            8.0000
## 89   0.1129666667 124.666667            8.0000
## 90  -0.0573666667 159.166667            8.0000
## 91   0.0617333333 137.666667            7.6667
## 92   0.0596666667  98.000000            7.0000
## 93  -0.1806666667  77.166667            7.0000
## 94   0.0179333333 106.333333            7.0000
## 95  -0.0019333333 117.666667            7.0000
## 96  -0.0421666667 114.333333            7.0000
## 97   0.0200333333 125.166667            7.0000
## 98   0.2003666667 140.833333            8.0000
## 99   0.0518333333 155.666667            8.0000
## 100  0.1323333333 152.000000            7.6667
## 101  0.0110666667 188.833333            8.0000
## 102 -0.0940666667 177.166667            8.0000
## 103  0.1001333333 144.666667            8.0000
## 104  0.2126666667 120.666667            7.0000
## 105 -0.0156666667  99.500000            5.3333
## 106 -0.0007666667 113.000000            7.0000
## 107 -0.1048333333 173.000000            7.0000
## 108  0.0033333333 140.500000            7.0000
## 109  0.2359333333 151.833333            7.0000
## 110 -0.0563333333 144.833333            7.0000
## 111 -0.0823666667 155.333333            7.0000
## 112 -0.0940666667 177.666667            7.0000
## 113  0.0877666667 175.333333            7.3333
## 114 -0.0596666667 182.666667            7.6667
## 115  0.2624333333 206.166667            8.0000
## 116            NA         NA            8.0000
## 117  0.3390000000         NA            8.0000
## 118  0.3470000000         NA            4.3000
## 119  0.2850000000         NA            7.7000
## 120  0.4500000000         NA            4.7000
## 121  0.3060000000         NA            7.3000
## 122  0.5720000000         NA            1.7000
## 123  0.3190000000 172.500000            7.6667
## 124  0.3451000000 156.333333            6.3333
## 125            NA 178.833333            8.3333
## 126  0.2023000000 166.166667            7.0000
## 127  0.2973000000 147.666667            6.0000
## 128            NA 200.166667            8.0000
## 129  0.0100500000 175.666667            7.3333
## 130  0.0798500000 158.000000            6.0000
## 131            NA 193.666667            7.3333
## 132  0.3385000000 171.500000            7.0000
## 133  0.4152000000 155.333333            6.0000
## 134            NA 194.333333            9.0000
## 135 -0.0532000000 189.500000            7.3333
## 136  0.4201000000 161.500000            7.0000
## 137            NA 220.333333            8.6667
## 138  0.1599500000 170.333333            6.6667
## 139  0.0986500000 150.666667            5.6667
## 140            NA 205.000000            8.0000
## 141            NA 119.625000            8.0000
## 142  0.4130000000  71.750000            6.2500
## 143  0.5672000000  61.750000            4.5000
## 144  0.4901000000  50.500000            3.0000
## 145  0.3385000000  61.125000            4.0000
## 146  0.5352000000  64.375000            7.5000
## 147  0.5317000000  53.750000            6.5000
## 148            NA 172.000000            8.2500
## 149  0.2202000000 113.500000            7.0000
## 150  0.2232000000  47.000000            2.2500
## 151  0.0621000000  54.000000            2.5000
## 152  0.0883000000 140.000000            7.7500
## 153  0.1331000000  87.500000            6.5000
## 154  0.1336000000  63.500000            2.7500</code></pre>
<p>From these trials I am most interested in the experiments that directly compare <code>Recommended</code> with <code>Recommended_P_plus</code> and/or <code>Late</code> with <code>Late_plus</code>.
Therefore I will not inspect, <code>AM1304</code> (Marys Mount), which only trialled an early, prophylactic spray.</p>
<p>We can see that the crops which were likely the most mature, did not show large yield gains, in particular:</p>
<ul>
<li>Hermitage 2019<br />
</li>
<li>Premer<br />
</li>
<li>Goolhi<br />
</li>
<li>Millmerran</li>
</ul>
<p>Let’s look at this in a quick box plot.
We will only look at trials where powdery mildew set in 60 days after planting, when the physiological maturity was likely flowering.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="post-hoc-analysis-and-ploting.html#cb3-1"></a>dat1 <span class="op">%&gt;%</span></span>
<span id="cb3-2"><a href="post-hoc-analysis-and-ploting.html#cb3-2"></a><span class="st">   </span><span class="kw">filter</span>(days2PM <span class="op">&gt;=</span><span class="st"> </span><span class="dv">60</span>) <span class="op">%&gt;%</span></span>
<span id="cb3-3"><a href="post-hoc-analysis-and-ploting.html#cb3-3"></a><span class="st">   </span><span class="kw">filter</span>(spray_management <span class="op">!=</span><span class="st"> &quot;control&quot;</span> <span class="op">&amp;</span></span>
<span id="cb3-4"><a href="post-hoc-analysis-and-ploting.html#cb3-4"></a><span class="st">             </span>trial_ref <span class="op">!=</span><span class="st"> &quot;AM1304&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb3-5"><a href="post-hoc-analysis-and-ploting.html#cb3-5"></a><span class="st">   </span><span class="kw">group_by</span>(trial_ref, spray_management) <span class="op">%&gt;%</span></span>
<span id="cb3-6"><a href="post-hoc-analysis-and-ploting.html#cb3-6"></a><span class="st">   </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> spray_management, <span class="dt">y =</span> yield_gain, <span class="dt">colour =</span> trial_ref)) <span class="op">+</span></span>
<span id="cb3-7"><a href="post-hoc-analysis-and-ploting.html#cb3-7"></a><span class="st">   </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></span>
<span id="cb3-8"><a href="post-hoc-analysis-and-ploting.html#cb3-8"></a><span class="st">   </span><span class="kw">scale_fill_usq</span>() <span class="op">+</span></span>
<span id="cb3-9"><a href="post-hoc-analysis-and-ploting.html#cb3-9"></a><span class="st">   </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/ageBoxPlot-1.png" width="672" /></p>
<p>We can see in these experiments five experiments there is clearly no benefit to applying a second fungicide application given the values of the recommended _plus treatment were predominantly lower than zero.</p>
<p>For completeness let’s test this with powdery mildew infection commencing 40 - 60 days after planting, instead of greater than 60.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="post-hoc-analysis-and-ploting.html#cb4-1"></a>dat1 <span class="op">%&gt;%</span></span>
<span id="cb4-2"><a href="post-hoc-analysis-and-ploting.html#cb4-2"></a><span class="st">   </span><span class="kw">filter</span>(days2PM <span class="op">&lt;</span><span class="st"> </span><span class="dv">60</span> <span class="op">&amp;</span></span>
<span id="cb4-3"><a href="post-hoc-analysis-and-ploting.html#cb4-3"></a><span class="st">             </span>days2PM <span class="op">&gt;=</span><span class="st"> </span><span class="dv">40</span>) <span class="op">%&gt;%</span></span>
<span id="cb4-4"><a href="post-hoc-analysis-and-ploting.html#cb4-4"></a><span class="st">   </span><span class="kw">filter</span>(spray_management <span class="op">!=</span><span class="st"> &quot;control&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb4-5"><a href="post-hoc-analysis-and-ploting.html#cb4-5"></a><span class="st">   </span><span class="kw">group_by</span>(trial_ref, spray_management) <span class="op">%&gt;%</span></span>
<span id="cb4-6"><a href="post-hoc-analysis-and-ploting.html#cb4-6"></a><span class="st">   </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> spray_management, <span class="dt">y =</span> yield_gain, <span class="dt">colour =</span> trial_ref)) <span class="op">+</span></span>
<span id="cb4-7"><a href="post-hoc-analysis-and-ploting.html#cb4-7"></a><span class="st">   </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></span>
<span id="cb4-8"><a href="post-hoc-analysis-and-ploting.html#cb4-8"></a><span class="st">   </span><span class="kw">scale_fill_usq</span>() <span class="op">+</span></span>
<span id="cb4-9"><a href="post-hoc-analysis-and-ploting.html#cb4-9"></a><span class="st">   </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/PM40_2_59_days-1.png" width="672" /></p>
<p>We can see here all four experiments benefited, on average, from more than one spray.</p>
<p>Let’s estimate the age of the crop based on crop maturity observations, we will use the <code>PM_MB_dat_full</code> which include some observations of crop maturity.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="post-hoc-analysis-and-ploting.html#cb5-1"></a>dat2 &lt;-<span class="st"> </span>PM_MB_dat_full <span class="op">%&gt;%</span></span>
<span id="cb5-2"><a href="post-hoc-analysis-and-ploting.html#cb5-2"></a><span class="st">   </span><span class="kw">mutate</span>(</span>
<span id="cb5-3"><a href="post-hoc-analysis-and-ploting.html#cb5-3"></a>      <span class="dt">flower =</span> lubridate<span class="op">::</span><span class="kw">ymd</span>(flowering_date) <span class="op">-</span><span class="st"> </span>lubridate<span class="op">::</span><span class="kw">ymd</span>(planting_date),</span>
<span id="cb5-4"><a href="post-hoc-analysis-and-ploting.html#cb5-4"></a>      <span class="dt">pod =</span> lubridate<span class="op">::</span><span class="kw">ymd</span>(pod_fill_date) <span class="op">-</span><span class="st"> </span>lubridate<span class="op">::</span><span class="kw">ymd</span>(planting_date),</span>
<span id="cb5-5"><a href="post-hoc-analysis-and-ploting.html#cb5-5"></a>      <span class="dt">late_pod =</span> lubridate<span class="op">::</span><span class="kw">ymd</span>(mid_late_pod_fill) <span class="op">-</span><span class="st"> </span>lubridate<span class="op">::</span><span class="kw">ymd</span>(planting_date)</span>
<span id="cb5-6"><a href="post-hoc-analysis-and-ploting.html#cb5-6"></a>   ) <span class="op">%&gt;%</span></span>
<span id="cb5-7"><a href="post-hoc-analysis-and-ploting.html#cb5-7"></a><span class="st">   </span><span class="kw">select</span>(location, year, flower, pod, late_pod) <span class="op">%&gt;%</span></span>
<span id="cb5-8"><a href="post-hoc-analysis-and-ploting.html#cb5-8"></a><span class="st">   </span><span class="kw">distinct</span>() <span class="op">%&gt;%</span></span>
<span id="cb5-9"><a href="post-hoc-analysis-and-ploting.html#cb5-9"></a><span class="st">   </span><span class="kw">arrange</span>(<span class="kw">desc</span>(flower))</span>
<span id="cb5-10"><a href="post-hoc-analysis-and-ploting.html#cb5-10"></a></span>
<span id="cb5-11"><a href="post-hoc-analysis-and-ploting.html#cb5-11"></a>index1 &lt;-</span>
<span id="cb5-12"><a href="post-hoc-analysis-and-ploting.html#cb5-12"></a><span class="st">   </span><span class="kw">apply</span>(dat2, <span class="dv">1</span> , <span class="cf">function</span>(X)</span>
<span id="cb5-13"><a href="post-hoc-analysis-and-ploting.html#cb5-13"></a>      <span class="op">!</span><span class="st"> </span><span class="kw">all</span>(<span class="kw">is.na</span>(X[<span class="kw">c</span>(<span class="st">&quot;flower&quot;</span>, <span class="st">&quot;pod&quot;</span>, <span class="st">&quot;late_pod&quot;</span>)])))</span>
<span id="cb5-14"><a href="post-hoc-analysis-and-ploting.html#cb5-14"></a></span>
<span id="cb5-15"><a href="post-hoc-analysis-and-ploting.html#cb5-15"></a>dat2[index1,]</span></code></pre></div>
<pre><code>##      location year  flower     pod late_pod
## 1      Goolhi 2013 71 days 85 days  NA days
## 2      Premer 2013 62 days NA days  NA days
## 3   Hermitage 2011 57 days NA days  NA days
## 4    Kingaroy 2012 38 days NA days  NA days
## 6 Marys Mount 2013 NA days 66 days  NA days
## 7  Millmerran 2013 NA days 68 days  75 days
## 8   Hermitage 2016 NA days NA days  72 days
## 9    Kingaroy 2016 NA days 54 days  NA days</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="post-hoc-analysis-and-ploting.html#cb7-1"></a><span class="kw">as.double</span>(<span class="kw">mean</span>(dat2[index1, <span class="st">&quot;flower&quot;</span>], <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## [1] 57</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="post-hoc-analysis-and-ploting.html#cb9-1"></a><span class="kw">as.double</span>(<span class="kw">mean</span>(dat2[index1, <span class="st">&quot;pod&quot;</span>], <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## [1] 68.25</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="post-hoc-analysis-and-ploting.html#cb11-1"></a><span class="kw">as.double</span>(<span class="kw">mean</span>(dat2[index1, <span class="st">&quot;late_pod&quot;</span>], <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## [1] 73.5</code></pre>
<p>We can see that flowering and podding can be variable, and depend on the cumulative degree days.
However, on average flowering starts 57 days after sowing, podding starts 68.25, and late podding 73.5.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="grain-yield-meta-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="import-and-format-data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
