<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Prepare data for meta-analysis | A meta-analysis of powdery mildew yield loss mitigation strategies in Australian mungbean</title>
  <meta name="description" content="A meta-analysis of fungicide use in mungbean to control for yield loss due to powdery mildew." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Prepare data for meta-analysis | A meta-analysis of powdery mildew yield loss mitigation strategies in Australian mungbean" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A meta-analysis of fungicide use in mungbean to control for yield loss due to powdery mildew." />
  <meta name="github-repo" content="OpenPlantPathology/Mungbean_PM" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Prepare data for meta-analysis | A meta-analysis of powdery mildew yield loss mitigation strategies in Australian mungbean" />
  
  <meta name="twitter:description" content="A meta-analysis of fungicide use in mungbean to control for yield loss due to powdery mildew." />
  

<meta name="author" content="Paul Melloy, Emerson Del Ponte and Adam H. Sparks" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="preliminary-analysis.html"/>
<link rel="next" href="grain-yield-meta-analysis.html"/>
<script src="libs/header-attrs-2.3/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Home</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#contents"><i class="fa fa-check"></i><b>1.1</b> Contents</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#other-research-questions-which-are-not-the-focus-of-this-study"><i class="fa fa-check"></i><b>1.2</b> Other research questions, which are not the focus of this study</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#possible-sources-of-variation-in-this-analysis."><i class="fa fa-check"></i><b>1.3</b> Possible sources of variation in this analysis.</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="studies-considered-in-meta-analysis.html"><a href="studies-considered-in-meta-analysis.html"><i class="fa fa-check"></i><b>2</b> Studies considered in meta-analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="studies-considered-in-meta-analysis.html"><a href="studies-considered-in-meta-analysis.html#summary-of-trials"><i class="fa fa-check"></i><b>2.1</b> Summary of trials</a></li>
<li class="chapter" data-level="2.2" data-path="studies-considered-in-meta-analysis.html"><a href="studies-considered-in-meta-analysis.html#powdery-mildew-rating-scales"><i class="fa fa-check"></i><b>2.2</b> Powdery mildew rating scales</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="studies-considered-in-meta-analysis.html"><a href="studies-considered-in-meta-analysis.html#powdery-mildew-rating-scale"><i class="fa fa-check"></i><b>2.2.1</b> 1 - 5 powdery mildew rating scale</a></li>
<li class="chapter" data-level="2.2.2" data-path="studies-considered-in-meta-analysis.html"><a href="studies-considered-in-meta-analysis.html#powdery-mildew-rating-scale-1"><i class="fa fa-check"></i><b>2.2.2</b> 1 - 9 powdery mildew rating scale</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="studies-considered-in-meta-analysis.html"><a href="studies-considered-in-meta-analysis.html#experiment-locations"><i class="fa fa-check"></i><b>2.3</b> Experiment locations</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html"><i class="fa fa-check"></i><b>3</b> Preliminary Analysis</a>
<ul>
<li class="chapter" data-level="3.1" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#explore-and-visualise-data"><i class="fa fa-check"></i><b>3.1</b> Explore and Visualise Data</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#fungicides"><i class="fa fa-check"></i><b>3.1.1</b> Fungicides</a></li>
<li class="chapter" data-level="3.1.2" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#mungbean-cultivars"><i class="fa fa-check"></i><b>3.1.2</b> Mungbean cultivars</a></li>
<li class="chapter" data-level="3.1.3" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#row-spacing"><i class="fa fa-check"></i><b>3.1.3</b> Row spacing</a></li>
<li class="chapter" data-level="3.1.4" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#yield-vs-in-season-rain"><i class="fa fa-check"></i><b>3.1.4</b> Yield vs in-season rain</a></li>
<li class="chapter" data-level="3.1.5" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#season-range-and-first-incidence"><i class="fa fa-check"></i><b>3.1.5</b> Season range and first incidence</a></li>
<li class="chapter" data-level="3.1.6" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#audpc-visualise-raw-data"><i class="fa fa-check"></i><b>3.1.6</b> AUDPC visualise raw data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html"><i class="fa fa-check"></i><b>4</b> Prepare data for meta-analysis</a>
<ul>
<li class="chapter" data-level="4.1" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#set-environment-and-import-data"><i class="fa fa-check"></i><b>4.1</b> Set environment and import data</a></li>
<li class="chapter" data-level="4.2" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#standardising-sample-variance"><i class="fa fa-check"></i><b>4.2</b> Standardising sample variance</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#converting-least-squares-to-sample-variance"><i class="fa fa-check"></i><b>4.2.1</b> Converting least-squares to sample variance</a></li>
<li class="chapter" data-level="4.2.2" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#converting-standard-deviation-to-sample-variance"><i class="fa fa-check"></i><b>4.2.2</b> Converting standard deviation to sample variance</a></li>
<li class="chapter" data-level="4.2.3" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#check-variance-of-data-set"><i class="fa fa-check"></i><b>4.2.3</b> Check variance of data-set</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#reduce-data-set-to-required-variables"><i class="fa fa-check"></i><b>4.3</b> Reduce data set to required variables</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#cluster-fungicide-applications"><i class="fa fa-check"></i><b>4.3.1</b> Cluster fungicide applications</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#test-dose-effect"><i class="fa fa-check"></i><b>4.4</b> Test dose effect</a></li>
<li class="chapter" data-level="4.5" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#disease-pressure-factor"><i class="fa fa-check"></i><b>4.5</b> Disease pressure factor</a></li>
<li class="chapter" data-level="4.6" data-path="preliminary-analysis.html"><a href="preliminary-analysis.html#row-spacing"><i class="fa fa-check"></i><b>4.6</b> Row spacing</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="prepare-data-for-meta-analysis.html"><a href="prepare-data-for-meta-analysis.html#mungbeans-age-and-yield-saved"><i class="fa fa-check"></i><b>4.6.1</b> Mungbeans age and yield saved</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="grain-yield-meta-analysis.html"><a href="grain-yield-meta-analysis.html"><i class="fa fa-check"></i><b>5</b> Grain yield meta-analysis</a>
<ul>
<li class="chapter" data-level="5.0.1" data-path="grain-yield-meta-analysis.html"><a href="grain-yield-meta-analysis.html#formating-the-response-variable"><i class="fa fa-check"></i><b>5.0.1</b> Formating the response variable</a></li>
<li class="chapter" data-level="5.0.2" data-path="grain-yield-meta-analysis.html"><a href="grain-yield-meta-analysis.html#formatting-variance"><i class="fa fa-check"></i><b>5.0.2</b> Formatting Variance</a></li>
<li class="chapter" data-level="5.1" data-path="grain-yield-meta-analysis.html"><a href="grain-yield-meta-analysis.html#metafor-analysis"><i class="fa fa-check"></i><b>5.1</b> metafor analysis</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="grain-yield-meta-analysis.html"><a href="grain-yield-meta-analysis.html#profile-plots"><i class="fa fa-check"></i><b>5.1.1</b> Profile plots</a></li>
<li class="chapter" data-level="5.1.2" data-path="grain-yield-meta-analysis.html"><a href="grain-yield-meta-analysis.html#forest-plot-of-trial-treatment-effect-per-trial"><i class="fa fa-check"></i><b>5.1.2</b> Forest plot of trial treatment effect per trial</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="grain-yield-meta-analysis.html"><a href="grain-yield-meta-analysis.html#netmeta-analysis"><i class="fa fa-check"></i><b>5.2</b> netmeta analysis</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="aupdc-meta-analysis.html"><a href="aupdc-meta-analysis.html"><i class="fa fa-check"></i><b>6</b> AUPDC meta-analysis</a>
<ul>
<li class="chapter" data-level="6.0.1" data-path="aupdc-meta-analysis.html"><a href="aupdc-meta-analysis.html#spray-management-and-audpc"><i class="fa fa-check"></i><b>6.0.1</b> Spray management and AUDPC</a></li>
<li class="chapter" data-level="6.1" data-path="aupdc-meta-analysis.html"><a href="aupdc-meta-analysis.html#aupdc-effect-on-grain-yield-meta-analysis"><i class="fa fa-check"></i><b>6.1</b> AUPDC effect on grain yield meta-analysis</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html"><i class="fa fa-check"></i><b>7</b> Manuscript wire frame</a>
<ul>
<li class="chapter" data-level="7.1" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#who-are-the-intended-readers---list-3-to-5-of-them-by-name"><i class="fa fa-check"></i><b>7.1</b> Who are the intended readers? - list 3 to 5 of them by name</a></li>
<li class="chapter" data-level="7.2" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-did-you-do-limit---50-words"><i class="fa fa-check"></i><b>7.2</b> what did you do? (limit - 50 words)</a></li>
<li class="chapter" data-level="7.3" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#why-did-you-do-it-limit---50-words"><i class="fa fa-check"></i><b>7.3</b> Why did you do it? (limit - 50 words)</a></li>
<li class="chapter" data-level="7.4" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-happened-limit---50-words"><i class="fa fa-check"></i><b>7.4</b> what happened? (limit - 50 words)</a></li>
<li class="chapter" data-level="7.5" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-do-the-results-mean-in-theory-limit---50-words"><i class="fa fa-check"></i><b>7.5</b> What do the results mean in theory? (limit - 50 words)</a></li>
<li class="chapter" data-level="7.6" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-do-the-results-mean-in-practice-limit---50-words"><i class="fa fa-check"></i><b>7.6</b> What do the results mean in practice? (limit - 50 words)</a></li>
<li class="chapter" data-level="7.7" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-is-the-key-benefit-for-your-readers-limit---25-words."><i class="fa fa-check"></i><b>7.7</b> what is the key benefit for your readers? (limit - 25 words).</a></li>
<li class="chapter" data-level="7.8" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#what-remains-unresolved-no-word-limit."><i class="fa fa-check"></i><b>7.8</b> What remains unresolved? (no word limit).</a></li>
<li class="chapter" data-level="7.9" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#introduction"><i class="fa fa-check"></i><b>7.9</b> Introduction</a></li>
<li class="chapter" data-level="7.10" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#materials-and-methods"><i class="fa fa-check"></i><b>7.10</b> Materials and Methods</a></li>
<li class="chapter" data-level="7.11" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#results"><i class="fa fa-check"></i><b>7.11</b> Results</a></li>
<li class="chapter" data-level="7.12" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#discussion"><i class="fa fa-check"></i><b>7.12</b> Discussion</a>
<ul>
<li class="chapter" data-level="7.12.1" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#future-work"><i class="fa fa-check"></i><b>7.12.1</b> Future work</a></li>
</ul></li>
<li class="chapter" data-level="7.13" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#conclusion"><i class="fa fa-check"></i><b>7.13</b> Conclusion</a></li>
<li class="chapter" data-level="7.14" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#supplemental-material"><i class="fa fa-check"></i><b>7.14</b> Supplemental Material</a></li>
<li class="chapter" data-level="7.15" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#data-availability"><i class="fa fa-check"></i><b>7.15</b> Data Availability</a></li>
<li class="chapter" data-level="7.16" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#conflict-of-interest-statement"><i class="fa fa-check"></i><b>7.16</b> Conflict of Interest Statement</a></li>
<li class="chapter" data-level="7.17" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#acknowledgments"><i class="fa fa-check"></i><b>7.17</b> Acknowledgments</a></li>
<li class="chapter" data-level="7.18" data-path="manuscript-wire-frame.html"><a href="manuscript-wire-frame.html#references"><i class="fa fa-check"></i><b>7.18</b> References</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A meta-analysis of powdery mildew yield loss mitigation strategies in Australian mungbean</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="prepare-data-for-meta-analysis" class="section level1" number="4">
<h1><span class="header-section-number">4</span> Prepare data for meta-analysis</h1>
<div id="set-environment-and-import-data" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Set environment and import data</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="prepare-data-for-meta-analysis.html#cb1-1" aria-hidden="true"></a>PM_MB_means &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="kw">here</span>(<span class="st">&quot;cache/1911_PM_MB_means&amp;Ygains.csv&quot;</span>))</span>
<span id="cb1-2"><a href="prepare-data-for-meta-analysis.html#cb1-2" aria-hidden="true"></a></span>
<span id="cb1-3"><a href="prepare-data-for-meta-analysis.html#cb1-3" aria-hidden="true"></a><span class="kw">source</span>(<span class="kw">here</span>(<span class="st">&quot;R/same.R&quot;</span>)) <span class="co"># matches each element of a vector and does not return NAs</span></span></code></pre></div>
</div>
<div id="standardising-sample-variance" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Standardising sample variance</h2>
<p>Meta-analyses use variance from the data to calculate the effect sizes.
The type of variance needs to be the same across all the data incorporated in the meta-analysis.</p>
<p>We are narrowing the meta-analysis to only include treatments using demethylation inhibitors, tebuconazole and propiconazole.
Let’s look at what type of statistical error was reported for the trials that used these fungicides.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="prepare-data-for-meta-analysis.html#cb2-1" aria-hidden="true"></a>PM_MB_means <span class="op">%&gt;%</span></span>
<span id="cb2-2"><a href="prepare-data-for-meta-analysis.html#cb2-2" aria-hidden="true"></a><span class="st">   </span><span class="kw">filter</span>(fungicide_ai <span class="op">==</span><span class="st"> &quot;tebuconazole&quot;</span> <span class="op">|</span></span>
<span id="cb2-3"><a href="prepare-data-for-meta-analysis.html#cb2-3" aria-hidden="true"></a><span class="st">             </span>fungicide_ai <span class="op">==</span><span class="st"> &quot;propiconazole&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb2-4"><a href="prepare-data-for-meta-analysis.html#cb2-4" aria-hidden="true"></a><span class="st">   </span><span class="kw">group_by</span>(trial_ref, location, year , Y_error_type, fungicide_ai) <span class="op">%&gt;%</span></span>
<span id="cb2-5"><a href="prepare-data-for-meta-analysis.html#cb2-5" aria-hidden="true"></a><span class="st">   </span><span class="kw">summarise</span>(<span class="dt">DMI_treatments =</span> <span class="kw">length</span>(Y_error_type)) <span class="op">%&gt;%</span></span>
<span id="cb2-6"><a href="prepare-data-for-meta-analysis.html#cb2-6" aria-hidden="true"></a><span class="st">   </span><span class="kw">arrange</span>(Y_error_type) <span class="op">%&gt;%</span></span>
<span id="cb2-7"><a href="prepare-data-for-meta-analysis.html#cb2-7" aria-hidden="true"></a><span class="st">   </span><span class="kw">select</span>(<span class="op">!</span>fungicide_ai) <span class="op">%&gt;%</span></span>
<span id="cb2-8"><a href="prepare-data-for-meta-analysis.html#cb2-8" aria-hidden="true"></a><span class="st">   </span><span class="kw">kable</span>(<span class="dt">caption =</span> <span class="st">&quot;Number of treatments for each trial and the error type reported&quot;</span>,</span>
<span id="cb2-9"><a href="prepare-data-for-meta-analysis.html#cb2-9" aria-hidden="true"></a>         <span class="dt">align =</span> <span class="st">&quot;c&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb2-10"><a href="prepare-data-for-meta-analysis.html#cb2-10" aria-hidden="true"></a><span class="st">   </span><span class="kw">footnote</span>(<span class="dt">general =</span> <span class="st">&quot;DMI - demethylation inhibitors (tebuconazole and propiconazole).&quot;</span>)</span></code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;trial_ref&#39;, &#39;location&#39;, &#39;year&#39;, &#39;Y_error_type&#39; (override with `.groups` argument)</code></pre>
<table>
<caption>
(#tab:variance_types)Number of treatments for each trial and the error type reported
</caption>
<thead>
<tr>
<th style="text-align:center;">
trial_ref
</th>
<th style="text-align:center;">
location
</th>
<th style="text-align:center;">
year
</th>
<th style="text-align:center;">
Y_error_type
</th>
<th style="text-align:center;">
DMI_treatments
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
mung1112/02
</td>
<td style="text-align:center;">
Kingaroy
</td>
<td style="text-align:center;">
2012
</td>
<td style="text-align:center;">
lsd (P=0.05)
</td>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
mung1112/02
</td>
<td style="text-align:center;">
Kingaroy
</td>
<td style="text-align:center;">
2012
</td>
<td style="text-align:center;">
lsd (P=0.05)
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
AM1303
</td>
<td style="text-align:center;">
Premer
</td>
<td style="text-align:center;">
2013
</td>
<td style="text-align:center;">
stdev
</td>
<td style="text-align:center;">
3
</td>
</tr>
<tr>
<td style="text-align:center;">
AM1304
</td>
<td style="text-align:center;">
Marys Mount
</td>
<td style="text-align:center;">
2013
</td>
<td style="text-align:center;">
stdev
</td>
<td style="text-align:center;">
3
</td>
</tr>
<tr>
<td style="text-align:center;">
AM1305
</td>
<td style="text-align:center;">
Goolhi
</td>
<td style="text-align:center;">
2013
</td>
<td style="text-align:center;">
stdev
</td>
<td style="text-align:center;">
3
</td>
</tr>
<tr>
<td style="text-align:center;">
BB1305
</td>
<td style="text-align:center;">
Millmerran
</td>
<td style="text-align:center;">
2013
</td>
<td style="text-align:center;">
stdev
</td>
<td style="text-align:center;">
3
</td>
</tr>
<tr>
<td style="text-align:center;">
mung1011/01
</td>
<td style="text-align:center;">
Hermitage
</td>
<td style="text-align:center;">
2011
</td>
<td style="text-align:center;">
stdev
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
mung1011/02
</td>
<td style="text-align:center;">
Kingaroy
</td>
<td style="text-align:center;">
2011
</td>
<td style="text-align:center;">
stdev
</td>
<td style="text-align:center;">
6
</td>
</tr>
<tr>
<td style="text-align:center;">
mung1415/01
</td>
<td style="text-align:center;">
Hermitage
</td>
<td style="text-align:center;">
2015
</td>
<td style="text-align:center;">
stdev
</td>
<td style="text-align:center;">
5
</td>
</tr>
<tr>
<td style="text-align:center;">
mung1516/01
</td>
<td style="text-align:center;">
Hermitage
</td>
<td style="text-align:center;">
2016
</td>
<td style="text-align:center;">
stdev
</td>
<td style="text-align:center;">
6
</td>
</tr>
<tr>
<td style="text-align:center;">
mung1516/02
</td>
<td style="text-align:center;">
Kingaroy
</td>
<td style="text-align:center;">
2016
</td>
<td style="text-align:center;">
stdev
</td>
<td style="text-align:center;">
6
</td>
</tr>
<tr>
<td style="text-align:center;">
mung1617/01
</td>
<td style="text-align:center;">
Hermitage
</td>
<td style="text-align:center;">
2017
</td>
<td style="text-align:center;">
stdev
</td>
<td style="text-align:center;">
15
</td>
</tr>
<tr>
<td style="text-align:center;">
mung1617/01
</td>
<td style="text-align:center;">
Hermitage
</td>
<td style="text-align:center;">
2017
</td>
<td style="text-align:center;">
stdev
</td>
<td style="text-align:center;">
15
</td>
</tr>
<tr>
<td style="text-align:center;">
mung1617/02
</td>
<td style="text-align:center;">
Missen Flats
</td>
<td style="text-align:center;">
2017
</td>
<td style="text-align:center;">
stdev
</td>
<td style="text-align:center;">
15
</td>
</tr>
<tr>
<td style="text-align:center;">
mung1617/02
</td>
<td style="text-align:center;">
Missen Flats
</td>
<td style="text-align:center;">
2017
</td>
<td style="text-align:center;">
stdev
</td>
<td style="text-align:center;">
15
</td>
</tr>
<tr>
<td style="text-align:center;">
mung1718/01
</td>
<td style="text-align:center;">
Wellcamp
</td>
<td style="text-align:center;">
2018
</td>
<td style="text-align:center;">
stdev
</td>
<td style="text-align:center;">
6
</td>
</tr>
<tr>
<td style="text-align:center;">
mung1718/01
</td>
<td style="text-align:center;">
Wellcamp
</td>
<td style="text-align:center;">
2018
</td>
<td style="text-align:center;">
stdev
</td>
<td style="text-align:center;">
6
</td>
</tr>
<tr>
<td style="text-align:center;">
mung1819/01
</td>
<td style="text-align:center;">
Hermitage
</td>
<td style="text-align:center;">
2019
</td>
<td style="text-align:center;">
stdev
</td>
<td style="text-align:center;">
3
</td>
</tr>
<tr>
<td style="text-align:center;">
mung1819/02
</td>
<td style="text-align:center;">
Hermitage
</td>
<td style="text-align:center;">
2019
</td>
<td style="text-align:center;">
stdev
</td>
<td style="text-align:center;">
3
</td>
</tr>
<tr>
<td style="text-align:center;">
mung1112/01
</td>
<td style="text-align:center;">
Gatton
</td>
<td style="text-align:center;">
2012
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
4
</td>
</tr>
<tr>
<td style="text-align:center;">
mung1112/01
</td>
<td style="text-align:center;">
Gatton
</td>
<td style="text-align:center;">
2012
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:center;">
mung1516/03
</td>
<td style="text-align:center;">
Emerald
</td>
<td style="text-align:center;">
2016
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
6
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<span style="font-style: italic;">Note: </span>
</td>
</tr>
<tr>
<td style="padding: 0; border: 0;" colspan="100%">
<sup></sup> DMI - demethylation inhibitors (tebuconazole and propiconazole).
</td>
</tr>
</tfoot>
</table>
<p>The experiment summaries report either standard deviation, least square differences or no error term (<code>NA</code>).
First we will convert LSD and standard deviation to sample variance.
Then we will impute variances for the trials, which did not report any form of variance (<code>NA</code>).</p>
<div id="converting-least-squares-to-sample-variance" class="section level3" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Converting least-squares to sample variance</h3>
<p>First let’s get a list the of trials that reported LSD.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="prepare-data-for-meta-analysis.html#cb4-1" aria-hidden="true"></a>Trials &lt;-<span class="st"> </span>PM_MB_means <span class="op">%&gt;%</span></span>
<span id="cb4-2"><a href="prepare-data-for-meta-analysis.html#cb4-2" aria-hidden="true"></a><span class="st">   </span><span class="kw">filter</span>(Y_error_type <span class="op">==</span><span class="st"> &quot;lsd (P=0.05)&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb4-3"><a href="prepare-data-for-meta-analysis.html#cb4-3" aria-hidden="true"></a><span class="st">   </span><span class="kw">select</span>(trial_ref) <span class="op">%&gt;%</span></span>
<span id="cb4-4"><a href="prepare-data-for-meta-analysis.html#cb4-4" aria-hidden="true"></a><span class="st">   </span><span class="kw">distinct</span>()</span>
<span id="cb4-5"><a href="prepare-data-for-meta-analysis.html#cb4-5" aria-hidden="true"></a>Trials</span></code></pre></div>
<pre><code>##     trial_ref
## 1 mung0001/01
## 2 mung1112/02</code></pre>
<p>Let’s use this list of trials to subset the data and calculate sampling variances.</p>
<p>We will follow the method of converting ‘least square differences’ (LSD) to sampling variance reported by <a href="https://apsjournals.apsnet.org/doi/10.1094/PHYTO-08-10-0221">Nugugi et.al (2011)</a>.
A <a href="https://www.statisticshowto.datasciencecentral.com/tables/t-distribution-table/">table of T-critical values</a> was consulted to select the T-crit value in the equation.
Our data contained 30 degrees of freedom which equates to a ‘T-crit’ value of 1.697.</p>
<div class="figure">
<img src="Paul_etal_2008.PNG" alt="" />
<p class="caption">Calculating sampling variance from mean squared error Paul et al. (2008)</p>
</div>
<p><code>Tcrit</code> is the T critical value for which there is significant difference between two groups.
This value is the same for both trials “mung1112/01” and “mung1112/02”.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="prepare-data-for-meta-analysis.html#cb6-1" aria-hidden="true"></a>Tcrit &lt;-<span class="st"> </span><span class="fl">2.042</span> <span class="co"># 0.05 and DFw = 30</span></span>
<span id="cb6-2"><a href="prepare-data-for-meta-analysis.html#cb6-2" aria-hidden="true"></a></span>
<span id="cb6-3"><a href="prepare-data-for-meta-analysis.html#cb6-3" aria-hidden="true"></a><span class="cf">for</span> (i <span class="cf">in</span> Trials<span class="op">$</span>trial_ref) {</span>
<span id="cb6-4"><a href="prepare-data-for-meta-analysis.html#cb6-4" aria-hidden="true"></a>   DFw &lt;-</span>
<span id="cb6-5"><a href="prepare-data-for-meta-analysis.html#cb6-5" aria-hidden="true"></a><span class="st">      </span><span class="kw">sum</span>(PM_MB_means[PM_MB_means<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>i, ]<span class="op">$</span>replicates) <span class="op">-</span></span>
<span id="cb6-6"><a href="prepare-data-for-meta-analysis.html#cb6-6" aria-hidden="true"></a><span class="st">      </span><span class="kw">length</span>(PM_MB_means[PM_MB_means<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>i, ]<span class="op">$</span>replicates) <span class="co"># degrees of freedom within groups</span></span>
<span id="cb6-7"><a href="prepare-data-for-meta-analysis.html#cb6-7" aria-hidden="true"></a>   </span>
<span id="cb6-8"><a href="prepare-data-for-meta-analysis.html#cb6-8" aria-hidden="true"></a>   LSD &lt;-</span>
<span id="cb6-9"><a href="prepare-data-for-meta-analysis.html#cb6-9" aria-hidden="true"></a><span class="st">      </span>PM_MB_means[PM_MB_means<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>i, ]<span class="op">$</span>yield_error[<span class="dv">1</span>]</span>
<span id="cb6-10"><a href="prepare-data-for-meta-analysis.html#cb6-10" aria-hidden="true"></a>   </span>
<span id="cb6-11"><a href="prepare-data-for-meta-analysis.html#cb6-11" aria-hidden="true"></a>   </span>
<span id="cb6-12"><a href="prepare-data-for-meta-analysis.html#cb6-12" aria-hidden="true"></a>   V_yield &lt;-</span>
<span id="cb6-13"><a href="prepare-data-for-meta-analysis.html#cb6-13" aria-hidden="true"></a><span class="st">      </span>(PM_MB_means[PM_MB_means<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>i, ]<span class="op">$</span>replicates[<span class="dv">1</span>] <span class="op">*</span><span class="st"> </span></span>
<span id="cb6-14"><a href="prepare-data-for-meta-analysis.html#cb6-14" aria-hidden="true"></a><span class="st">          </span>(LSD <span class="op">/</span><span class="st"> </span>Tcrit) <span class="op">^</span><span class="st"> </span><span class="dv">2</span>) <span class="op">/</span><span class="st"> </span><span class="dv">2</span> </span>
<span id="cb6-15"><a href="prepare-data-for-meta-analysis.html#cb6-15" aria-hidden="true"></a>   <span class="co"># method - Nugugi et.al (2011) DOI: 10.1094/phyto-08-10-0221</span></span>
<span id="cb6-16"><a href="prepare-data-for-meta-analysis.html#cb6-16" aria-hidden="true"></a></span>
<span id="cb6-17"><a href="prepare-data-for-meta-analysis.html#cb6-17" aria-hidden="true"></a>   <span class="cf">for</span> (j <span class="cf">in</span> <span class="kw">seq_along</span>(PM_MB_means[PM_MB_means<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>i,]<span class="op">$</span>replicates)) {</span>
<span id="cb6-18"><a href="prepare-data-for-meta-analysis.html#cb6-18" aria-hidden="true"></a>      <span class="cf">if</span> (j <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) {</span>
<span id="cb6-19"><a href="prepare-data-for-meta-analysis.html#cb6-19" aria-hidden="true"></a>         Sv &lt;-</span>
<span id="cb6-20"><a href="prepare-data-for-meta-analysis.html#cb6-20" aria-hidden="true"></a><span class="st">            </span><span class="kw">vector</span>(<span class="dt">length =</span> <span class="kw">length</span>(PM_MB_means[PM_MB_means<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>i,]<span class="op">$</span>replicates))</span>
<span id="cb6-21"><a href="prepare-data-for-meta-analysis.html#cb6-21" aria-hidden="true"></a>      } <span class="co"># reset Sv vector if this is the first loop</span></span>
<span id="cb6-22"><a href="prepare-data-for-meta-analysis.html#cb6-22" aria-hidden="true"></a>      </span>
<span id="cb6-23"><a href="prepare-data-for-meta-analysis.html#cb6-23" aria-hidden="true"></a>      </span>
<span id="cb6-24"><a href="prepare-data-for-meta-analysis.html#cb6-24" aria-hidden="true"></a>      Sv[j] =<span class="st"> </span>V_yield <span class="op">/</span></span>
<span id="cb6-25"><a href="prepare-data-for-meta-analysis.html#cb6-25" aria-hidden="true"></a><span class="st">         </span>PM_MB_means[PM_MB_means<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>i,]<span class="op">$</span>replicates[j]</span>
<span id="cb6-26"><a href="prepare-data-for-meta-analysis.html#cb6-26" aria-hidden="true"></a>      </span>
<span id="cb6-27"><a href="prepare-data-for-meta-analysis.html#cb6-27" aria-hidden="true"></a>   }</span>
<span id="cb6-28"><a href="prepare-data-for-meta-analysis.html#cb6-28" aria-hidden="true"></a>   </span>
<span id="cb6-29"><a href="prepare-data-for-meta-analysis.html#cb6-29" aria-hidden="true"></a>   <span class="co"># Replace the values in the dataset</span></span>
<span id="cb6-30"><a href="prepare-data-for-meta-analysis.html#cb6-30" aria-hidden="true"></a>   PM_MB_means[PM_MB_means<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>i,]<span class="op">$</span>yield_error &lt;-</span>
<span id="cb6-31"><a href="prepare-data-for-meta-analysis.html#cb6-31" aria-hidden="true"></a><span class="st">      </span>Sv</span>
<span id="cb6-32"><a href="prepare-data-for-meta-analysis.html#cb6-32" aria-hidden="true"></a>   PM_MB_means[PM_MB_means<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>i,]<span class="op">$</span>Y_error_type &lt;-</span>
<span id="cb6-33"><a href="prepare-data-for-meta-analysis.html#cb6-33" aria-hidden="true"></a><span class="st">      &quot;SamplingVariance&quot;</span></span>
<span id="cb6-34"><a href="prepare-data-for-meta-analysis.html#cb6-34" aria-hidden="true"></a>}</span></code></pre></div>
</div>
<div id="converting-standard-deviation-to-sample-variance" class="section level3" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Converting standard deviation to sample variance</h3>
<p>Now to estimate the variance from the standard deviation.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="prepare-data-for-meta-analysis.html#cb7-1" aria-hidden="true"></a><span class="co"># subset data by those which describe the Yield error with standard deviation</span></span>
<span id="cb7-2"><a href="prepare-data-for-meta-analysis.html#cb7-2" aria-hidden="true"></a>Trials &lt;-<span class="st"> </span>PM_MB_means <span class="op">%&gt;%</span></span>
<span id="cb7-3"><a href="prepare-data-for-meta-analysis.html#cb7-3" aria-hidden="true"></a><span class="st">   </span><span class="kw">filter</span>(Y_error_type <span class="op">==</span><span class="st"> &quot;stdev&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb7-4"><a href="prepare-data-for-meta-analysis.html#cb7-4" aria-hidden="true"></a><span class="st">   </span><span class="kw">select</span>(trial_ref) <span class="op">%&gt;%</span></span>
<span id="cb7-5"><a href="prepare-data-for-meta-analysis.html#cb7-5" aria-hidden="true"></a><span class="st">   </span><span class="kw">distinct</span>()</span>
<span id="cb7-6"><a href="prepare-data-for-meta-analysis.html#cb7-6" aria-hidden="true"></a></span>
<span id="cb7-7"><a href="prepare-data-for-meta-analysis.html#cb7-7" aria-hidden="true"></a></span>
<span id="cb7-8"><a href="prepare-data-for-meta-analysis.html#cb7-8" aria-hidden="true"></a><span class="co"># calculate the Sampling variance from the standard deviation</span></span>
<span id="cb7-9"><a href="prepare-data-for-meta-analysis.html#cb7-9" aria-hidden="true"></a><span class="co"># standard error of the mean equals the standard deviation divided by the square</span></span>
<span id="cb7-10"><a href="prepare-data-for-meta-analysis.html#cb7-10" aria-hidden="true"></a><span class="co">#  root of the number of samples</span></span>
<span id="cb7-11"><a href="prepare-data-for-meta-analysis.html#cb7-11" aria-hidden="true"></a><span class="co"># Sv &lt;- sem^2 &lt;- stdev/sqrt(n)</span></span>
<span id="cb7-12"><a href="prepare-data-for-meta-analysis.html#cb7-12" aria-hidden="true"></a><span class="co"># Sampling variance equals the square of the standard error.</span></span>
<span id="cb7-13"><a href="prepare-data-for-meta-analysis.html#cb7-13" aria-hidden="true"></a><span class="co"># Sv &lt;- (stdev/sqrt(n))^2</span></span>
<span id="cb7-14"><a href="prepare-data-for-meta-analysis.html#cb7-14" aria-hidden="true"></a></span>
<span id="cb7-15"><a href="prepare-data-for-meta-analysis.html#cb7-15" aria-hidden="true"></a><span class="co"># Therefore</span></span>
<span id="cb7-16"><a href="prepare-data-for-meta-analysis.html#cb7-16" aria-hidden="true"></a></span>
<span id="cb7-17"><a href="prepare-data-for-meta-analysis.html#cb7-17" aria-hidden="true"></a><span class="cf">for</span> (j <span class="cf">in</span> <span class="kw">seq_along</span>(PM_MB_means[PM_MB_means<span class="op">$</span>trial_ref <span class="op">%in%</span><span class="st"> </span>Trials<span class="op">$</span>trial_ref,]<span class="op">$</span>yield_error)) {</span>
<span id="cb7-18"><a href="prepare-data-for-meta-analysis.html#cb7-18" aria-hidden="true"></a>   <span class="cf">if</span> (j <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) {</span>
<span id="cb7-19"><a href="prepare-data-for-meta-analysis.html#cb7-19" aria-hidden="true"></a>      Sv &lt;-</span>
<span id="cb7-20"><a href="prepare-data-for-meta-analysis.html#cb7-20" aria-hidden="true"></a><span class="st">         </span><span class="kw">vector</span>(<span class="dt">length =</span> <span class="kw">length</span>(PM_MB_means[PM_MB_means<span class="op">$</span>trial_ref <span class="op">%in%</span><span class="st"> </span>Trials<span class="op">$</span>trial_ref,]<span class="op">$</span>yield_error))</span>
<span id="cb7-21"><a href="prepare-data-for-meta-analysis.html#cb7-21" aria-hidden="true"></a>   }<span class="co"># create empty vector at first iteration with length of j</span></span>
<span id="cb7-22"><a href="prepare-data-for-meta-analysis.html#cb7-22" aria-hidden="true"></a>   </span>
<span id="cb7-23"><a href="prepare-data-for-meta-analysis.html#cb7-23" aria-hidden="true"></a>   Sv[j] =<span class="st"> </span>(PM_MB_means[PM_MB_means<span class="op">$</span>trial_ref <span class="op">%in%</span><span class="st"> </span>Trials<span class="op">$</span>trial_ref,]<span class="op">$</span>yield_error[j]) <span class="op">^</span><span class="st"> </span><span class="dv">2</span></span>
<span id="cb7-24"><a href="prepare-data-for-meta-analysis.html#cb7-24" aria-hidden="true"></a>}</span>
<span id="cb7-25"><a href="prepare-data-for-meta-analysis.html#cb7-25" aria-hidden="true"></a></span>
<span id="cb7-26"><a href="prepare-data-for-meta-analysis.html#cb7-26" aria-hidden="true"></a></span>
<span id="cb7-27"><a href="prepare-data-for-meta-analysis.html#cb7-27" aria-hidden="true"></a><span class="co"># and replacing the values in the dataset</span></span>
<span id="cb7-28"><a href="prepare-data-for-meta-analysis.html#cb7-28" aria-hidden="true"></a>PM_MB_means[PM_MB_means<span class="op">$</span>trial_ref <span class="op">%in%</span><span class="st"> </span>Trials<span class="op">$</span>trial_ref,]<span class="op">$</span>yield_error &lt;-</span>
<span id="cb7-29"><a href="prepare-data-for-meta-analysis.html#cb7-29" aria-hidden="true"></a><span class="st">   </span>Sv</span>
<span id="cb7-30"><a href="prepare-data-for-meta-analysis.html#cb7-30" aria-hidden="true"></a>PM_MB_means[PM_MB_means<span class="op">$</span>trial_ref <span class="op">%in%</span><span class="st"> </span>Trials<span class="op">$</span>trial_ref,]<span class="op">$</span>Y_error_type &lt;-</span>
<span id="cb7-31"><a href="prepare-data-for-meta-analysis.html#cb7-31" aria-hidden="true"></a><span class="st">   &quot;SamplingVariance&quot;</span></span></code></pre></div>
</div>
<div id="check-variance-of-data-set" class="section level3" number="4.2.3">
<h3><span class="header-section-number">4.2.3</span> Check variance of data-set</h3>
<p>Our data currently uses sample variance to define the yield error.
We should expect that when yield increases so does the variance.
Let’s quickly plot this to check.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="prepare-data-for-meta-analysis.html#cb8-1" aria-hidden="true"></a><span class="co"># redefine sample variance calculated from mean square</span></span>
<span id="cb8-2"><a href="prepare-data-for-meta-analysis.html#cb8-2" aria-hidden="true"></a>PM_MB_means<span class="op">$</span>vi &lt;-</span>
<span id="cb8-3"><a href="prepare-data-for-meta-analysis.html#cb8-3" aria-hidden="true"></a><span class="st">   </span>PM_MB_means<span class="op">$</span>Y_Msquare <span class="op">/</span></span>
<span id="cb8-4"><a href="prepare-data-for-meta-analysis.html#cb8-4" aria-hidden="true"></a><span class="st">   </span>(PM_MB_means<span class="op">$</span>n)</span>
<span id="cb8-5"><a href="prepare-data-for-meta-analysis.html#cb8-5" aria-hidden="true"></a></span>
<span id="cb8-6"><a href="prepare-data-for-meta-analysis.html#cb8-6" aria-hidden="true"></a>PM_MB_means <span class="op">%&gt;%</span></span>
<span id="cb8-7"><a href="prepare-data-for-meta-analysis.html#cb8-7" aria-hidden="true"></a><span class="st">   </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> grain_yield.t.ha., <span class="dt">y =</span> vi)) <span class="op">+</span></span>
<span id="cb8-8"><a href="prepare-data-for-meta-analysis.html#cb8-8" aria-hidden="true"></a><span class="st">   </span><span class="kw">geom_point</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 104 rows containing missing values (geom_point).</code></pre>
<p><img src="_main_files/figure-html/Var_mean_sqaures-1.png" width="672" /></p>
<p>We see here that the sample variance generally decreases or has no association with the grain yield.
This might be due to the unpredictable nature of mungbeans, however going forward we will use mean squares, which defines between trial variation and is the more generic error term.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="prepare-data-for-meta-analysis.html#cb10-1" aria-hidden="true"></a>PM_MB_means <span class="op">%&gt;%</span></span>
<span id="cb10-2"><a href="prepare-data-for-meta-analysis.html#cb10-2" aria-hidden="true"></a><span class="st">   </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> grain_yield.t.ha., <span class="dt">y =</span> Y_Msquare)) <span class="op">+</span></span>
<span id="cb10-3"><a href="prepare-data-for-meta-analysis.html#cb10-3" aria-hidden="true"></a><span class="st">   </span><span class="kw">geom_point</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 104 rows containing missing values (geom_point).</code></pre>
<p><img src="_main_files/figure-html/Var_MeanSquarePlot-1.png" width="672" /></p>
</div>
</div>
<div id="reduce-data-set-to-required-variables" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Reduce data set to required variables</h2>
<p>Let’s tidy up the data set into a data frame of only the variables, which are required for the analysis.</p>
<p>First remove the irrelevant columns/variables.
Then calculate fungicide application timing variables relative to the first sign of disease.
Entries with <code>NA</code> in the grain yield or powdery mildew severity are also removed from the data.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="prepare-data-for-meta-analysis.html#cb12-1" aria-hidden="true"></a><span class="kw">source</span>(<span class="st">&quot;R/slimming_PM_dat.R&quot;</span>) <span class="co"># see R script for the code, which reduces the data.</span></span>
<span id="cb12-2"><a href="prepare-data-for-meta-analysis.html#cb12-2" aria-hidden="true"></a></span>
<span id="cb12-3"><a href="prepare-data-for-meta-analysis.html#cb12-3" aria-hidden="true"></a>slim_PM_dat <span class="op">%&lt;&gt;%</span></span>
<span id="cb12-4"><a href="prepare-data-for-meta-analysis.html#cb12-4" aria-hidden="true"></a><span class="st">   </span><span class="kw">mutate</span>(<span class="dt">fungicide_timing_1 =</span> fungicide_application_<span class="dv">1</span> <span class="op">-</span><span class="st"> </span>first_sign_disease) <span class="op">%&gt;%</span></span>
<span id="cb12-5"><a href="prepare-data-for-meta-analysis.html#cb12-5" aria-hidden="true"></a><span class="st">   </span><span class="kw">mutate</span>(<span class="dt">fungicide_timing_2 =</span> fungicide_application_<span class="dv">2</span> <span class="op">-</span><span class="st"> </span>fungicide_application_<span class="dv">1</span>) <span class="op">%&gt;%</span></span>
<span id="cb12-6"><a href="prepare-data-for-meta-analysis.html#cb12-6" aria-hidden="true"></a><span class="st">   </span><span class="kw">mutate</span>(<span class="dt">fungicide_timing_3 =</span> fungicide_application_<span class="dv">3</span> <span class="op">-</span><span class="st"> </span>fungicide_application_<span class="dv">2</span>) <span class="op">%&gt;%</span></span>
<span id="cb12-7"><a href="prepare-data-for-meta-analysis.html#cb12-7" aria-hidden="true"></a><span class="st">   </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(grain_yield.t.ha)) <span class="op">%&gt;%</span></span>
<span id="cb12-8"><a href="prepare-data-for-meta-analysis.html#cb12-8" aria-hidden="true"></a><span class="st">   </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(PM_final_severity))</span></code></pre></div>
<div id="cluster-fungicide-applications" class="section level3" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Cluster fungicide applications</h3>
<p>We are going to define ‘fungicide application timing’ as a categorical variable, relative to the first sign of powdery mildew.</p>
<p>These categorical variables are named:</p>
<ul>
<li><p><strong>Early</strong>: First fungicide application was prior to first sign of disease.</p></li>
<li><p><strong>Recommended</strong>: First fungicide application was applied on the day powdery mildew was observed, or within three days of first sign.</p></li>
<li><p><strong>Late</strong>: First fungicide application was four or more days after first sign of disease being observed.
Follow up fungicide applications (cluster_2 and cluster_3) were also categorised as either early, recommended or late.</p></li>
</ul>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="prepare-data-for-meta-analysis.html#cb13-1" aria-hidden="true"></a>slim_PM_dat <span class="op">%&lt;&gt;%</span></span>
<span id="cb13-2"><a href="prepare-data-for-meta-analysis.html#cb13-2" aria-hidden="true"></a><span class="st">   </span><span class="kw">mutate</span>(</span>
<span id="cb13-3"><a href="prepare-data-for-meta-analysis.html#cb13-3" aria-hidden="true"></a>      <span class="dt">cluster_1 =</span> <span class="kw">case_when</span>(</span>
<span id="cb13-4"><a href="prepare-data-for-meta-analysis.html#cb13-4" aria-hidden="true"></a>         fungicide_timing_<span class="dv">1</span> <span class="op">&lt;</span><span class="st"> </span><span class="dv">0</span> <span class="op">~</span><span class="st"> &quot;Early&quot;</span>,</span>
<span id="cb13-5"><a href="prepare-data-for-meta-analysis.html#cb13-5" aria-hidden="true"></a>         fungicide_timing_<span class="dv">1</span> <span class="op">&gt;=</span><span class="st"> </span><span class="dv">0</span> <span class="op">&amp;</span></span>
<span id="cb13-6"><a href="prepare-data-for-meta-analysis.html#cb13-6" aria-hidden="true"></a><span class="st">            </span>fungicide_timing_<span class="dv">1</span> <span class="op">&lt;</span><span class="st"> </span><span class="dv">4</span> <span class="op">~</span><span class="st"> &quot;Recommended&quot;</span>,</span>
<span id="cb13-7"><a href="prepare-data-for-meta-analysis.html#cb13-7" aria-hidden="true"></a>         <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> &quot;Late&quot;</span></span>
<span id="cb13-8"><a href="prepare-data-for-meta-analysis.html#cb13-8" aria-hidden="true"></a>      )</span>
<span id="cb13-9"><a href="prepare-data-for-meta-analysis.html#cb13-9" aria-hidden="true"></a>   ) <span class="op">%&gt;%</span></span>
<span id="cb13-10"><a href="prepare-data-for-meta-analysis.html#cb13-10" aria-hidden="true"></a><span class="st">   </span><span class="kw">mutate</span>(</span>
<span id="cb13-11"><a href="prepare-data-for-meta-analysis.html#cb13-11" aria-hidden="true"></a>      <span class="dt">cluster_2 =</span> <span class="kw">case_when</span>(</span>
<span id="cb13-12"><a href="prepare-data-for-meta-analysis.html#cb13-12" aria-hidden="true"></a>         <span class="kw">is.na</span>(fungicide_timing_<span class="dv">2</span>) <span class="op">~</span><span class="st"> </span><span class="ot">NA_character_</span>,</span>
<span id="cb13-13"><a href="prepare-data-for-meta-analysis.html#cb13-13" aria-hidden="true"></a>         fungicide_timing_<span class="dv">2</span> <span class="op">&lt;</span><span class="st"> </span><span class="dv">13</span> <span class="op">~</span><span class="st"> &quot;Early&quot;</span>,</span>
<span id="cb13-14"><a href="prepare-data-for-meta-analysis.html#cb13-14" aria-hidden="true"></a>         fungicide_timing_<span class="dv">2</span> <span class="op">&gt;=</span><span class="st"> </span><span class="dv">13</span> <span class="op">&amp;</span></span>
<span id="cb13-15"><a href="prepare-data-for-meta-analysis.html#cb13-15" aria-hidden="true"></a><span class="st">            </span>fungicide_timing_<span class="dv">2</span> <span class="op">&lt;</span><span class="st"> </span><span class="dv">17</span> <span class="op">~</span><span class="st"> &quot;Recommended&quot;</span>,</span>
<span id="cb13-16"><a href="prepare-data-for-meta-analysis.html#cb13-16" aria-hidden="true"></a>         <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> &quot;Late&quot;</span></span>
<span id="cb13-17"><a href="prepare-data-for-meta-analysis.html#cb13-17" aria-hidden="true"></a>      )</span>
<span id="cb13-18"><a href="prepare-data-for-meta-analysis.html#cb13-18" aria-hidden="true"></a>   ) <span class="op">%&gt;%</span></span>
<span id="cb13-19"><a href="prepare-data-for-meta-analysis.html#cb13-19" aria-hidden="true"></a><span class="st">   </span><span class="kw">mutate</span>(</span>
<span id="cb13-20"><a href="prepare-data-for-meta-analysis.html#cb13-20" aria-hidden="true"></a>      <span class="dt">cluster_3 =</span> <span class="kw">case_when</span>(</span>
<span id="cb13-21"><a href="prepare-data-for-meta-analysis.html#cb13-21" aria-hidden="true"></a>         fungicide_timing_<span class="dv">3</span> <span class="op">&lt;</span><span class="st"> </span><span class="dv">14</span> <span class="op">~</span><span class="st"> &quot;Early&quot;</span>,</span>
<span id="cb13-22"><a href="prepare-data-for-meta-analysis.html#cb13-22" aria-hidden="true"></a>         <span class="kw">is.na</span>(fungicide_timing_<span class="dv">3</span>) <span class="op">~</span><span class="st"> </span><span class="ot">NA_character_</span>,</span>
<span id="cb13-23"><a href="prepare-data-for-meta-analysis.html#cb13-23" aria-hidden="true"></a>         <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> &quot;Recommended&quot;</span></span>
<span id="cb13-24"><a href="prepare-data-for-meta-analysis.html#cb13-24" aria-hidden="true"></a>      )</span>
<span id="cb13-25"><a href="prepare-data-for-meta-analysis.html#cb13-25" aria-hidden="true"></a>   )</span></code></pre></div>
<p>Let’s look at these clusters to see where we have the most degrees of freedom.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="prepare-data-for-meta-analysis.html#cb14-1" aria-hidden="true"></a>clusters &lt;-</span>
<span id="cb14-2"><a href="prepare-data-for-meta-analysis.html#cb14-2" aria-hidden="true"></a><span class="st">   </span><span class="kw">unique</span>(slim_PM_dat[<span class="kw">c</span>(<span class="st">&quot;cluster_1&quot;</span>, <span class="st">&quot;cluster_2&quot;</span>, <span class="st">&quot;cluster_3&quot;</span>)])</span>
<span id="cb14-3"><a href="prepare-data-for-meta-analysis.html#cb14-3" aria-hidden="true"></a></span>
<span id="cb14-4"><a href="prepare-data-for-meta-analysis.html#cb14-4" aria-hidden="true"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(clusters)) {</span>
<span id="cb14-5"><a href="prepare-data-for-meta-analysis.html#cb14-5" aria-hidden="true"></a>   <span class="cf">if</span> (i <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) {</span>
<span id="cb14-6"><a href="prepare-data-for-meta-analysis.html#cb14-6" aria-hidden="true"></a>      clusters<span class="op">$</span>n &lt;-<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb14-7"><a href="prepare-data-for-meta-analysis.html#cb14-7" aria-hidden="true"></a>      clusters<span class="op">$</span>n_x_trial &lt;-<span class="st"> </span><span class="ot">NA</span></span>
<span id="cb14-8"><a href="prepare-data-for-meta-analysis.html#cb14-8" aria-hidden="true"></a>   }</span>
<span id="cb14-9"><a href="prepare-data-for-meta-analysis.html#cb14-9" aria-hidden="true"></a>   </span>
<span id="cb14-10"><a href="prepare-data-for-meta-analysis.html#cb14-10" aria-hidden="true"></a>   clusters[i, <span class="st">&quot;n&quot;</span>] &lt;-</span>
<span id="cb14-11"><a href="prepare-data-for-meta-analysis.html#cb14-11" aria-hidden="true"></a><span class="st">      </span><span class="kw">nrow</span>(slim_PM_dat[<span class="kw">same</span>(slim_PM_dat<span class="op">$</span>cluster_<span class="dv">1</span>, clusters[i, <span class="st">&quot;cluster_1&quot;</span>]) <span class="op">&amp;</span></span>
<span id="cb14-12"><a href="prepare-data-for-meta-analysis.html#cb14-12" aria-hidden="true"></a><span class="st">                          </span><span class="kw">same</span>(slim_PM_dat<span class="op">$</span>cluster_<span class="dv">2</span>, clusters[i, <span class="st">&quot;cluster_2&quot;</span>]) <span class="op">&amp;</span></span>
<span id="cb14-13"><a href="prepare-data-for-meta-analysis.html#cb14-13" aria-hidden="true"></a><span class="st">                          </span><span class="kw">same</span>(slim_PM_dat<span class="op">$</span>cluster_<span class="dv">3</span>, clusters[i, <span class="st">&quot;cluster_3&quot;</span>]),])</span>
<span id="cb14-14"><a href="prepare-data-for-meta-analysis.html#cb14-14" aria-hidden="true"></a>   </span>
<span id="cb14-15"><a href="prepare-data-for-meta-analysis.html#cb14-15" aria-hidden="true"></a>   clusters[i, <span class="st">&quot;n_x_trial&quot;</span>] &lt;-</span>
<span id="cb14-16"><a href="prepare-data-for-meta-analysis.html#cb14-16" aria-hidden="true"></a><span class="st">      </span><span class="kw">length</span>(<span class="kw">unique</span>(slim_PM_dat[<span class="kw">same</span>(slim_PM_dat<span class="op">$</span>cluster_<span class="dv">1</span>, clusters[i, <span class="st">&quot;cluster_1&quot;</span>]) <span class="op">&amp;</span></span>
<span id="cb14-17"><a href="prepare-data-for-meta-analysis.html#cb14-17" aria-hidden="true"></a><span class="st">                                   </span><span class="kw">same</span>(slim_PM_dat<span class="op">$</span>cluster_<span class="dv">2</span>, clusters[i, <span class="st">&quot;cluster_2&quot;</span>]) <span class="op">&amp;</span></span>
<span id="cb14-18"><a href="prepare-data-for-meta-analysis.html#cb14-18" aria-hidden="true"></a><span class="st">                                   </span><span class="kw">same</span>(slim_PM_dat<span class="op">$</span>cluster_<span class="dv">3</span>, clusters[i, <span class="st">&quot;cluster_3&quot;</span>]),</span>
<span id="cb14-19"><a href="prepare-data-for-meta-analysis.html#cb14-19" aria-hidden="true"></a>                                <span class="st">&quot;trial_ref&quot;</span>]))</span>
<span id="cb14-20"><a href="prepare-data-for-meta-analysis.html#cb14-20" aria-hidden="true"></a>   </span>
<span id="cb14-21"><a href="prepare-data-for-meta-analysis.html#cb14-21" aria-hidden="true"></a>}</span>
<span id="cb14-22"><a href="prepare-data-for-meta-analysis.html#cb14-22" aria-hidden="true"></a></span>
<span id="cb14-23"><a href="prepare-data-for-meta-analysis.html#cb14-23" aria-hidden="true"></a>knitr<span class="op">::</span><span class="kw">kable</span>(clusters)</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
cluster_1
</th>
<th style="text-align:left;">
cluster_2
</th>
<th style="text-align:left;">
cluster_3
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
n_x_trial
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
Late
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:right;">
57
</td>
<td style="text-align:right;">
17
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
Recommended
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
15
</td>
</tr>
<tr>
<td style="text-align:left;">
9
</td>
<td style="text-align:left;">
Recommended
</td>
<td style="text-align:left;">
Late
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
11
</td>
<td style="text-align:left;">
Early
</td>
<td style="text-align:left;">
Late
</td>
<td style="text-align:left;">
Early
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
15
</td>
<td style="text-align:left;">
Recommended
</td>
<td style="text-align:left;">
Recommended
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
10
</td>
</tr>
<tr>
<td style="text-align:left;">
30
</td>
<td style="text-align:left;">
Recommended
</td>
<td style="text-align:left;">
Late
</td>
<td style="text-align:left;">
Early
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
33
</td>
<td style="text-align:left;">
Recommended
</td>
<td style="text-align:left;">
Early
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
34
</td>
<td style="text-align:left;">
Recommended
</td>
<td style="text-align:left;">
Early
</td>
<td style="text-align:left;">
Early
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
36
</td>
<td style="text-align:left;">
Early
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
37
</td>
<td style="text-align:left;">
Early
</td>
<td style="text-align:left;">
Late
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
38
</td>
<td style="text-align:left;">
Early
</td>
<td style="text-align:left;">
Late
</td>
<td style="text-align:left;">
Recommended
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
42
</td>
<td style="text-align:left;">
Recommended
</td>
<td style="text-align:left;">
Recommended
</td>
<td style="text-align:left;">
Recommended
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
44
</td>
<td style="text-align:left;">
Early
</td>
<td style="text-align:left;">
Recommended
</td>
<td style="text-align:left;">
Recommended
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
48
</td>
<td style="text-align:left;">
Late
</td>
<td style="text-align:left;">
Recommended
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
59
</td>
<td style="text-align:left;">
Late
</td>
<td style="text-align:left;">
Recommended
</td>
<td style="text-align:left;">
Recommended
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
148
</td>
<td style="text-align:left;">
Late
</td>
<td style="text-align:left;">
Late
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
1
</td>
</tr>
</tbody>
</table>
<p>From this we can see that there are 16 different cluster combinations, which would make the analysis too difficult. We will reduce this to 6 levels within one variable.</p>
<p>Single sprays of either:</p>
<ol style="list-style-type: lower-alpha">
<li><p>early,</p></li>
<li><p>recommended timing,</p></li>
<li><p>late.</p></li>
</ol>
<p>Two or more sprays where the first spray was either:</p>
<ol start="4" style="list-style-type: lower-alpha">
<li><p>early,</p></li>
<li><p>recommended timing,</p></li>
<li><p>late.</p></li>
</ol>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="prepare-data-for-meta-analysis.html#cb15-1" aria-hidden="true"></a>slim_PM_dat &lt;-<span class="st"> </span>slim_PM_dat <span class="op">%&gt;%</span></span>
<span id="cb15-2"><a href="prepare-data-for-meta-analysis.html#cb15-2" aria-hidden="true"></a><span class="st">   </span><span class="kw">mutate</span>(</span>
<span id="cb15-3"><a href="prepare-data-for-meta-analysis.html#cb15-3" aria-hidden="true"></a>      <span class="dt">spray_management =</span> <span class="kw">case_when</span>(</span>
<span id="cb15-4"><a href="prepare-data-for-meta-analysis.html#cb15-4" aria-hidden="true"></a>         fungicide_timing_<span class="dv">1</span> <span class="op">&lt;</span><span class="st"> </span><span class="dv">0</span> <span class="op">&amp;</span></span>
<span id="cb15-5"><a href="prepare-data-for-meta-analysis.html#cb15-5" aria-hidden="true"></a><span class="st">            </span><span class="kw">is.na</span>(fungicide_application_<span class="dv">2</span>) <span class="op">&amp;</span></span>
<span id="cb15-6"><a href="prepare-data-for-meta-analysis.html#cb15-6" aria-hidden="true"></a><span class="st">            </span><span class="kw">is.na</span>(fungicide_application_<span class="dv">3</span>) <span class="op">~</span><span class="st"> &quot;Early&quot;</span>,</span>
<span id="cb15-7"><a href="prepare-data-for-meta-analysis.html#cb15-7" aria-hidden="true"></a>         fungicide_timing_<span class="dv">1</span> <span class="op">&gt;=</span><span class="st"> </span><span class="dv">0</span> <span class="op">&amp;</span></span>
<span id="cb15-8"><a href="prepare-data-for-meta-analysis.html#cb15-8" aria-hidden="true"></a><span class="st">            </span>fungicide_timing_<span class="dv">1</span> <span class="op">&lt;</span><span class="st"> </span><span class="dv">4</span> <span class="op">&amp;</span></span>
<span id="cb15-9"><a href="prepare-data-for-meta-analysis.html#cb15-9" aria-hidden="true"></a><span class="st">            </span><span class="kw">is.na</span>(fungicide_application_<span class="dv">2</span>) <span class="op">&amp;</span></span>
<span id="cb15-10"><a href="prepare-data-for-meta-analysis.html#cb15-10" aria-hidden="true"></a><span class="st">            </span><span class="kw">is.na</span>(fungicide_application_<span class="dv">3</span>) <span class="op">~</span><span class="st"> &quot;Recommended&quot;</span>,</span>
<span id="cb15-11"><a href="prepare-data-for-meta-analysis.html#cb15-11" aria-hidden="true"></a>         fungicide_timing_<span class="dv">1</span> <span class="op">&gt;=</span><span class="st"> </span><span class="dv">4</span> <span class="op">&amp;</span></span>
<span id="cb15-12"><a href="prepare-data-for-meta-analysis.html#cb15-12" aria-hidden="true"></a><span class="st">            </span><span class="kw">is.na</span>(fungicide_application_<span class="dv">2</span>) <span class="op">&amp;</span></span>
<span id="cb15-13"><a href="prepare-data-for-meta-analysis.html#cb15-13" aria-hidden="true"></a><span class="st">            </span><span class="kw">is.na</span>(fungicide_application_<span class="dv">3</span>) <span class="op">~</span><span class="st"> &quot;Late&quot;</span>,</span>
<span id="cb15-14"><a href="prepare-data-for-meta-analysis.html#cb15-14" aria-hidden="true"></a>         fungicide_timing_<span class="dv">1</span> <span class="op">&lt;</span><span class="st"> </span><span class="dv">0</span> <span class="op">&amp;</span></span>
<span id="cb15-15"><a href="prepare-data-for-meta-analysis.html#cb15-15" aria-hidden="true"></a><span class="st">            </span><span class="op">!</span><span class="kw">is.na</span>(fungicide_application_<span class="dv">2</span>) <span class="op">~</span><span class="st"> &quot;Early_plus&quot;</span>,</span>
<span id="cb15-16"><a href="prepare-data-for-meta-analysis.html#cb15-16" aria-hidden="true"></a>         fungicide_timing_<span class="dv">1</span> <span class="op">&gt;=</span><span class="st"> </span><span class="dv">0</span> <span class="op">&amp;</span></span>
<span id="cb15-17"><a href="prepare-data-for-meta-analysis.html#cb15-17" aria-hidden="true"></a><span class="st">            </span>fungicide_timing_<span class="dv">1</span> <span class="op">&lt;</span><span class="st"> </span><span class="dv">4</span> <span class="op">&amp;</span></span>
<span id="cb15-18"><a href="prepare-data-for-meta-analysis.html#cb15-18" aria-hidden="true"></a><span class="st">            </span><span class="op">!</span><span class="kw">is.na</span>(fungicide_application_<span class="dv">2</span>) <span class="op">~</span><span class="st"> &quot;Recommended_plus&quot;</span>,</span>
<span id="cb15-19"><a href="prepare-data-for-meta-analysis.html#cb15-19" aria-hidden="true"></a>         fungicide_timing_<span class="dv">1</span> <span class="op">&gt;=</span><span class="st"> </span><span class="dv">4</span> <span class="op">&amp;</span></span>
<span id="cb15-20"><a href="prepare-data-for-meta-analysis.html#cb15-20" aria-hidden="true"></a><span class="st">            </span><span class="op">!</span><span class="kw">is.na</span>(fungicide_application_<span class="dv">2</span>) <span class="op">~</span><span class="st"> &quot;Late_plus&quot;</span>,</span>
<span id="cb15-21"><a href="prepare-data-for-meta-analysis.html#cb15-21" aria-hidden="true"></a>         <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> &quot;Other&quot;</span></span>
<span id="cb15-22"><a href="prepare-data-for-meta-analysis.html#cb15-22" aria-hidden="true"></a>      )</span>
<span id="cb15-23"><a href="prepare-data-for-meta-analysis.html#cb15-23" aria-hidden="true"></a>   )</span>
<span id="cb15-24"><a href="prepare-data-for-meta-analysis.html#cb15-24" aria-hidden="true"></a></span>
<span id="cb15-25"><a href="prepare-data-for-meta-analysis.html#cb15-25" aria-hidden="true"></a>slim_PM_dat[slim_PM_dat<span class="op">$</span>fungicide_ai <span class="op">==</span><span class="st"> &quot;control&quot;</span>,</span>
<span id="cb15-26"><a href="prepare-data-for-meta-analysis.html#cb15-26" aria-hidden="true"></a>            <span class="kw">c</span>(</span>
<span id="cb15-27"><a href="prepare-data-for-meta-analysis.html#cb15-27" aria-hidden="true"></a>               <span class="st">&quot;fungicide_timing_1&quot;</span>,</span>
<span id="cb15-28"><a href="prepare-data-for-meta-analysis.html#cb15-28" aria-hidden="true"></a>               <span class="st">&quot;fungicide_timing_2&quot;</span>,</span>
<span id="cb15-29"><a href="prepare-data-for-meta-analysis.html#cb15-29" aria-hidden="true"></a>               <span class="st">&quot;fungicide_timing_3&quot;</span>,</span>
<span id="cb15-30"><a href="prepare-data-for-meta-analysis.html#cb15-30" aria-hidden="true"></a>               <span class="st">&quot;spray_management&quot;</span></span>
<span id="cb15-31"><a href="prepare-data-for-meta-analysis.html#cb15-31" aria-hidden="true"></a>            )] &lt;-<span class="st"> &quot;control&quot;</span></span></code></pre></div>
<p>Now to view the number break-down of the <code>spray_management</code> treatments</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="prepare-data-for-meta-analysis.html#cb16-1" aria-hidden="true"></a><span class="kw">table</span>(slim_PM_dat<span class="op">$</span>spray_management)</span></code></pre></div>
<pre><code>## 
##          control            Early       Early_plus             Late 
##               40               13                5               17 
##        Late_plus      Recommended Recommended_plus 
##               20               32               46</code></pre>
<p>There are few ‘Early_plus’ treatments, these treatments therefore will have too few comparisons with other treatments in the meta-analysis to provide accurate results. Therefore we will remove ‘Early_plus’ from the analysis.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="prepare-data-for-meta-analysis.html#cb18-1" aria-hidden="true"></a>slimmer_PM_dat &lt;-</span>
<span id="cb18-2"><a href="prepare-data-for-meta-analysis.html#cb18-2" aria-hidden="true"></a><span class="st">   </span>slim_PM_dat[slim_PM_dat<span class="op">$</span>spray_management <span class="op">!=</span><span class="st"> &quot;Early_plus&quot;</span>, ]</span></code></pre></div>
<hr />
</div>
</div>
<div id="test-dose-effect" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Test dose effect</h2>
<p>Earlier we noted there were different doses of propiconazole, which might influence our analysis.
Let’s check this by comparing a linear mixed effect model including and excluding dose.
We already have a factor breaking down the dose in the <code>trial</code> variable.
Let’s make a new one without dose.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="prepare-data-for-meta-analysis.html#cb19-1" aria-hidden="true"></a>slimmer_PM_dat<span class="op">$</span>trial_noDose &lt;-<span class="st"> </span><span class="kw">paste</span>(slimmer_PM_dat<span class="op">$</span>trial_ref, slimmer_PM_dat<span class="op">$</span>year,</span>
<span id="cb19-2"><a href="prepare-data-for-meta-analysis.html#cb19-2" aria-hidden="true"></a>                 slimmer_PM_dat<span class="op">$</span>location,slimmer_PM_dat<span class="op">$</span>host_genotype,</span>
<span id="cb19-3"><a href="prepare-data-for-meta-analysis.html#cb19-3" aria-hidden="true"></a>                 slimmer_PM_dat<span class="op">$</span>row_spacing,<span class="dt">sep =</span> <span class="st">&quot;_&quot;</span>)</span>
<span id="cb19-4"><a href="prepare-data-for-meta-analysis.html#cb19-4" aria-hidden="true"></a></span>
<span id="cb19-5"><a href="prepare-data-for-meta-analysis.html#cb19-5" aria-hidden="true"></a><span class="kw">cbind</span>(<span class="dt">Dose =</span> <span class="kw">head</span>(slimmer_PM_dat<span class="op">$</span>trial),</span>
<span id="cb19-6"><a href="prepare-data-for-meta-analysis.html#cb19-6" aria-hidden="true"></a>      <span class="dt">NoDose =</span> <span class="kw">head</span>(slimmer_PM_dat<span class="op">$</span>trial_noDose)) <span class="op">%&gt;%</span></span>
<span id="cb19-7"><a href="prepare-data-for-meta-analysis.html#cb19-7" aria-hidden="true"></a><span class="st">   </span><span class="kw">kable</span>()</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;">
Dose
</th>
<th style="text-align:left;">
NoDose
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
mung1011/01_2011_Hermitage_Berken_0.75_lowDose
</td>
<td style="text-align:left;">
mung1011/01_2011_Hermitage_Berken_0.75
</td>
</tr>
<tr>
<td style="text-align:left;">
mung1011/01_2011_Hermitage_Berken_0.75_lowDose
</td>
<td style="text-align:left;">
mung1011/01_2011_Hermitage_Berken_0.75
</td>
</tr>
<tr>
<td style="text-align:left;">
mung1011/01_2011_Hermitage_Crystal_0.75_lowDose
</td>
<td style="text-align:left;">
mung1011/01_2011_Hermitage_Crystal_0.75
</td>
</tr>
<tr>
<td style="text-align:left;">
mung1011/01_2011_Hermitage_Crystal_0.75_lowDose
</td>
<td style="text-align:left;">
mung1011/01_2011_Hermitage_Crystal_0.75
</td>
</tr>
<tr>
<td style="text-align:left;">
mung1011/02_2011_Kingaroy_Berken_0.75_lowDose
</td>
<td style="text-align:left;">
mung1011/02_2011_Kingaroy_Berken_0.75
</td>
</tr>
<tr>
<td style="text-align:left;">
mung1011/02_2011_Kingaroy_Crystal_0.75_lowDose
</td>
<td style="text-align:left;">
mung1011/02_2011_Kingaroy_Crystal_0.75
</td>
</tr>
</tbody>
</table>
<p>Let’s test the dose effect in a basic linear mixed effect model.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="prepare-data-for-meta-analysis.html#cb20-1" aria-hidden="true"></a>m1 &lt;-</span>
<span id="cb20-2"><a href="prepare-data-for-meta-analysis.html#cb20-2" aria-hidden="true"></a><span class="st">   </span><span class="kw">lmer</span>(<span class="kw">log</span>(grain_yield.t.ha <span class="op">*</span><span class="st"> </span><span class="dv">1000</span>) <span class="op">~</span><span class="st"> </span><span class="kw">factor</span>(spray_management) <span class="op">+</span></span>
<span id="cb20-3"><a href="prepare-data-for-meta-analysis.html#cb20-3" aria-hidden="true"></a><span class="st">           </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>trial),</span>
<span id="cb20-4"><a href="prepare-data-for-meta-analysis.html#cb20-4" aria-hidden="true"></a>        <span class="dt">data =</span> slimmer_PM_dat)</span>
<span id="cb20-5"><a href="prepare-data-for-meta-analysis.html#cb20-5" aria-hidden="true"></a></span>
<span id="cb20-6"><a href="prepare-data-for-meta-analysis.html#cb20-6" aria-hidden="true"></a>m2 &lt;-</span>
<span id="cb20-7"><a href="prepare-data-for-meta-analysis.html#cb20-7" aria-hidden="true"></a><span class="st">   </span><span class="kw">lmer</span>(<span class="kw">log</span>(grain_yield.t.ha <span class="op">*</span><span class="st"> </span><span class="dv">1000</span>) <span class="op">~</span><span class="st"> </span><span class="kw">factor</span>(spray_management) <span class="op">+</span></span>
<span id="cb20-8"><a href="prepare-data-for-meta-analysis.html#cb20-8" aria-hidden="true"></a><span class="st">           </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>trial_noDose),</span>
<span id="cb20-9"><a href="prepare-data-for-meta-analysis.html#cb20-9" aria-hidden="true"></a>        <span class="dt">data =</span> slimmer_PM_dat)</span>
<span id="cb20-10"><a href="prepare-data-for-meta-analysis.html#cb20-10" aria-hidden="true"></a></span>
<span id="cb20-11"><a href="prepare-data-for-meta-analysis.html#cb20-11" aria-hidden="true"></a><span class="kw">anova</span>(m1, m2)</span></code></pre></div>
<pre><code>## refitting model(s) with ML (instead of REML)</code></pre>
<pre><code>## Data: slimmer_PM_dat
## Models:
## m1: log(grain_yield.t.ha * 1000) ~ factor(spray_management) + (1 | 
## m1:     trial)
## m2: log(grain_yield.t.ha * 1000) ~ factor(spray_management) + (1 | 
## m2:     trial_noDose)
##    npar   AIC   BIC logLik deviance Chisq Df          Pr(&gt;Chisq)    
## m1    8 -21.4   3.6   18.7    -37.4                                 
## m2    8 -60.2 -35.2   38.1    -76.2  38.8  0 &lt;0.0000000000000002 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Using the model without dose produces a lower AIC, however we should accept the data with dose as there is a significant difference between the models and we should accept the more complicated model <code>m1</code>.
We will retain dose as a variable inside the <code>trial</code> factor.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="prepare-data-for-meta-analysis.html#cb23-1" aria-hidden="true"></a>slimmer_PM_dat &lt;-</span>
<span id="cb23-2"><a href="prepare-data-for-meta-analysis.html#cb23-2" aria-hidden="true"></a><span class="st">   </span>slimmer_PM_dat[, <span class="kw">colnames</span>(slimmer_PM_dat) <span class="op">!=</span><span class="st"> &quot;trial_noDose&quot;</span>] <span class="co">#remove second trial column</span></span></code></pre></div>
</div>
<div id="disease-pressure-factor" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> Disease pressure factor</h2>
<p>We may wish to investigate the impact of spray management in mitigating the yield loss through the effect on the disease pressure.
We will set a categorical variable to indicate the amount of disease pressure in the trial, which will be evaluated on the control plot.
We will create two categories, <code>lowD</code> and <code>highD</code>.
We will use the median <code>AUDPC</code> to separate the trials into these two groups.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="prepare-data-for-meta-analysis.html#cb24-1" aria-hidden="true"></a>slimmer_PM_dat<span class="op">$</span>D_pres &lt;-<span class="st"> </span><span class="ot">NA_character_</span></span>
<span id="cb24-2"><a href="prepare-data-for-meta-analysis.html#cb24-2" aria-hidden="true"></a></span>
<span id="cb24-3"><a href="prepare-data-for-meta-analysis.html#cb24-3" aria-hidden="true"></a>Trial_Dpress &lt;-<span class="st"> </span>slimmer_PM_dat <span class="op">%&gt;%</span></span>
<span id="cb24-4"><a href="prepare-data-for-meta-analysis.html#cb24-4" aria-hidden="true"></a><span class="st">   </span><span class="kw">group_by</span>(trial_ref) <span class="op">%&gt;%</span></span>
<span id="cb24-5"><a href="prepare-data-for-meta-analysis.html#cb24-5" aria-hidden="true"></a><span class="st">   </span><span class="kw">filter</span>(fungicide_ai <span class="op">==</span><span class="st"> &quot;control&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb24-6"><a href="prepare-data-for-meta-analysis.html#cb24-6" aria-hidden="true"></a><span class="st">   </span><span class="kw">summarise</span>(<span class="dt">AUDPC_C =</span> <span class="kw">mean</span>(AUDPC_m, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="prepare-data-for-meta-analysis.html#cb26-1" aria-hidden="true"></a>median_AUDPC &lt;-</span>
<span id="cb26-2"><a href="prepare-data-for-meta-analysis.html#cb26-2" aria-hidden="true"></a><span class="st">   </span><span class="kw">median</span>(<span class="kw">as.vector</span>(Trial_Dpress<span class="op">$</span>AUDPC_C), <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span>
<span id="cb26-3"><a href="prepare-data-for-meta-analysis.html#cb26-3" aria-hidden="true"></a>median_AUDPC</span></code></pre></div>
<pre><code>## [1] 153.6</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="prepare-data-for-meta-analysis.html#cb28-1" aria-hidden="true"></a><span class="kw">write.csv</span>(median_AUDPC, <span class="kw">here</span>(<span class="st">&quot;cache/median_AUDPC_C.csv&quot;</span>), <span class="dt">row.names =</span> <span class="ot">FALSE</span>)</span>
<span id="cb28-2"><a href="prepare-data-for-meta-analysis.html#cb28-2" aria-hidden="true"></a></span>
<span id="cb28-3"><a href="prepare-data-for-meta-analysis.html#cb28-3" aria-hidden="true"></a><span class="kw">sort</span>(Trial_Dpress<span class="op">$</span>AUDPC_C)</span></code></pre></div>
<pre><code>##  [1]  24.50  40.25  41.00  47.12  77.00  78.33  82.60 119.62 153.62 161.00
## [11] 169.00 172.00 192.08 196.00 198.72 228.37 239.61</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="prepare-data-for-meta-analysis.html#cb30-1" aria-hidden="true"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="kw">unique</span>(slimmer_PM_dat<span class="op">$</span>trial_ref)) {</span>
<span id="cb30-2"><a href="prepare-data-for-meta-analysis.html#cb30-2" aria-hidden="true"></a>   <span class="cf">if</span> (<span class="kw">is.na</span>(Trial_Dpress[Trial_Dpress<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>i, <span class="st">&quot;AUDPC_C&quot;</span>])) {</span>
<span id="cb30-3"><a href="prepare-data-for-meta-analysis.html#cb30-3" aria-hidden="true"></a>      <span class="cf">next</span>()</span>
<span id="cb30-4"><a href="prepare-data-for-meta-analysis.html#cb30-4" aria-hidden="true"></a>   }</span>
<span id="cb30-5"><a href="prepare-data-for-meta-analysis.html#cb30-5" aria-hidden="true"></a>   </span>
<span id="cb30-6"><a href="prepare-data-for-meta-analysis.html#cb30-6" aria-hidden="true"></a>   <span class="cf">if</span> (Trial_Dpress[Trial_Dpress<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>i, <span class="st">&quot;AUDPC_C&quot;</span>] <span class="op">&lt;</span><span class="st"> </span>median_AUDPC)</span>
<span id="cb30-7"><a href="prepare-data-for-meta-analysis.html#cb30-7" aria-hidden="true"></a>   {</span>
<span id="cb30-8"><a href="prepare-data-for-meta-analysis.html#cb30-8" aria-hidden="true"></a>      slimmer_PM_dat[slimmer_PM_dat<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>i, <span class="st">&quot;D_pres&quot;</span>] &lt;-<span class="st"> &quot;lowD&quot;</span></span>
<span id="cb30-9"><a href="prepare-data-for-meta-analysis.html#cb30-9" aria-hidden="true"></a>   } <span class="cf">else</span>{</span>
<span id="cb30-10"><a href="prepare-data-for-meta-analysis.html#cb30-10" aria-hidden="true"></a>      <span class="cf">if</span> (Trial_Dpress[Trial_Dpress<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>i, <span class="st">&quot;AUDPC_C&quot;</span>] <span class="op">&gt;=</span><span class="st"> </span>median_AUDPC) {</span>
<span id="cb30-11"><a href="prepare-data-for-meta-analysis.html#cb30-11" aria-hidden="true"></a>         slimmer_PM_dat[slimmer_PM_dat<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>i, <span class="st">&quot;D_pres&quot;</span>] &lt;-<span class="st"> &quot;highD&quot;</span></span>
<span id="cb30-12"><a href="prepare-data-for-meta-analysis.html#cb30-12" aria-hidden="true"></a>      } <span class="cf">else</span>{</span>
<span id="cb30-13"><a href="prepare-data-for-meta-analysis.html#cb30-13" aria-hidden="true"></a>         slimmer_PM_dat[slimmer_PM_dat<span class="op">$</span>trial_ref <span class="op">==</span><span class="st"> </span>i, <span class="st">&quot;D_pres&quot;</span>] &lt;-</span>
<span id="cb30-14"><a href="prepare-data-for-meta-analysis.html#cb30-14" aria-hidden="true"></a><span class="st">            </span><span class="ot">NA_character_</span></span>
<span id="cb30-15"><a href="prepare-data-for-meta-analysis.html#cb30-15" aria-hidden="true"></a>      }</span>
<span id="cb30-16"><a href="prepare-data-for-meta-analysis.html#cb30-16" aria-hidden="true"></a>   }</span>
<span id="cb30-17"><a href="prepare-data-for-meta-analysis.html#cb30-17" aria-hidden="true"></a>}</span></code></pre></div>
<p>Let’s have a quick look to examine whether trials with high disease pressure sustain a greater yield loss.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="prepare-data-for-meta-analysis.html#cb31-1" aria-hidden="true"></a>slimmer_PM_dat <span class="op">%&gt;%</span></span>
<span id="cb31-2"><a href="prepare-data-for-meta-analysis.html#cb31-2" aria-hidden="true"></a><span class="st">   </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> D_pres, <span class="dt">y =</span> grain_yield.t.ha))<span class="op">+</span></span>
<span id="cb31-3"><a href="prepare-data-for-meta-analysis.html#cb31-3" aria-hidden="true"></a><span class="st">   </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></span>
<span id="cb31-4"><a href="prepare-data-for-meta-analysis.html#cb31-4" aria-hidden="true"></a><span class="st">   </span><span class="kw">xlab</span>(<span class="st">&quot;Disease pressure&quot;</span>) <span class="op">+</span></span>
<span id="cb31-5"><a href="prepare-data-for-meta-analysis.html#cb31-5" aria-hidden="true"></a><span class="st">   </span><span class="kw">ylab</span>(<span class="st">&quot;Grain yield (t/ha)&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/plot_disease_pressure-1.png" width="672" /></p>
<p>From this plot we see that in the trials with high disease pressure tended to produce lower yields.
There are 0 trials that contained no data for AUDPC and thus produced <code>NA</code> values.</p>
</div>
<div id="row-spacing" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> Row spacing</h2>
<p>We may want to consider row spacing in the trials.
However one of the locations has <code>NA</code> as the row spacing.
For now let’s assign the most used row spacing of 0.33 m as an approximation so the model can analyse this as a continuous variable.
If we decide to use the row_spacing column as a factor in the final model we will need to remove this approximation.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="prepare-data-for-meta-analysis.html#cb32-1" aria-hidden="true"></a>slimmer_PM_dat[<span class="kw">is.na</span>(slimmer_PM_dat<span class="op">$</span>row_spacing),]</span></code></pre></div>
<pre><code>##                                    trial trial_ref year host_genotype location
## 27 AM1303_2013_Premer_Crystal_NA_lowDose    AM1303 2013       Crystal   Premer
## 28 AM1303_2013_Premer_Crystal_NA_lowDose    AM1303 2013       Crystal   Premer
## 29 AM1303_2013_Premer_Crystal_NA_lowDose    AM1303 2013       Crystal   Premer
## 30 AM1303_2013_Premer_Crystal_NA_lowDose    AM1303 2013       Crystal   Premer
##    row_spacing n planting_date first_sign_disease  fungicide_ai
## 27          NA 3    2012-12-28         2013-02-28       control
## 28          NA 3    2012-12-28         2013-02-28 propiconazole
## 29          NA 3    2012-12-28         2013-02-28 propiconazole
## 30          NA 3    2012-12-28         2013-02-28 propiconazole
##    fungicide_application_1 fungicide_application_2 fungicide_application_3
## 27                    &lt;NA&gt;                    &lt;NA&gt;                    &lt;NA&gt;
## 28              2013-02-28                    &lt;NA&gt;                    &lt;NA&gt;
## 29              2013-02-28              2013-03-19                    &lt;NA&gt;
## 30              2013-02-28              2013-03-19              2013-03-31
##    total_fungicide dose_ai.ha grain_yield.t.ha yield_error yield_gain
## 27               0        0.0            1.422    0.005073         NA
## 28               1       62.5            1.450    0.054783    0.02859
## 29               2       62.5            1.345    0.052398   -0.07693
## 30               3       62.5            1.334    0.021939   -0.08783
##    prop_yield_gain PM_final_severity PM_final_severity_error Y_Msquare Inc_Ms
## 27              NA             8.000                  0.0000  0.009815  417.2
## 28         0.02011             7.833                  0.2887  0.009815  417.2
## 29        -0.05412             2.167                  0.2887  0.009815  417.2
## 30        -0.06178             2.000                  0.8660  0.009815  417.2
##    AUDPC_m AUDPC_sd AUDPS_m AUDPS_sd    dose fungicide_timing_1
## 27  24.500    0.000  49.000    0.000 lowDose       control days
## 28  23.917    1.010  47.833    2.021 lowDose             0 days
## 29   4.083    1.010   8.167    2.021 lowDose             0 days
## 30   3.500    3.031   7.000    6.062 lowDose             0 days
##    fungicide_timing_2 fungicide_timing_3   cluster_1 cluster_2 cluster_3
## 27       control days       control days        Late      &lt;NA&gt;      &lt;NA&gt;
## 28            NA days            NA days Recommended      &lt;NA&gt;      &lt;NA&gt;
## 29            19 days            NA days Recommended      Late      &lt;NA&gt;
## 30            19 days            12 days Recommended      Late     Early
##    spray_management D_pres
## 27          control   lowD
## 28      Recommended   lowD
## 29 Recommended_plus   lowD
## 30 Recommended_plus   lowD</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="prepare-data-for-meta-analysis.html#cb34-1" aria-hidden="true"></a>slimmer_PM_dat[<span class="kw">is.na</span>(slimmer_PM_dat<span class="op">$</span>row_spacing),<span class="st">&quot;row_spacing&quot;</span>] &lt;-<span class="st"> </span><span class="fl">0.33</span></span>
<span id="cb34-2"><a href="prepare-data-for-meta-analysis.html#cb34-2" aria-hidden="true"></a></span>
<span id="cb34-3"><a href="prepare-data-for-meta-analysis.html#cb34-3" aria-hidden="true"></a><span class="kw">write.csv</span>(slimmer_PM_dat, <span class="dt">file =</span> <span class="kw">here</span>(<span class="st">&quot;cache/slimmer_PM_clusterdat.csv&quot;</span>), <span class="dt">row.names =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<div id="mungbeans-age-and-yield-saved" class="section level3" number="4.6.1">
<h3><span class="header-section-number">4.6.1</span> Mungbeans age and yield saved</h3>
<p>The time at which powdery mildew infects in the seasons and the age of the plant might affect the AUDPC and the loss in yield.
Let’s have a look at the age of each trial when each powdery mildew infected it.
We will use the difference between <code>planting_date</code> and <code>first_sign_disease</code> as a proxy for crop maturity.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="prepare-data-for-meta-analysis.html#cb35-1" aria-hidden="true"></a>dat1 &lt;-<span class="st"> </span>slimmer_PM_dat <span class="op">%&gt;%</span></span>
<span id="cb35-2"><a href="prepare-data-for-meta-analysis.html#cb35-2" aria-hidden="true"></a><span class="st">   </span><span class="kw">mutate</span>(<span class="dt">days2PM =</span> first_sign_disease <span class="op">-</span><span class="st"> </span>planting_date) <span class="op">%&gt;%</span></span>
<span id="cb35-3"><a href="prepare-data-for-meta-analysis.html#cb35-3" aria-hidden="true"></a><span class="st">   </span><span class="kw">arrange</span>(<span class="kw">desc</span>(days2PM)) <span class="op">%&gt;%</span></span>
<span id="cb35-4"><a href="prepare-data-for-meta-analysis.html#cb35-4" aria-hidden="true"></a><span class="st">   </span><span class="kw">select</span>(</span>
<span id="cb35-5"><a href="prepare-data-for-meta-analysis.html#cb35-5" aria-hidden="true"></a>      trial_ref,</span>
<span id="cb35-6"><a href="prepare-data-for-meta-analysis.html#cb35-6" aria-hidden="true"></a>      year,</span>
<span id="cb35-7"><a href="prepare-data-for-meta-analysis.html#cb35-7" aria-hidden="true"></a>      location,</span>
<span id="cb35-8"><a href="prepare-data-for-meta-analysis.html#cb35-8" aria-hidden="true"></a>      spray_management,</span>
<span id="cb35-9"><a href="prepare-data-for-meta-analysis.html#cb35-9" aria-hidden="true"></a>      days2PM,</span>
<span id="cb35-10"><a href="prepare-data-for-meta-analysis.html#cb35-10" aria-hidden="true"></a>      grain_yield.t.ha,</span>
<span id="cb35-11"><a href="prepare-data-for-meta-analysis.html#cb35-11" aria-hidden="true"></a>      yield_gain,</span>
<span id="cb35-12"><a href="prepare-data-for-meta-analysis.html#cb35-12" aria-hidden="true"></a>      prop_yield_gain,</span>
<span id="cb35-13"><a href="prepare-data-for-meta-analysis.html#cb35-13" aria-hidden="true"></a>      AUDPC_m,</span>
<span id="cb35-14"><a href="prepare-data-for-meta-analysis.html#cb35-14" aria-hidden="true"></a>      D_pres,</span>
<span id="cb35-15"><a href="prepare-data-for-meta-analysis.html#cb35-15" aria-hidden="true"></a>      PM_final_severity</span>
<span id="cb35-16"><a href="prepare-data-for-meta-analysis.html#cb35-16" aria-hidden="true"></a>   )</span>
<span id="cb35-17"><a href="prepare-data-for-meta-analysis.html#cb35-17" aria-hidden="true"></a>dat1</span></code></pre></div>
<pre><code>##       trial_ref year     location spray_management days2PM grain_yield.t.ha
## 1        AM1304 2013  Marys Mount          control 82 days           1.0938
## 2        AM1304 2013  Marys Mount            Early 82 days           1.2654
## 3   mung1819/01 2019    Hermitage      Recommended 67 days           0.5432
## 4   mung1819/01 2019    Hermitage Recommended_plus 67 days           0.5636
## 5   mung1819/01 2019    Hermitage             Late 67 days           0.5713
## 6   mung1819/01 2019    Hermitage          control 67 days           0.5872
## 7   mung1011/01 2011    Hermitage          control 63 days           1.6619
## 8   mung1011/01 2011    Hermitage      Recommended 63 days           1.7693
## 9   mung1011/01 2011    Hermitage          control 63 days           1.3876
## 10  mung1011/01 2011    Hermitage      Recommended 63 days           1.5439
## 11       AM1303 2013       Premer          control 62 days           1.4216
## 12       AM1303 2013       Premer      Recommended 62 days           1.4502
## 13       AM1303 2013       Premer Recommended_plus 62 days           1.3446
## 14       AM1303 2013       Premer Recommended_plus 62 days           1.3337
## 15       AM1305 2013       Goolhi          control 61 days           0.6944
## 16       AM1305 2013       Goolhi      Recommended 61 days           0.6528
## 17       AM1305 2013       Goolhi Recommended_plus 61 days           0.7222
## 18       AM1305 2013       Goolhi Recommended_plus 61 days           0.6042
## 19       BB1305 2013   Millmerran          control 60 days           0.8021
## 20       BB1305 2013   Millmerran      Recommended 60 days           0.8027
## 21       BB1305 2013   Millmerran Recommended_plus 60 days           0.7714
## 22       BB1305 2013   Millmerran Recommended_plus 60 days           0.7439
## 23  mung1415/01 2015    Hermitage          control 56 days           2.0449
## 24  mung1415/01 2015    Hermitage      Recommended 56 days           2.0183
## 25  mung1415/01 2015    Hermitage Recommended_plus 56 days           2.1524
## 26  mung1415/01 2015    Hermitage             Late 56 days           2.1240
## 27  mung1415/01 2015    Hermitage        Late_plus 56 days           2.1755
## 28  mung1819/02 2019    Hermitage      Recommended 53 days           0.2962
## 29  mung1819/02 2019    Hermitage Recommended_plus 53 days           0.3117
## 30  mung1819/02 2019    Hermitage             Late 53 days           0.2759
## 31  mung1819/02 2019    Hermitage          control 53 days           0.2894
## 32  mung1011/02 2011     Kingaroy          control 48 days           0.7985
## 33  mung1011/02 2011     Kingaroy          control 48 days           0.7985
## 34  mung1011/02 2011     Kingaroy      Recommended 48 days           1.0586
## 35  mung1011/02 2011     Kingaroy      Recommended 48 days           0.7302
## 36  mung1011/02 2011     Kingaroy Recommended_plus 48 days           0.9862
## 37  mung1011/02 2011     Kingaroy Recommended_plus 48 days           0.8754
## 38  mung1112/01 2012       Gatton          control 42 days           0.7380
## 39  mung1112/01 2012       Gatton      Recommended 42 days           0.8100
## 40  mung1112/01 2012       Gatton Recommended_plus 42 days           0.9480
## 41  mung1112/01 2012       Gatton      Recommended 42 days           0.9100
## 42  mung1112/01 2012       Gatton Recommended_plus 42 days           0.9250
## 43  mung1112/01 2012       Gatton      Recommended 42 days           0.8600
## 44  mung1112/01 2012       Gatton Recommended_plus 42 days           0.9440
## 45  mung1617/02 2017 Missen Flats          control 39 days           1.6419
## 46  mung1617/02 2017 Missen Flats          control 39 days           2.0839
## 47  mung1617/02 2017 Missen Flats          control 39 days           1.8249
## 48  mung1617/02 2017 Missen Flats          control 39 days           1.5046
## 49  mung1617/02 2017 Missen Flats          control 39 days           1.4828
## 50  mung1617/02 2017 Missen Flats          control 39 days           1.6085
## 51  mung1617/02 2017 Missen Flats          control 39 days           1.4484
## 52  mung1617/02 2017 Missen Flats          control 39 days           1.2265
## 53  mung1617/02 2017 Missen Flats          control 39 days           1.2279
## 54  mung1617/02 2017 Missen Flats            Early 39 days           1.7914
## 55  mung1617/02 2017 Missen Flats            Early 39 days           1.7243
## 56  mung1617/02 2017 Missen Flats            Early 39 days           1.7330
## 57  mung1617/02 2017 Missen Flats            Early 39 days           1.7173
## 58  mung1617/02 2017 Missen Flats            Early 39 days           1.1302
## 59  mung1617/02 2017 Missen Flats            Early 39 days           1.4435
## 60  mung1617/02 2017 Missen Flats      Recommended 39 days           2.1006
## 61  mung1617/02 2017 Missen Flats      Recommended 39 days           1.9219
## 62  mung1617/02 2017 Missen Flats      Recommended 39 days           1.8592
## 63  mung1617/02 2017 Missen Flats      Recommended 39 days           1.8610
## 64  mung1617/02 2017 Missen Flats      Recommended 39 days           1.4981
## 65  mung1617/02 2017 Missen Flats      Recommended 39 days           1.3891
## 66  mung1617/02 2017 Missen Flats Recommended_plus 39 days           2.1017
## 67  mung1617/02 2017 Missen Flats Recommended_plus 39 days           2.5263
## 68  mung1617/02 2017 Missen Flats Recommended_plus 39 days           2.1795
## 69  mung1617/02 2017 Missen Flats Recommended_plus 39 days           2.0006
## 70  mung1617/02 2017 Missen Flats Recommended_plus 39 days           1.9737
## 71  mung1617/02 2017 Missen Flats Recommended_plus 39 days           1.7988
## 72  mung1617/02 2017 Missen Flats             Late 39 days           2.1434
## 73  mung1617/02 2017 Missen Flats             Late 39 days           1.8778
## 74  mung1617/02 2017 Missen Flats             Late 39 days           1.8279
## 75  mung1617/02 2017 Missen Flats             Late 39 days           1.7806
## 76  mung1617/02 2017 Missen Flats             Late 39 days           1.7564
## 77  mung1617/02 2017 Missen Flats             Late 39 days           1.5337
## 78  mung1617/02 2017 Missen Flats Recommended_plus 39 days           2.3121
## 79  mung1617/02 2017 Missen Flats Recommended_plus 39 days           2.2779
## 80  mung1617/02 2017 Missen Flats Recommended_plus 39 days           2.1126
## 81  mung1617/02 2017 Missen Flats Recommended_plus 39 days           1.3569
## 82  mung1617/02 2017 Missen Flats Recommended_plus 39 days           1.7922
## 83  mung1617/02 2017 Missen Flats Recommended_plus 39 days           1.7424
## 84  mung1617/01 2017    Hermitage          control 39 days           0.4047
## 85  mung1617/01 2017    Hermitage          control 39 days           0.5589
## 86  mung1617/01 2017    Hermitage          control 39 days           0.3163
## 87  mung1617/01 2017    Hermitage          control 39 days           0.3191
## 88  mung1617/01 2017    Hermitage          control 39 days           0.6205
## 89  mung1617/01 2017    Hermitage          control 39 days           0.4736
## 90  mung1617/01 2017    Hermitage          control 39 days           0.6152
## 91  mung1617/01 2017    Hermitage          control 39 days           0.5020
## 92  mung1617/01 2017    Hermitage          control 39 days           0.4721
## 93  mung1617/01 2017    Hermitage            Early 39 days           0.3594
## 94  mung1617/01 2017    Hermitage            Early 39 days           0.5928
## 95  mung1617/01 2017    Hermitage            Early 39 days           0.6020
## 96  mung1617/01 2017    Hermitage            Early 39 days           0.5593
## 97  mung1617/01 2017    Hermitage            Early 39 days           0.5031
## 98  mung1617/01 2017    Hermitage            Early 39 days           0.4824
## 99  mung1617/01 2017    Hermitage Recommended_plus 39 days           0.5060
## 100 mung1617/01 2017    Hermitage Recommended_plus 39 days           0.3798
## 101 mung1617/01 2017    Hermitage Recommended_plus 39 days           0.4386
## 102 mung1617/01 2017    Hermitage Recommended_plus 39 days           0.4444
## 103 mung1617/01 2017    Hermitage Recommended_plus 39 days           0.5183
## 104 mung1617/01 2017    Hermitage Recommended_plus 39 days           0.4407
## 105 mung1617/01 2017    Hermitage      Recommended 39 days           0.6467
## 106 mung1617/01 2017    Hermitage      Recommended 39 days           0.6123
## 107 mung1617/01 2017    Hermitage      Recommended 39 days           0.5530
## 108 mung1617/01 2017    Hermitage      Recommended 39 days           0.4574
## 109 mung1617/01 2017    Hermitage      Recommended 39 days           0.4664
## 110 mung1617/01 2017    Hermitage      Recommended 39 days           0.5208
## 111 mung1617/01 2017    Hermitage Recommended_plus 39 days           0.6590
## 112 mung1617/01 2017    Hermitage Recommended_plus 39 days           0.5448
## 113 mung1617/01 2017    Hermitage Recommended_plus 39 days           0.4199
## 114 mung1617/01 2017    Hermitage Recommended_plus 39 days           0.3415
## 115 mung1617/01 2017    Hermitage Recommended_plus 39 days           0.5638
## 116 mung1617/01 2017    Hermitage Recommended_plus 39 days           0.6566
## 117 mung1617/01 2017    Hermitage             Late 39 days           0.3900
## 118 mung1617/01 2017    Hermitage             Late 39 days           0.4781
## 119 mung1617/01 2017    Hermitage             Late 39 days           0.3266
## 120 mung1617/01 2017    Hermitage             Late 39 days           0.5341
## 121 mung1617/01 2017    Hermitage             Late 39 days           0.5008
## 122 mung1617/01 2017    Hermitage             Late 39 days           0.6831
## 123 mung1112/02 2012     Kingaroy          control 38 days           0.7510
## 124 mung1112/02 2012     Kingaroy      Recommended 38 days           1.0900
## 125 mung1112/02 2012     Kingaroy Recommended_plus 38 days           1.0980
## 126 mung1112/02 2012     Kingaroy      Recommended 38 days           1.0360
## 127 mung1112/02 2012     Kingaroy Recommended_plus 38 days           1.2010
## 128 mung1112/02 2012     Kingaroy      Recommended 38 days           1.0570
## 129 mung1112/02 2012     Kingaroy Recommended_plus 38 days           1.3230
## 130 mung1718/01 2018     Wellcamp        Late_plus 36 days           1.5559
## 131 mung1718/01 2018     Wellcamp        Late_plus 36 days           1.5820
## 132 mung1718/01 2018     Wellcamp          control 36 days           0.9007
## 133 mung1718/01 2018     Wellcamp        Late_plus 36 days           1.4725
## 134 mung1718/01 2018     Wellcamp        Late_plus 36 days           1.5675
## 135 mung1718/01 2018     Wellcamp          control 36 days           1.0891
## 136 mung1718/01 2018     Wellcamp        Late_plus 36 days           1.0845
## 137 mung1718/01 2018     Wellcamp        Late_plus 36 days           1.1543
## 138 mung1718/01 2018     Wellcamp          control 36 days           1.0928
## 139 mung1718/01 2018     Wellcamp        Late_plus 36 days           1.5754
## 140 mung1718/01 2018     Wellcamp        Late_plus 36 days           1.6521
## 141 mung1718/01 2018     Wellcamp          control 36 days           1.5731
## 142 mung1718/01 2018     Wellcamp        Late_plus 36 days           1.2170
## 143 mung1718/01 2018     Wellcamp        Late_plus 36 days           1.6903
## 144 mung1718/01 2018     Wellcamp          control 36 days           1.4513
## 145 mung1718/01 2018     Wellcamp        Late_plus 36 days           1.2344
## 146 mung1718/01 2018     Wellcamp        Late_plus 36 days           1.1731
## 147 mung1718/01 2018     Wellcamp          control 36 days           1.0561
## 148 mung1516/03 2016      Emerald          control 34 days           0.8050
## 149 mung1516/03 2016      Emerald      Recommended 34 days           0.8700
## 150 mung1516/03 2016      Emerald Recommended_plus 34 days           0.8330
## 151 mung1516/03 2016      Emerald Recommended_plus 34 days           0.8480
## 152 mung1516/03 2016      Emerald      Recommended 34 days           0.9260
## 153 mung1516/03 2016      Emerald Recommended_plus 34 days           0.8050
## 154 mung1516/03 2016      Emerald        Late_plus 34 days           0.7840
## 155 mung1516/01 2016    Hermitage          control 34 days           1.8029
## 156 mung1516/01 2016    Hermitage             Late 34 days           2.2159
## 157 mung1516/01 2016    Hermitage        Late_plus 34 days           2.3701
## 158 mung1516/01 2016    Hermitage        Late_plus 34 days           2.2930
## 159 mung1516/01 2016    Hermitage      Recommended 34 days           2.1414
## 160 mung1516/01 2016    Hermitage Recommended_plus 34 days           2.3381
## 161 mung1516/01 2016    Hermitage        Late_plus 34 days           2.3346
## 162 mung1516/02 2016     Kingaroy          control 27 days           0.8107
## 163 mung1516/02 2016     Kingaroy             Late 27 days           1.0309
## 164 mung1516/02 2016     Kingaroy        Late_plus 27 days           1.0339
## 165 mung1516/02 2016     Kingaroy        Late_plus 27 days           0.8728
## 166 mung1516/02 2016     Kingaroy      Recommended 27 days           0.8990
## 167 mung1516/02 2016     Kingaroy Recommended_plus 27 days           0.9438
## 168 mung1516/02 2016     Kingaroy        Late_plus 27 days           0.9443
##     yield_gain prop_yield_gain AUDPC_m D_pres PM_final_severity
## 1           NA              NA  47.125   lowD             3.000
## 2    0.1716821       0.1569665  30.583   lowD             3.167
## 3   -0.0440017      -0.0749392  28.000   lowD             5.000
## 4   -0.0236129      -0.0402150  28.000   lowD             5.000
## 5   -0.0159016      -0.0270820  42.667   lowD             7.167
## 6           NA              NA  41.000   lowD             7.500
## 7           NA              NA  38.500   lowD             4.667
## 8    0.2445887       0.1604151  10.500   lowD             2.000
## 9           NA              NA  42.000   lowD             5.000
## 10   0.0191718       0.0125739  14.000   lowD             2.333
## 11          NA              NA  24.500   lowD             8.000
## 12   0.0285948       0.0201149  23.917   lowD             7.833
## 13  -0.0769336      -0.0541188   4.083   lowD             2.167
## 14  -0.0878268      -0.0617816   3.500   lowD             2.000
## 15          NA              NA 161.000  highD             7.000
## 16  -0.0416667      -0.0600000  37.375  highD             3.750
## 17   0.0277778       0.0400000  14.875  highD             2.750
## 18  -0.0902778      -0.1300000   0.000  highD             1.000
## 19          NA              NA 153.625  highD             8.000
## 20   0.0006127       0.0007639  66.500  highD             8.000
## 21  -0.0306373      -0.0381971  49.062  highD             5.625
## 22  -0.0582108      -0.0725745  11.062  highD             1.625
## 23          NA              NA  82.600   lowD             7.800
## 24  -0.0266272      -0.0130209  61.800   lowD             6.600
## 25   0.1074954       0.0525663  55.400   lowD             5.400
## 26   0.0790062       0.0386348  79.400   lowD             6.600
## 27   0.1305743       0.0638522  73.700   lowD             6.400
## 28   0.0067663       0.0233769  49.800   lowD             5.600
## 29   0.0222400       0.0768373  47.800   lowD             4.600
## 30  -0.0135837      -0.0469305  83.000   lowD             7.333
## 31          NA              NA  78.333   lowD             7.833
## 32          NA              NA 211.000  highD             8.000
## 33          NA              NA 173.167  highD             7.667
## 34   0.2601100       0.3257646  96.333  highD             5.333
## 35  -0.0682650      -0.0854958  50.333  highD             4.333
## 36   0.1877750       0.2351715  55.333  highD             3.333
## 37   0.0769600       0.0963855  45.500  highD             4.000
## 38          NA              NA 169.000  highD             7.500
## 39   0.0720000       0.0975610  85.800  highD             4.300
## 40   0.2100000       0.2845528  59.800  highD             3.300
## 41   0.1720000       0.2330623 137.800  highD             6.300
## 42   0.1870000       0.2533875  59.800  highD             3.300
## 43   0.1220000       0.1653117 111.800  highD             5.300
## 44   0.2060000       0.2791328  26.000  highD             2.000
## 45          NA              NA 233.667  highD             9.000
## 46          NA              NA 239.500  highD             9.000
## 47          NA              NA 241.833  highD             9.000
## 48          NA              NA 242.333  highD             9.000
## 49          NA              NA 239.500  highD             9.000
## 50          NA              NA 241.833  highD             9.000
## 51          NA              NA 237.333  highD             9.000
## 52          NA              NA 241.000  highD             8.667
## 53          NA              NA 239.500  highD             9.000
## 54  -0.0588262      -0.0317939 212.167  highD             8.667
## 55  -0.1259498      -0.0680725 223.833  highD             9.000
## 56   0.2010261       0.1312200 230.667  highD             8.667
## 57   0.1853020       0.1209561 224.167  highD             9.000
## 58  -0.1707497      -0.1312524 229.000  highD             9.000
## 59   0.1425934       0.1096091 223.667  highD             9.000
## 60   0.2503239       0.1352932 159.833  highD             8.000
## 61   0.0716202       0.0387087 197.167  highD             8.667
## 62   0.3272415       0.2136072 168.667  highD             8.333
## 63   0.3290150       0.2147649 198.500  highD             8.333
## 64   0.1971689       0.1515603 175.167  highD             8.667
## 65   0.0881311       0.0677449 186.833  highD             8.000
## 66   0.2514674       0.1359112 174.167  highD             8.000
## 67   0.6760208       0.3653708 158.333  highD             8.000
## 68   0.6475035       0.4226586 149.667  highD             7.667
## 69   0.4686232       0.3058943 191.500  highD             8.000
## 70   0.6728122       0.5171791 153.167  highD             8.000
## 71   0.4979126       0.3827368 188.000  highD             8.000
## 72   0.2931218       0.1584243 199.333  highD             8.000
## 73   0.0275480       0.0148890 207.333  highD             8.000
## 74   0.2959211       0.1931628 207.333  highD             8.000
## 75   0.2486372       0.1622982 218.500  highD             8.000
## 76   0.4554631       0.3501066 192.833  highD             8.000
## 77   0.2327435       0.1789059 218.500  highD             8.000
## 78   0.4619123       0.2496510 201.667  highD             8.000
## 79   0.4276816       0.2311503 214.333  highD             7.667
## 80   0.5806158       0.3789976 204.333  highD             8.000
## 81  -0.1750750      -0.1142804 215.667  highD             8.000
## 82   0.4912386       0.3776067 202.833  highD             8.000
## 83   0.4415085       0.3393800 207.500  highD             8.000
## 84          NA              NA 246.500  highD             8.000
## 85          NA              NA 222.667  highD             8.000
## 86          NA              NA 212.000  highD             8.000
## 87          NA              NA 235.500  highD             8.000
## 88          NA              NA 226.833  highD             8.000
## 89          NA              NA 212.333  highD             8.000
## 90          NA              NA 235.167  highD             8.000
## 91          NA              NA 222.833  highD             8.000
## 92          NA              NA 241.500  highD             8.000
## 93  -0.0868802      -0.1946615 140.000  highD             8.000
## 94   0.0322860       0.0576048 123.833  highD             7.667
## 95   0.1812860       0.4309271 125.500  highD             8.000
## 96   0.1129455       0.2530627 124.667  highD             8.000
## 97  -0.0573711      -0.1023616 159.167  highD             8.000
## 98   0.0617076       0.1466823 137.667  highD             7.667
## 99   0.0596804       0.1337184  98.000  highD             7.000
## 100 -0.1807224      -0.3224450  77.167  highD             7.000
## 101  0.0179611       0.0426945 106.333  highD             7.000
## 102 -0.0019451      -0.0043581 117.667  highD             7.000
## 103 -0.0421730      -0.0752451 114.333  highD             7.000
## 104  0.0200330       0.0476195 125.167  highD             7.000
## 105  0.2003826       0.4489720 140.833  highD             8.000
## 106  0.0518660       0.0925393 155.667  highD             8.000
## 107  0.1323394       0.3145782 152.000  highD             7.667
## 108  0.0111221       0.0249199 188.833  highD             8.000
## 109 -0.0940530      -0.1678094 177.167  highD             8.000
## 110  0.1001438       0.2380475 144.667  highD             8.000
## 111  0.2127255       0.4766273 120.667  highD             7.000
## 112 -0.0156564      -0.0279342  99.500  highD             5.333
## 113 -0.0008316      -0.0019767 113.000  highD             7.000
## 114 -0.1047887      -0.2347868 173.000  highD             7.000
## 115  0.0033556       0.0059871 140.500  highD             7.000
## 116  0.2359362       0.5608336 151.833  highD             7.000
## 117 -0.0563528      -0.1262625 144.833  highD             7.000
## 118 -0.0823390      -0.1469093 155.333  highD             7.000
## 119 -0.0940946      -0.2236680 177.667  highD             7.000
## 120  0.0877364       0.1965798 175.333  highD             7.333
## 121 -0.0596928      -0.1065039 182.667  highD             7.667
## 122  0.2624596       0.6238813 206.167  highD             8.000
## 123         NA              NA 196.000  highD             8.000
## 124  0.3390000       0.4513981 196.000  highD             8.000
## 125  0.3470000       0.4620506  92.400  highD             4.300
## 126  0.2850000       0.3794940 187.600  highD             7.700
## 127  0.4500000       0.5992011 103.600  highD             4.700
## 128  0.3060000       0.4074567 176.400  highD             7.300
## 129  0.5720000       0.7616511  19.600  highD             1.700
## 130  0.3190304       0.2579239 172.500  highD             7.667
## 131  0.3451043       0.2790036 156.333  highD             6.333
## 132         NA              NA 178.833  highD             8.333
## 133  0.2023365       0.1592966 166.167  highD             7.000
## 134  0.2973506       0.2340999 147.667  highD             6.000
## 135         NA              NA 200.167  highD             8.000
## 136  0.0100724       0.0093745 175.667  highD             7.333
## 137  0.0798006       0.0742711 158.000  highD             6.000
## 138         NA              NA 193.667  highD             7.333
## 139  0.3384810       0.2736490 171.500  highD             7.000
## 140  0.4151966       0.3356706 155.333  highD             6.000
## 141         NA              NA 194.333  highD             9.000
## 142 -0.0532369      -0.0419126 189.500  highD             7.333
## 143  0.4201107       0.3307471 161.500  highD             7.000
## 144         NA              NA 220.333  highD             8.667
## 145  0.1599073       0.1488271 170.333  highD             6.667
## 146  0.0986429       0.0918078 150.667  highD             5.667
## 147         NA              NA 205.000  highD             8.000
## 148         NA              NA  77.000   lowD             4.500
## 149  0.0650000       0.0807453  55.000   lowD             3.500
## 150  0.0280000       0.0347826  33.000   lowD             2.500
## 151  0.0430000       0.0534161  39.600   lowD             2.800
## 152  0.1210000       0.1503106  50.600   lowD             3.300
## 153  0.0000000       0.0000000  39.600   lowD             2.800
## 154 -0.0210000      -0.0260870  77.000   lowD             4.500
## 155         NA              NA 119.625   lowD             8.000
## 156  0.4130228       0.2290878  71.750   lowD             6.250
## 157  0.5671527       0.3145778  61.750   lowD             4.500
## 158  0.4900935       0.2718360  50.500   lowD             3.000
## 159  0.3385256       0.1877671  61.125   lowD             4.000
## 160  0.5352451       0.2968798  64.375   lowD             7.500
## 161  0.5316499       0.2948857  53.750   lowD             6.500
## 162         NA              NA 172.000  highD             8.250
## 163  0.2201110       0.2714939 113.500  highD             7.000
## 164  0.2231786       0.2752776  47.000  highD             2.250
## 165  0.0620611       0.0765488  54.000  highD             2.500
## 166  0.0882327       0.1088298 140.000  highD             7.750
## 167  0.1330887       0.1641570  87.500  highD             6.500
## 168  0.1336091       0.1647990  63.500  highD             2.750</code></pre>
<p>From these trials I am most interested in the experiments that directly compare <code>Recommended</code> with <code>Recommended_P_plus</code> and/or <code>Late</code> with <code>Late_plus</code>.
Therefore I will not inspect, <code>AM1304</code> (Marys Mount).</p>
<p>We can see that the crops which were likely the most mature, did not show large yield gains, in particular:</p>
<ul>
<li>Hermitage 2019<br />
</li>
<li>Premer<br />
</li>
<li>Goolhi<br />
</li>
<li>Millmerran</li>
</ul>
<p>Let’s look at this in a quick box plot.
We will only look at trials where powdery mildew set in at flowering which is approximately 60 days after planting.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="prepare-data-for-meta-analysis.html#cb37-1" aria-hidden="true"></a>dat1 <span class="op">%&gt;%</span></span>
<span id="cb37-2"><a href="prepare-data-for-meta-analysis.html#cb37-2" aria-hidden="true"></a><span class="st">   </span><span class="kw">filter</span>(days2PM <span class="op">&gt;=</span><span class="st"> </span><span class="dv">60</span>) <span class="op">%&gt;%</span></span>
<span id="cb37-3"><a href="prepare-data-for-meta-analysis.html#cb37-3" aria-hidden="true"></a><span class="st">   </span><span class="kw">filter</span>(spray_management <span class="op">!=</span><span class="st"> &quot;control&quot;</span> <span class="op">&amp;</span></span>
<span id="cb37-4"><a href="prepare-data-for-meta-analysis.html#cb37-4" aria-hidden="true"></a><span class="st">             </span>trial_ref <span class="op">!=</span><span class="st"> &quot;AM1304&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb37-5"><a href="prepare-data-for-meta-analysis.html#cb37-5" aria-hidden="true"></a><span class="st">   </span><span class="kw">group_by</span>(trial_ref, spray_management) <span class="op">%&gt;%</span></span>
<span id="cb37-6"><a href="prepare-data-for-meta-analysis.html#cb37-6" aria-hidden="true"></a><span class="st">   </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> spray_management, <span class="dt">y =</span> yield_gain, <span class="dt">fill =</span> trial_ref)) <span class="op">+</span></span>
<span id="cb37-7"><a href="prepare-data-for-meta-analysis.html#cb37-7" aria-hidden="true"></a><span class="st">   </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></span>
<span id="cb37-8"><a href="prepare-data-for-meta-analysis.html#cb37-8" aria-hidden="true"></a><span class="st">   </span><span class="kw">scale_fill_usq</span>() <span class="op">+</span></span>
<span id="cb37-9"><a href="prepare-data-for-meta-analysis.html#cb37-9" aria-hidden="true"></a><span class="st">   </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/ageBoxPlot-1.png" width="672" /></p>
<p>We can see in these experiments five experiments there is clearly no benefit to applying a second fungicide application.</p>
<p>For completeness let’s test this with powdery mildew infection commencing 40 - 60 days after planting, instead of greater than 60.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="prepare-data-for-meta-analysis.html#cb38-1" aria-hidden="true"></a>dat1 <span class="op">%&gt;%</span></span>
<span id="cb38-2"><a href="prepare-data-for-meta-analysis.html#cb38-2" aria-hidden="true"></a><span class="st">   </span><span class="kw">filter</span>(days2PM <span class="op">&lt;</span><span class="st"> </span><span class="dv">60</span> <span class="op">&amp;</span></span>
<span id="cb38-3"><a href="prepare-data-for-meta-analysis.html#cb38-3" aria-hidden="true"></a><span class="st">             </span>days2PM <span class="op">&gt;=</span><span class="st"> </span><span class="dv">40</span>) <span class="op">%&gt;%</span></span>
<span id="cb38-4"><a href="prepare-data-for-meta-analysis.html#cb38-4" aria-hidden="true"></a><span class="st">   </span><span class="kw">filter</span>(spray_management <span class="op">!=</span><span class="st"> &quot;control&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb38-5"><a href="prepare-data-for-meta-analysis.html#cb38-5" aria-hidden="true"></a><span class="st">   </span><span class="kw">group_by</span>(trial_ref, spray_management) <span class="op">%&gt;%</span></span>
<span id="cb38-6"><a href="prepare-data-for-meta-analysis.html#cb38-6" aria-hidden="true"></a><span class="st">   </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> spray_management, <span class="dt">y =</span> yield_gain, <span class="dt">fill =</span> trial_ref)) <span class="op">+</span></span>
<span id="cb38-7"><a href="prepare-data-for-meta-analysis.html#cb38-7" aria-hidden="true"></a><span class="st">   </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></span>
<span id="cb38-8"><a href="prepare-data-for-meta-analysis.html#cb38-8" aria-hidden="true"></a><span class="st">   </span><span class="kw">scale_fill_usq</span>() <span class="op">+</span></span>
<span id="cb38-9"><a href="prepare-data-for-meta-analysis.html#cb38-9" aria-hidden="true"></a><span class="st">   </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">0</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/PM40_2_59_days-1.png" width="672" /></p>
<p>We can see here all four experiments benefited, on average, from more than one spray.</p>
<p>Let’s estimate the age of the crop based on crop maturity observations, we will use the <code>PM_MB_means</code> which include some observations of crop maturity.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="prepare-data-for-meta-analysis.html#cb39-1" aria-hidden="true"></a>dat2 &lt;-<span class="st"> </span>PM_MB_means <span class="op">%&gt;%</span></span>
<span id="cb39-2"><a href="prepare-data-for-meta-analysis.html#cb39-2" aria-hidden="true"></a><span class="st">   </span><span class="kw">mutate</span>(</span>
<span id="cb39-3"><a href="prepare-data-for-meta-analysis.html#cb39-3" aria-hidden="true"></a>      <span class="dt">flower =</span> lubridate<span class="op">::</span><span class="kw">ymd</span>(flowering_date) <span class="op">-</span><span class="st"> </span>lubridate<span class="op">::</span><span class="kw">ymd</span>(planting_date),</span>
<span id="cb39-4"><a href="prepare-data-for-meta-analysis.html#cb39-4" aria-hidden="true"></a>      <span class="dt">pod =</span> lubridate<span class="op">::</span><span class="kw">ymd</span>(pod_fill_date) <span class="op">-</span><span class="st"> </span>lubridate<span class="op">::</span><span class="kw">ymd</span>(planting_date),</span>
<span id="cb39-5"><a href="prepare-data-for-meta-analysis.html#cb39-5" aria-hidden="true"></a>      <span class="dt">late_pod =</span> lubridate<span class="op">::</span><span class="kw">ymd</span>(mid_late_pod_fill) <span class="op">-</span><span class="st"> </span>lubridate<span class="op">::</span><span class="kw">ymd</span>(planting_date)</span>
<span id="cb39-6"><a href="prepare-data-for-meta-analysis.html#cb39-6" aria-hidden="true"></a>   ) <span class="op">%&gt;%</span></span>
<span id="cb39-7"><a href="prepare-data-for-meta-analysis.html#cb39-7" aria-hidden="true"></a><span class="st">   </span><span class="kw">select</span>(location, year, flower, pod, late_pod) <span class="op">%&gt;%</span></span>
<span id="cb39-8"><a href="prepare-data-for-meta-analysis.html#cb39-8" aria-hidden="true"></a><span class="st">   </span><span class="kw">distinct</span>() <span class="op">%&gt;%</span></span>
<span id="cb39-9"><a href="prepare-data-for-meta-analysis.html#cb39-9" aria-hidden="true"></a><span class="st">   </span><span class="kw">arrange</span>(<span class="kw">desc</span>(flower))</span>
<span id="cb39-10"><a href="prepare-data-for-meta-analysis.html#cb39-10" aria-hidden="true"></a></span>
<span id="cb39-11"><a href="prepare-data-for-meta-analysis.html#cb39-11" aria-hidden="true"></a>index1 &lt;-</span>
<span id="cb39-12"><a href="prepare-data-for-meta-analysis.html#cb39-12" aria-hidden="true"></a><span class="st">   </span><span class="kw">apply</span>(dat2, <span class="dv">1</span> , <span class="cf">function</span>(X)</span>
<span id="cb39-13"><a href="prepare-data-for-meta-analysis.html#cb39-13" aria-hidden="true"></a>      <span class="op">!</span><span class="st"> </span><span class="kw">all</span>(<span class="kw">is.na</span>(X[<span class="kw">c</span>(<span class="st">&quot;flower&quot;</span>, <span class="st">&quot;pod&quot;</span>, <span class="st">&quot;late_pod&quot;</span>)])))</span>
<span id="cb39-14"><a href="prepare-data-for-meta-analysis.html#cb39-14" aria-hidden="true"></a></span>
<span id="cb39-15"><a href="prepare-data-for-meta-analysis.html#cb39-15" aria-hidden="true"></a>dat2[index1,]</span></code></pre></div>
<pre><code>##       location year  flower     pod late_pod
## 1       Goolhi 2013 71 days 85 days  NA days
## 2       Premer 2013 62 days NA days  NA days
## 3    Hermitage 2011 57 days NA days  NA days
## 4       Gatton 2012 42 days NA days  NA days
## 5     Kingaroy 2012 38 days NA days  NA days
## 14  Millmerran 2013 NA days 68 days  75 days
## 15 Marys Mount 2013 NA days 66 days  NA days
## 19   Hermitage 2016 NA days NA days  72 days
## 20    Kingaroy 2016 NA days 54 days  NA days</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="prepare-data-for-meta-analysis.html#cb41-1" aria-hidden="true"></a><span class="kw">as.double</span>(<span class="kw">mean</span>(dat2[index1, <span class="st">&quot;flower&quot;</span>], <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## [1] 54</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="prepare-data-for-meta-analysis.html#cb43-1" aria-hidden="true"></a><span class="kw">as.double</span>(<span class="kw">mean</span>(dat2[index1, <span class="st">&quot;pod&quot;</span>], <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## [1] 68.25</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="prepare-data-for-meta-analysis.html#cb45-1" aria-hidden="true"></a><span class="kw">as.double</span>(<span class="kw">mean</span>(dat2[index1, <span class="st">&quot;late_pod&quot;</span>], <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## [1] 73.5</code></pre>
<p>We can see that flowering and podding can be variable, and depend on the cumulative degree days.
However, on average flowering starts 54 days after sowing, podding starts 68.25, and late podding 73.5.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="preliminary-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="grain-yield-meta-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
